const express=require('express');
const {requirePermission}=require('../auth/authorization');
const {PERMISSIONS}=require('../auth/permissions');
const repo=require('../services/commercialStructureRepository');
const {getRecommendedCommercialStructureTemplate}=require('../services/commercialStructureTemplate');
const {COMMERCIAL_HEAD_CATEGORIES}=require('../services/commercialHeadCategoryConstants');
const router=express.Router();
const send=(res,result)=>res.status(result.status||200).json(result.ok===false?{message:result.message}:result.node);
router.get('/',requirePermission(PERMISSIONS.COMMERCIAL_READ),async(req,res)=>{try{res.json(await repo.listStructure(req.buildliteAuth.clientId));}catch(e){res.status(e.status||500).json({message:e.message||'Failed to load Commercial Structure.'});}});
router.get('/recommended-template',requirePermission(PERMISSIONS.COMMERCIAL_READ),(req,res)=>res.json(getRecommendedCommercialStructureTemplate()));
router.get('/categories',requirePermission(PERMISSIONS.COMMERCIAL_READ),(req,res)=>res.json({categories:COMMERCIAL_HEAD_CATEGORIES}));
router.put('/heads/:id/buildlite-category',requirePermission(PERMISSIONS.COMMERCIAL_HEAD_CATEGORIES_MANAGE),async(req,res)=>{try{send(res,await repo.setHeadCategory(req.buildliteAuth.clientId,req.params.id,req.body||{},req.buildliteAuth));}catch(e){res.status(e.status||500).json({message:e.message||'Failed to update Commercial Head category.'});}});
router.post('/:type',requirePermission(PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE),async(req,res)=>{try{send(res,await repo.createNode(req.buildliteAuth.clientId,req.params.type,req.body||{},req.buildliteAuth));}catch(e){res.status(e.status||500).json({message:e.message||'Failed to create Commercial Structure item.'});}});
router.put('/:type/:id',requirePermission(PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE),async(req,res)=>{try{send(res,await repo.updateNode(req.buildliteAuth.clientId,req.params.type,req.params.id,req.body||{},req.buildliteAuth));}catch(e){res.status(e.status||500).json({message:e.message||'Failed to update Commercial Structure item.'});}});
router.put('/:type/reorder/siblings',requirePermission(PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE),async(req,res)=>{try{const result=await repo.reorderSiblings(req.buildliteAuth.clientId,req.params.type,req.body||{},req.buildliteAuth);res.status(result.status||200).json(result.ok===false?{message:result.message}:result.structure);}catch(e){res.status(e.status||500).json({message:e.message||'Failed to reorder Commercial Structure.'});}});
module.exports=router;
