import {beforeEach,describe,expect,it,vi} from 'vitest';
const {preview,apply,list}=vi.hoisted(()=>({preview:vi.fn(),apply:vi.fn(),list:vi.fn()}));
vi.mock('../admin/costCodeAuthority',()=>({isCostCodeServerAuthorityEnabled:()=>true}));
vi.mock('../api/costCodes',()=>({CostCodeApiError:class CostCodeApiError extends Error{},previewServerCostCodeImport:preview,applyServerCostCodeImport:apply,listServerCostCodes:list}));
import {applyAuthoritativeCostCodeImport,buildAuthoritativeImportRows,previewAuthoritativeCostCodeImport} from './costCodeImportService';
import {__resetCostCodeServerCacheForTests,ensureCostCodesReady,getCachedCostCodes} from '../admin/costCodeServerCache';

describe('server-authoritative Cost Code import client contract',()=>{
 beforeEach(()=>{preview.mockReset();apply.mockReset();list.mockReset();__resetCostCodeServerCacheForTests();globalThis.localStorage={getItem:vi.fn(()=>null),setItem:vi.fn(),removeItem:vi.fn(),clear:vi.fn()};});
 it('normalizes raw intentions without defaulting hierarchy or touching local structure',()=>{const parsed={headerRowIndex:0,rows:[['Code','Description','Head','Group'],['A','Alpha','',''],['B','Beta','Tenant Head','Tenant Group']],fieldByColumn:['costCode','description','commercialHead','reportingGroup']};const rows=buildAuthoritativeImportRows(parsed);expect(rows[0]).toMatchObject({code:'A',commercialHead:'',commercialFamily:'',reportingGroup:''});expect(rows[1]).toMatchObject({commercialHead:'Tenant Head',reportingGroup:'Tenant Group'});expect(localStorage.getItem('buildlite_commercial_structure_v1')).toBeNull();});
 it('uses server preview evidence and carries token and versions into atomic apply',async()=>{const rows=[{code:'A',description:'Alpha'}],document={catalogueRevision:'rev',reviewToken:'signed',rows:[{code:'A',isUpdate:true,costCodeVersion:4}],proposals:[]};preview.mockResolvedValue({preview:document});apply.mockResolvedValue({summary:{ok:true,updated:1}});expect(await previewAuthoritativeCostCodeImport(rows)).toEqual({ok:true,preview:document});expect(await applyAuthoritativeCostCodeImport(document,rows)).toEqual({ok:true,updated:1});expect(apply).toHaveBeenCalledWith({rows,catalogueRevision:'rev',reviewToken:'signed',expectedCostCodes:[{code:'A',version:4}]});});
 it('rejects duplicate client rows before server preview',async()=>{const rows=[{code:'A',description:'One'},{code:'A',description:'Two',clientIssue:'Duplicate Cost Code in import.'}];expect(await previewAuthoritativeCostCodeImport(rows)).toEqual({ok:false,errors:['Duplicate Cost Code in import.']});expect(preview).not.toHaveBeenCalled();});
 it('invalidates a primed cache only after successful Apply and refetches imported rows',async()=>{list.mockResolvedValueOnce({costCodes:[{id:'old',code:'1100',description:'Land',active:true}]}).mockResolvedValueOnce({costCodes:[{id:'old',code:'1100',description:'Land',active:true},{id:'new',code:'UATC01',description:'Imported',active:true}]});await ensureCostCodesReady();expect(getCachedCostCodes().map(x=>x.code)).toEqual(['1100']);const rows=[{code:'UATC01',description:'Imported'}],document={catalogueRevision:'rev',reviewToken:'signed',rows:[{code:'UATC01',isUpdate:false}],proposals:[]};apply.mockResolvedValue({summary:{ok:true,imported:1}});await applyAuthoritativeCostCodeImport(document,rows);expect(getCachedCostCodes()).toBeNull();await ensureCostCodesReady();expect(list).toHaveBeenCalledTimes(2);expect(getCachedCostCodes().map(x=>x.code)).toEqual(['1100','UATC01']);expect(localStorage.setItem).not.toHaveBeenCalled();});
 it('does not invalidate a valid cache when Apply fails',async()=>{list.mockResolvedValue({costCodes:[{id:'old',code:'1100',description:'Land',active:true}]});await ensureCostCodesReady();apply.mockRejectedValue(new Error('Apply failed'));await expect(applyAuthoritativeCostCodeImport({catalogueRevision:'rev',reviewToken:'signed',rows:[]},[])).rejects.toThrow('Apply failed');expect(getCachedCostCodes().map(x=>x.code)).toEqual(['1100']);expect(list).toHaveBeenCalledTimes(1);});
 it('Preview leaves the authoritative cache intact',async()=>{list.mockResolvedValue({costCodes:[{id:'old',code:'1100',description:'Land',active:true}]});await ensureCostCodesReady();preview.mockResolvedValue({preview:{catalogueRevision:'rev',reviewToken:'signed',rows:[],proposals:[]}});await previewAuthoritativeCostCodeImport([{code:'A',description:'Alpha'}]);expect(getCachedCostCodes().map(x=>x.code)).toEqual(['1100']);expect(list).toHaveBeenCalledTimes(1);expect(localStorage.setItem).not.toHaveBeenCalled();});
});
