/* @vitest-environment jsdom */
import {act} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
const api=vi.hoisted(()=>({load:vi.fn(),invite:vi.fn(),update:vi.fn(),cancel:vi.fn()}));
vi.mock('../../admin/membershipAdminService',()=>({loadMembershipAdministration:api.load,inviteTenantMember:api.invite,updateTenantMember:api.update,cancelTenantInvitation:api.cancel}));
vi.mock('../../auth/BuildLiteAuthProvider',()=>({useBuildLitePrincipal:()=>({permissions:['users.manage','roles.manage'],activeTenant:{membershipId:'me'}})}));
import AdminUsersPage from './AdminUsersPage';
const data={roles:[{key:'commercial_director',name:'Commercial Director'},{key:'finance',name:'Finance'},{key:'qs',name:'QS'}],capabilities:[{key:'company_administration',label:'Company Administration',description:'Manage users.'},{key:'finance_operations',label:'Finance Operations',description:'Accept into Accounts.'}],members:[{id:'me',display_name:'Owner',email_snapshot:'owner@test',role_key:'commercial_director',role_name:'Commercial Director',capabilities:['company_administration'],is_active:true,status:'active',version:1},{id:'finance',display_name:'Finance User',email_snapshot:'finance@test',role_key:'finance',role_name:'Finance',capabilities:[],is_active:true,status:'active',version:1}],invitations:[{id:'invite',email:'pending@test',role_name:'QS',capabilities:[],status:'pending',version:2,expires_at:'2027-01-02T00:00:00Z'},{id:'cancelled',email:'cancelled@test',role_name:'Finance',capabilities:[],status:'cancelled',version:2,expires_at:'2027-01-01T00:00:00Z'}]};
const change=async(node,value)=>act(async()=>{const setter=Object.getOwnPropertyDescriptor(node.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value').set;setter.call(node,value);node.dispatchEvent(new Event('change',{bubbles:true}));node.dispatchEvent(new Event('input',{bubbles:true}));});
describe('real tenant Users administration',()=>{let host,root;beforeEach(()=>{api.load.mockResolvedValue(data);api.invite.mockResolvedValue({});api.update.mockResolvedValue({});api.cancel.mockResolvedValue({ok:true});vi.spyOn(window,'confirm').mockReturnValue(true);host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);});afterEach(()=>{act(()=>root.unmount());host.remove();vi.restoreAllMocks();vi.clearAllMocks();});
 it('renders authoritative members, capabilities and invitation states without placeholder fields',async()=>{await act(async()=>root.render(<AdminUsersPage onBack={vi.fn()}/>));expect(host.textContent).toContain('Owner');expect(host.textContent).toContain('Company Administration');expect(host.textContent).toContain('pending@test');expect(host.textContent).toContain('Pending');expect(host.textContent).not.toContain('Approval Rights');});
 it('requires explicit combined-authority acknowledgement and submits bounded keys',async()=>{await act(async()=>root.render(<AdminUsersPage onBack={vi.fn()}/>));await act(async()=>[...host.querySelectorAll('button')].find(x=>x.textContent==='Invite user').click());const email=host.querySelector('input[type="email"]');await change(email,'director@test');const role=host.querySelector('select');await change(role,'commercial_director');const finance=[...host.querySelectorAll('label')].find(x=>x.textContent.includes('Finance Operations')).querySelector('input');await act(async()=>finance.click());expect(host.textContent).toContain('both authorise payments and accept them into Accounts');const submit=[...host.querySelectorAll('button')].find(x=>x.textContent==='Send invitation');expect(submit.disabled).toBe(true);const ack=[...host.querySelectorAll('label')].find(x=>x.textContent.includes('both authorise')).querySelector('input');await act(async()=>ack.click());await act(async()=>submit.click());expect(api.invite).toHaveBeenCalledWith(expect.objectContaining({email:'director@test',roleKey:'commercial_director',capabilities:['finance_operations'],riskAcknowledged:true}));});
 it('requires an explicit role and presents capabilities and identities as separate readable rows',async()=>{await act(async()=>root.render(<AdminUsersPage onBack={vi.fn()}/>));expect(host.querySelector('.admin-users__identity').textContent).toContain('Owner');await act(async()=>[...host.querySelectorAll('button')].find(x=>x.textContent==='Invite user').click());expect(host.querySelector('select').value).toBe('');expect([...host.querySelectorAll('button')].find(x=>x.textContent==='Send invitation').disabled).toBe(true);expect(host.querySelectorAll('.admin-users__capability')).toHaveLength(2);});
 it('cancels only a pending invitation with its optimistic version and retains cancelled history',async()=>{await act(async()=>root.render(<AdminUsersPage onBack={vi.fn()}/>));expect(host.textContent).toContain('Cancelled');const buttons=[...host.querySelectorAll('button')].filter(x=>x.textContent==='Cancel invitation');expect(buttons).toHaveLength(1);await act(async()=>buttons[0].click());expect(api.cancel).toHaveBeenCalledWith('invite',2);expect(window.confirm).toHaveBeenCalledWith('Cancel the invitation for pending@test?');});
 it('does not allow the current membership to manage itself',async()=>{await act(async()=>root.render(<AdminUsersPage onBack={vi.fn()}/>));expect([...host.querySelectorAll('tr')].find(x=>x.textContent.includes('owner@test')).querySelector('button')).toBeNull();expect([...host.querySelectorAll('tr')].find(x=>x.textContent.includes('finance@test')).querySelector('button').textContent).toBe('Manage');});
});
