/** @vitest-environment jsdom */
import {act} from 'react';import {createRoot} from 'react-dom/client';import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const api=vi.hoisted(()=>({load:vi.fn(),loadCategories:vi.fn(),loadRecommended:vi.fn(),adopt:vi.fn(),saveCategory:vi.fn(),add:vi.fn(),save:vi.fn(),reorder:vi.fn()}));
const catalogue={heads:[{id:'h1',name:'Tenant Custom',buildliteCategory:null,displayOrder:0,active:true,version:3}],families:[],reportingGroups:[{id:'g1',headId:'h1',familyId:null,name:'Custom Group',displayOrder:0,active:true,version:2}],adoptionIssues:[]};
vi.mock('../../auth/BuildLiteAuthProvider',()=>({useBuildLitePermission:()=>true}));
vi.mock('../../admin/commercialStructureService',async()=>{const actual=await vi.importActual('../../admin/commercialStructureService');return {...actual,loadCommercialStructure:(...x)=>api.load(...x),loadCommercialHeadCategories:(...x)=>api.loadCategories(...x),loadRecommendedCommercialStructureTemplate:(...x)=>api.loadRecommended(...x),adoptRecommendedStructure:(...x)=>api.adopt(...x),saveCommercialHeadCategory:(...x)=>api.saveCategory(...x),addStructureNode:(...x)=>api.add(...x),saveStructureNode:(...x)=>api.save(...x),reorderStructureNodes:(...x)=>api.reorder(...x)};});
vi.mock('../../admin/costCodeAdminService',()=>({ensureAdminCostCodesReady:vi.fn(async()=>[]),listAdminCostCodeRecords:vi.fn(()=>[])}));
import AdminCommercialStructurePage from './AdminCommercialStructurePage';
let root,container;describe('server Commercial Structure administration',()=>{beforeEach(()=>{api.load.mockResolvedValue(catalogue);api.loadCategories.mockResolvedValue([{key:'PRELIMINARIES',label:'Preliminaries'}]);api.loadRecommended.mockResolvedValue({name:'BuildLite recommended housebuilder structure',heads:[{name:'Preliminaries',buildliteCategory:'PRELIMINARIES'}]});container=document.createElement('div');document.body.appendChild(container);root=createRoot(container);});afterEach(()=>{act(()=>root.unmount());container.remove();vi.clearAllMocks();});
it('loads the tenant API catalogue, labels the recommended preview and ignores browser local authority',async()=>{localStorage.setItem('buildlite_commercial_structure_v1',JSON.stringify({heads:[{name:'Local Head'}]}));await act(async()=>{root.render(<AdminCommercialStructurePage/>);await Promise.resolve();await Promise.resolve();});expect(container.querySelector('[aria-label="Commercial Head"]').value).toBe('Tenant Custom');expect(container.querySelector('[aria-label="Reporting Group"]').value).toBe('Custom Group');expect(container.textContent).not.toContain('Local Head');expect([...container.querySelectorAll('th')].map(x=>x.textContent)).toEqual(expect.arrayContaining(['Commercial Head','BuildLite category']));});
it('uses stable ID/version when renaming',async()=>{api.save.mockResolvedValue({});await act(async()=>{root.render(<AdminCommercialStructurePage/>);await Promise.resolve();await Promise.resolve();});const input=container.querySelector('[aria-label="Commercial Head"]');await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Renamed');input.dispatchEvent(new Event('input',{bubbles:true}));});await act(async()=>{input.dispatchEvent(new FocusEvent('focusout',{bubbles:true}));await Promise.resolve();});expect(api.save).toHaveBeenCalledWith('head',expect.objectContaining({id:'h1',version:3}),{name:'Renamed'});});
it('reviews and explicitly saves a controlled category without changing the Head name',async()=>{api.saveCategory.mockResolvedValue({});await act(async()=>{root.render(<AdminCommercialStructurePage/>);await Promise.resolve();await Promise.resolve();});const select=container.querySelector('[aria-label="Tenant Custom BuildLite category"]');expect(select.value).toBe('');expect(container.textContent).toContain('Needs review');await act(async()=>{select.value='PRELIMINARIES';select.dispatchEvent(new Event('change',{bubbles:true}));});const save=Array.from(container.querySelectorAll('button')).find(button=>button.textContent==='Save category');expect(save.disabled).toBe(false);await act(async()=>{save.click();await Promise.resolve();});expect(api.saveCategory).toHaveBeenCalledWith(expect.objectContaining({id:'h1',version:3}),'PRELIMINARIES');expect(api.save).not.toHaveBeenCalled();});
it('requires confirmation and reports unchanged Cost Codes after recommended adoption',async()=>{const empty={heads:[],families:[],reportingGroups:[],adoptionIssues:[]};api.load.mockResolvedValueOnce(empty).mockResolvedValueOnce({heads:[{id:'land',name:'Land',buildliteCategory:'LAND',displayOrder:0,active:true,version:1}],families:[],reportingGroups:[],adoptionIssues:[]});api.adopt.mockResolvedValue({created:{heads:9,families:0,reportingGroups:0},alreadyAdopted:false});const onReview=vi.fn();await act(async()=>{root.render(<AdminCommercialStructurePage onReviewCostCodeHierarchy={onReview}/>);await Promise.resolve();await Promise.resolve();});const use=Array.from(container.querySelectorAll('button')).find(button=>button.textContent==='Use BuildLite recommended structure');expect(use).toBeTruthy();expect(api.adopt).not.toHaveBeenCalled();await act(async()=>use.click());expect(container.textContent).toContain('Customer Cost Codes will remain unchanged');await act(async()=>{Array.from(container.querySelectorAll('button')).find(button=>button.textContent==='Create recommended structure').click();await Promise.resolve();await Promise.resolve();});expect(api.adopt).toHaveBeenCalledTimes(1);expect(container.textContent).toContain('9 Commercial Heads created');expect(container.textContent).toContain('not replaced, renumbered or mapped');await act(async()=>Array.from(container.querySelectorAll('button')).find(button=>button.textContent==='Review Cost Code hierarchy').click());expect(onReview).toHaveBeenCalledTimes(1);});});
