/** @vitest-environment jsdom */
import {act} from 'react';import {createRoot} from 'react-dom/client';import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import AdminCostCodeHierarchySetup from './AdminCostCodeHierarchySetup';import {bulkUpdateCostCodeHierarchyOnServer} from '../../admin/costCodeServerMutations';import {getCostCodeOnboardingSummary} from '../../api/costCodes';import {invalidateCostCodes,refreshCostCodes} from '../../admin/costCodeServerCache';
const H='11111111-1111-4111-8111-111111111110',G='11111111-1111-4111-8111-111111111120',C='11111111-1111-4111-8111-111111111111';
const catalogue={heads:[{id:H,name:'Land',active:true,version:1,displayOrder:0},{id:'custom',name:'Tenant Custom',active:true,version:1,displayOrder:1}],families:[],reportingGroups:[{id:G,headId:H,familyId:null,name:'Land Cost',active:true,version:1,displayOrder:0}],adoptionIssues:[]};
vi.mock('../../admin/costCodeServerMutations',()=>({bulkUpdateCostCodeHierarchyOnServer:vi.fn()}));
vi.mock('../../api/costCodes',()=>({getCostCodeOnboardingSummary:vi.fn(),getCostCodeHierarchyWorksheet:vi.fn(),previewCostCodeHierarchyWorksheet:vi.fn(),applyCostCodeHierarchyWorksheet:vi.fn()}));
vi.mock('../../admin/costCodeServerCache',()=>({invalidateCostCodes:vi.fn(),refreshCostCodes:vi.fn()}));
vi.mock('../../admin/commercialStructureService',async()=>{const actual=await vi.importActual('../../admin/commercialStructureService');return {...actual,loadCommercialStructure:vi.fn(async()=>catalogue)};});
const records=[{id:C,version:2,code:'1100',description:'Land Cost',commercialHeadId:null,commercialFamilyId:null,reportingGroupId:null,hierarchyReviewState:'not_reviewed',legacy:{subHeading:'Land',trade:'Land',element:'Land purchase'}},{id:'22222222-2222-4222-8222-222222222222',version:4,code:'4120',description:'Brickwork',hierarchyReviewState:'not_reviewed',legacy:{subHeading:'Super-Structure',trade:'Sub-Con',element:'Brickwork'}}];
let container,root;const click=n=>act(()=>n.click());const button=t=>[...container.querySelectorAll('button')].find(n=>n.textContent.includes(t));const settle=()=>act(async()=>{await Promise.resolve();await Promise.resolve();});
describe('server-authoritative Cost Code hierarchy setup',()=>{beforeEach(()=>{getCostCodeOnboardingSummary.mockResolvedValue({total:2,allocated:0,notReviewed:2,notApplicable:0,needsAttention:0});refreshCostCodes.mockResolvedValue(records);container=document.createElement('div');document.body.appendChild(container);root=createRoot(container);});afterEach(()=>{act(()=>root.unmount());container.remove();vi.clearAllMocks();});
it('resolves tenant Land IDs and applies only after review',async()=>{bulkUpdateCostCodeHierarchyOnServer.mockResolvedValue({ok:true,costCodes:[]});await act(async()=>root.render(<AdminCostCodeHierarchySetup records={records}/>));await settle();expect(container.textContent).toContain('Suggested Commercial Head: Land');click(button('Use suggestion'));expect(container.textContent).toContain('Added to review');click(button('Review 1'));click(button('Apply hierarchy'));await settle();expect(bulkUpdateCostCodeHierarchyOnServer).toHaveBeenCalledWith([{id:C,version:2,commercialHeadId:H,commercialFamilyId:null,reportingGroupId:G,reviewDisposition:null}]);});
it('offers custom tenant heads and clearing sends null IDs',async()=>{await act(async()=>root.render(<AdminCostCodeHierarchySetup records={records}/>));await settle();expect(container.querySelector('[aria-label="Bulk Commercial Head"]').textContent).toContain('Tenant Custom');expect(container.querySelector('[aria-label="1100 Commercial Head"]').textContent).toContain('Land');});
it('allows an individual Head-only allocation when no Reporting Groups exist',async()=>{bulkUpdateCostCodeHierarchyOnServer.mockResolvedValue({ok:true,costCodes:[]});await act(async()=>root.render(<AdminCostCodeHierarchySetup records={records}/>));await settle();const head=container.querySelector('[aria-label="4120 Commercial Head"]');await act(async()=>{head.value='custom';head.dispatchEvent(new Event('change',{bubbles:true}));});expect(container.querySelector('[aria-label="4120 Reporting Group"]').textContent).toContain('No reporting group');click(button('Review 1'));click(button('Apply hierarchy'));await settle();expect(bulkUpdateCostCodeHierarchyOnServer).toHaveBeenCalledWith([{id:records[1].id,version:4,commercialHeadId:'custom',commercialFamilyId:null,reportingGroupId:null,reviewDisposition:null}]);});
it('stays in the hierarchy workflow and reloads authoritative records and readiness after apply',async()=>{const refreshed=[{...records[1],version:5,commercialHeadId:'custom',commercialHead:'Tenant Custom',hierarchyReviewState:'allocated'}];bulkUpdateCostCodeHierarchyOnServer.mockResolvedValue({ok:true,costCodes:refreshed});refreshCostCodes.mockResolvedValue(refreshed);getCostCodeOnboardingSummary.mockResolvedValueOnce({total:2,allocated:0,notReviewed:2,notApplicable:0,needsAttention:0}).mockResolvedValueOnce({total:2,allocated:1,notReviewed:1,notApplicable:0,needsAttention:0});const onApplied=vi.fn();await act(async()=>root.render(<AdminCostCodeHierarchySetup records={records} onApplied={onApplied}/>));await settle();const head=container.querySelector('[aria-label="4120 Commercial Head"]');await act(async()=>{head.value='custom';head.dispatchEvent(new Event('change',{bubbles:true}));});click(button('Review 1'));click(button('Apply hierarchy'));await settle();expect(invalidateCostCodes).toHaveBeenCalledOnce();expect(refreshCostCodes).toHaveBeenCalledOnce();expect(onApplied).toHaveBeenCalledWith(refreshed);expect(container.textContent).toContain('Hierarchy applied. 1 Cost Codes updated.');expect(container.textContent).toContain('2 active · 1 Allocated · 1 Not reviewed');expect(container.textContent).toContain('Cost Code Commercial Hierarchy');});
it('does not read localStorage authority',async()=>{localStorage.setItem('buildlite_commercial_structure_v1',JSON.stringify({heads:[{name:'Local Override'}]}));await act(async()=>root.render(<AdminCostCodeHierarchySetup records={records}/>));await settle();expect(container.textContent).not.toContain('Local Override');expect(container.textContent).toContain('Tenant Custom');});
it('suppresses proposal once stable persisted IDs already satisfy it',async()=>{await act(async()=>root.render(<AdminCostCodeHierarchySetup records={[{...records[0],commercialHeadId:H,reportingGroupId:G,commercialHead:'Land',canonicalReportingGroup:'Land Cost',hierarchyReviewState:'allocated'}]}/>));await settle();const filter=container.querySelector('[aria-label="Show cost codes"]');await act(async()=>{filter.value='allocated';filter.dispatchEvent(new Event('change',{bubbles:true}));});expect(container.textContent).not.toContain('Use suggestion');expect(button('Review 0').disabled).toBe(true);});
it('selects all 300 filtered rows across pages and prepares one Head-only hierarchy',async()=>{const many=Array.from({length:300},(_,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,version:1,code:`N${String(i+1).padStart(3,'0')}`,description:'Imported row',hierarchyReviewState:'not_reviewed',legacy:{trade:i%2?'Trade A':'Trade B'}}));await act(async()=>root.render(<AdminCostCodeHierarchySetup records={many}/>));await settle();click(button('Select all filtered'));const head=container.querySelector('[aria-label="Bulk Commercial Head"]');await act(async()=>{head.value=H;head.dispatchEvent(new Event('change',{bubbles:true}));});click(button('Assign hierarchy'));expect(button('Review 300 changes')).toBeTruthy();});});
