import { useEffect, useMemo, useState } from 'react';
import { listServerCostCodes } from '../../api/costCodes';
import { applyBulkCostCodeClassifications, listCostCodeClassifications, previewBulkCostCodeClassifications } from '../../api/costCodeClassifications';
import { FORECAST_DRIVER_KEYS, SEMANTIC_GROUP_KEYS, forecastDriverLabel, semanticGroupLabel } from '../../admin/costCodeClassification';
import { buildClassificationReviewRows, filterClassificationCandidates } from '../../admin/costCodeBulkClassification';
import { useOptionalUnsavedChanges } from '../../navigation/UnsavedChangesContext.js';
import AdminPageShell from './AdminPageShell';
import { AdminButton } from './adminUi';

const initialFilters={search:'',commercialHeadId:'',commercialFamilyId:'',reportingGroupId:'',semanticGroup:'',active:'active'};
export default function AdminCostCodeBulkClassification({onBack,initialSemanticGroup=''}) {
  const guard=useOptionalUnsavedChanges();
  const [codes,setCodes]=useState([]),[classifications,setClassifications]=useState([]),[filters,setFilters]=useState(initialFilters);
  const [selected,setSelected]=useState(()=>new Set()),[semanticGroup,setSemanticGroup]=useState(initialSemanticGroup||'SELLING'),[forecastDriver,setForecastDriver]=useState('STANDARD_CVR');
  const [preview,setPreview]=useState(null),[ack,setAck]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);try{const [master,classified]=await Promise.all([listServerCostCodes({activeOnly:false}),listCostCodeClassifications()]);setCodes(master.costCodes||[]);setClassifications(classified.classifications||[]);setError('');}catch(e){setError(e.message||'Could not load classification authority.');}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  useEffect(()=>guard?.registerUnsavedChanges({isDirty:()=>selected.size>0||Boolean(preview),title:'Unapplied Cost Code classifications',message:'Leave and discard this reviewed classification batch?'}),[guard,preview,selected]);
  const filtered=useMemo(()=>filterClassificationCandidates(codes,classifications,filters),[codes,classifications,filters]);
  const option=(field,label)=><label>{label}<select className="input" value={filters[field]} onChange={e=>{setFilters(v=>({...v,[field]:e.target.value}));setPreview(null);}}><option value="">All</option>{[...new Map(codes.filter(c=>c[field]).map(c=>[c[field],c[field.replace('Id','')]||c.reportingGroup||c[field]])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>;
  const payload=()=>({semanticGroup,forecastDriver,rows:buildClassificationReviewRows(codes,classifications,selected)});
  const review=async()=>{try{setPreview(await previewBulkCostCodeClassifications(payload()));setAck(false);setError('');}catch(e){setError(e.message);}};
  const apply=async()=>{try{const result=await applyBulkCostCodeClassifications(payload());setMessage(`${result.applied} Cost Code classifications applied.`);setSelected(new Set());setPreview(null);setAck(false);await load();}catch(e){setError(e.message);}};
  return <AdminPageShell title="Bulk Cost Code classification" lead="Filter and explicitly review semantic classifications. Filtering never changes authority." onBack={onBack}>
    {error?<p role="alert" className="po-list-feedback po-list-feedback--error">{error}</p>:null}{message?<p role="status" className="po-list-feedback po-list-feedback--success">{message}</p>:null}
    <section className="po-module-card admin-panel"><h2>Filter</h2><div className="admin-form__grid"><label>Code or description<input className="input" value={filters.search} onChange={e=>setFilters(v=>({...v,search:e.target.value}))}/></label>{option('commercialHeadId','Commercial Head')}{option('commercialFamilyId','Family')}{option('reportingGroupId','Reporting Group')}<label>Current semantic group<select className="input" value={filters.semanticGroup} onChange={e=>setFilters(v=>({...v,semanticGroup:e.target.value}))}><option value="">All</option><option value="UNCLASSIFIED">Unclassified</option>{SEMANTIC_GROUP_KEYS.filter(k=>k!=='UNCLASSIFIED').map(k=><option key={k}>{k}</option>)}</select></label><label>Active state<select className="input" value={filters.active} onChange={e=>setFilters(v=>({...v,active:e.target.value}))}><option value="active">Active</option><option value="inactive">Inactive</option><option value="all">All</option></select></label></div></section>
    <section className="po-module-card admin-panel"><div className="admin-panel__heading"><h2>{loading?'Loading…':`${filtered.length} filtered Cost Codes`}</h2><div><AdminButton variant="secondary" onClick={()=>setSelected(new Set([...selected,...filtered.map(c=>c.id)]))}>Select all {filtered.length} filtered Cost Codes</AdminButton><AdminButton variant="secondary" onClick={()=>setSelected(new Set())}>Clear selection</AdminButton></div></div><p>{selected.size} selected</p><div className="admin-data-table"><table><thead><tr><th></th><th>Code</th><th>Description</th><th>Hierarchy</th></tr></thead><tbody>{filtered.map(code=><tr key={code.id}><td><input aria-label={`Select ${code.code}`} type="checkbox" checked={selected.has(code.id)} onChange={e=>setSelected(current=>{const next=new Set(current);e.target.checked?next.add(code.id):next.delete(code.id);setPreview(null);return next;})}/></td><td>{code.code}</td><td>{code.description}</td><td>{[code.commercialHead,code.commercialFamily,code.reportingGroup].filter(Boolean).join(' → ')||'Unallocated'}</td></tr>)}</tbody></table></div></section>
    <section className="po-module-card admin-panel"><h2>Classification target</h2><label>Semantic group<select className="input" value={semanticGroup} onChange={e=>{setSemanticGroup(e.target.value);setPreview(null);}}>{SEMANTIC_GROUP_KEYS.filter(k=>k!=='UNCLASSIFIED').map(k=><option key={k} value={k}>{semanticGroupLabel(k)}</option>)}</select></label><label>Forecast method<select className="input" value={forecastDriver} onChange={e=>{setForecastDriver(e.target.value);setPreview(null);}}>{FORECAST_DRIVER_KEYS.map(k=><option key={k} value={k}>{forecastDriverLabel(k)}</option>)}</select></label><AdminButton disabled={!selected.size} onClick={review}>Preview</AdminButton>
    {preview?<div aria-label="Classification preview"><h3>Preview</h3><p>Semantic group: {preview.semanticGroup}</p><p>Selected: {preview.counts.selected}</p><p>New classifications: {preview.counts.new}</p><p>Changing existing classifications: {preview.counts.changing}</p><p>Unchanged: {preview.counts.unchanged}</p>{preview.rows.filter(r=>r.change==='changing').map(r=><p key={r.costCodeId}>{r.costCodeKey}: {r.current.semanticGroup} → {r.proposed.semanticGroup}</p>)}{preview.counts.changing?<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I acknowledge the reviewed reclassifications</label>:null}<AdminButton disabled={preview.counts.changing>0&&!ack} onClick={apply}>Apply classifications</AdminButton></div>:null}</section>
  </AdminPageShell>;
}
