/** @vitest-environment jsdom */
import React from 'react';
import {act} from 'react';
import {createRoot} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';

const clerk=vi.hoisted(()=>({signedIn:false,providerProps:null,signInProps:null,signUpProps:null,signOut:vi.fn(),getToken:vi.fn(async()=>'token')}));
vi.mock('@clerk/react',()=>({
 ClerkProvider:props=>{clerk.providerProps=props;return props.children;},
 Show:({when,children})=>when===(clerk.signedIn?'signed-in':'signed-out')?children:null,
 SignIn:props=>{clerk.signInProps=props;return <div>{window.location.pathname.includes('client-trust')&&props.routing==='path'?'Clerk email code verification':'Clerk sign in'}</div>;},
 SignUp:props=>{clerk.signUpProps=props;return <div>Clerk sign up</div>;},
 useAuth:()=>({getToken:clerk.getToken}),
 useClerk:()=>({signOut:clerk.signOut}),
}));
import BuildLiteAuthProvider from './BuildLiteAuthProvider';

describe('membership invitation authentication routing',()=>{let host,root,nativeFetch;
 beforeEach(()=>{vi.stubEnv('VITE_CLERK_PUBLISHABLE_KEY','pk_test');clerk.signedIn=false;clerk.providerProps=null;clerk.signInProps=null;clerk.signUpProps=null;clerk.signOut.mockReset();nativeFetch=globalThis.fetch;host=document.createElement('div');document.body.appendChild(host);root=createRoot(host);});
 afterEach(()=>{act(()=>root.unmount());host.remove();globalThis.fetch=nativeFetch;window.history.replaceState({},'','/');localStorage.clear();vi.unstubAllEnvs();});
 it('uses explicit sign-up and sign-in routes while preserving only the invitation token',async()=>{window.history.replaceState({},'','/sign-up?membershipInvite=invite-token&unsafe=https://evil.test');await act(async()=>root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>));expect(clerk.signUpProps).toMatchObject({routing:'path',path:'/sign-up',signInUrl:'/sign-in?membershipInvite=invite-token',fallbackRedirectUrl:'/?membershipInvite=invite-token'});expect(clerk.providerProps.signInUrl).toBe('/sign-in?membershipInvite=invite-token');expect(clerk.providerProps.signUpUrl).toBe('/sign-up?membershipInvite=invite-token');expect(clerk.providerProps.signUpFallbackRedirectUrl).toBe('/?membershipInvite=invite-token');expect(clerk.providerProps.signInUrl).not.toContain('evil.test');expect(clerk.providerProps.signUpFallbackRedirectUrl).not.toContain('evil.test');});
 it.each([
  ['/sign-in','signIn','path'],
  ['/sign-in/client-trust','signIn','path'],
  ['/sign-in/verify-email-address','signIn','path'],
  ['/sign-in-something','signIn','virtual'],
  ['/sign-up','signUp','path'],
  ['/sign-up/verify-email-address','signUp','path'],
  ['/sign-upgrade','signIn','virtual'],
 ])('recognises the auth path boundary for %s',async(path,component,routing)=>{window.history.replaceState({},'',path);await act(async()=>root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>));const props=component==='signUp'?clerk.signUpProps:clerk.signInProps;expect(props).toMatchObject({routing,...(routing==='path'?{path:component==='signUp'?'/sign-up':'/sign-in'}:{})});});
 it('keeps the mounted Clerk flow path-routed through Device Trust and preserves only membershipInvite',async()=>{window.history.replaceState({},'','/sign-in?membershipInvite=original-token&unsafe=discard-me');await act(async()=>root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>));await act(async()=>clerk.providerProps.routerPush('/sign-in/client-trust?strategy=email_code&return_url=https://evil.test'));expect(window.location.pathname).toBe('/sign-in/client-trust');expect(window.location.search).toBe('?membershipInvite=original-token');expect(clerk.signInProps).toMatchObject({routing:'path',path:'/sign-in',fallbackRedirectUrl:'/?membershipInvite=original-token'});expect(host.textContent).toContain('Clerk email code verification');await act(async()=>clerk.providerProps.routerReplace('/sign-in/client-trust/verify?attempt=1'));expect(window.location.pathname).toBe('/sign-in/client-trust/verify');expect(window.location.search).toBe('?membershipInvite=original-token');expect(clerk.signInProps.routing).toBe('path');expect(localStorage.getItem('membershipInvite')).toBeNull();});
 it('retains nested path routing on a production-shaped direct refresh mount',async()=>{window.history.replaceState({},'','/sign-up/verify-email-address?membershipInvite=refresh-token');await act(async()=>root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>));expect(clerk.signUpProps).toMatchObject({routing:'path',path:'/sign-up',fallbackRedirectUrl:'/?membershipInvite=refresh-token'});expect(clerk.signInProps).toBeNull();});
 it('fails closed instead of following a cross-origin Clerk router destination',async()=>{window.history.replaceState({},'','/sign-in?membershipInvite=bounded-token');await act(async()=>root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>));await act(async()=>clerk.providerProps.routerPush('https://evil.test/callback?membershipInvite=attacker'));expect(window.location.pathname).toBe('/sign-in');expect(window.location.search).toBe('?membershipInvite=bounded-token');});
 it('preserves a mismatched invitation, refuses acceptance and offers a safe sign-out continuation',async()=>{clerk.signedIn=true;window.history.replaceState({},'','/sign-in?membershipInvite=wrong-account-token');const calls=[];globalThis.fetch=vi.fn(async input=>{calls.push(String(input));if(String(input).endsWith('/api/membership-invitations/accept'))return new Response(JSON.stringify({message:'This invitation belongs to a different authenticated email.'}),{status:403,headers:{'Content-Type':'application/json'}});throw new Error(`Unexpected request ${input}`);});await act(async()=>{root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>);await new Promise(resolve=>setTimeout(resolve,20));});expect(host.textContent).toContain('This invitation is for a different account.');expect(window.location.search).toContain('membershipInvite=wrong-account-token');const button=[...host.querySelectorAll('button')].find(x=>x.textContent==='Sign out & continue');await act(async()=>button.click());expect(clerk.signOut).toHaveBeenCalledWith({redirectUrl:'/sign-in?membershipInvite=wrong-account-token'});expect(calls).toHaveLength(1);});
 it('accepts once, clears invitation context and establishes the tenant principal',async()=>{clerk.signedIn=true;window.history.replaceState({},'','/sign-up?membershipInvite=fresh-token');const calls=[];globalThis.fetch=vi.fn(async input=>{calls.push(String(input));if(String(input).endsWith('/api/membership-invitations/accept'))return new Response(JSON.stringify({clientId:'willow'}),{status:200,headers:{'Content-Type':'application/json'}});if(String(input).endsWith('/api/auth/me'))return new Response(JSON.stringify({user:{displayName:'Finance User'},activeTenant:{clientId:'willow',roleName:'Finance'},permissions:[]}),{status:200,headers:{'Content-Type':'application/json'}});throw new Error(`Unexpected request ${input}`);});await act(async()=>{root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>);await new Promise(resolve=>setTimeout(resolve,20));});expect(calls.filter(x=>x.endsWith('/api/membership-invitations/accept'))).toHaveLength(1);expect(calls.filter(x=>x.endsWith('/api/auth/me'))).toHaveLength(1);expect(window.location.pathname).toBe('/');expect(window.location.search).toBe('');expect(localStorage.getItem('buildlite_active_client_id')).toBe('willow');expect(host.textContent).toContain('protected');});
 it('resumes acceptance once from a nested Device Trust return with the original token',async()=>{window.history.replaceState({},'','/sign-in?membershipInvite=device-token&unsafe=discard-me');await act(async()=>root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>));await act(async()=>clerk.providerProps.routerPush('/sign-in/client-trust?strategy=email_code'));clerk.signedIn=true;const bodies=[];globalThis.fetch=vi.fn(async(input,options={})=>{if(String(input).endsWith('/api/membership-invitations/accept')){bodies.push(JSON.parse(options.body));return new Response(JSON.stringify({clientId:'willow'}),{status:200,headers:{'Content-Type':'application/json'}});}if(String(input).endsWith('/api/auth/me'))return new Response(JSON.stringify({user:{displayName:'Finance User'},activeTenant:{clientId:'willow',roleName:'Finance'},permissions:[]}),{status:200,headers:{'Content-Type':'application/json'}});throw new Error(`Unexpected request ${input}`);});await act(async()=>{root.render(<BuildLiteAuthProvider><span>protected</span></BuildLiteAuthProvider>);await new Promise(resolve=>setTimeout(resolve,20));});expect(bodies).toEqual([{token:'device-token'}]);expect(window.location.pathname).toBe('/');expect(window.location.search).toBe('');expect(host.textContent).toContain('protected');});
});
