const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const {randomUUID}=require('crypto');
const request=require('supertest');
const createApp=require('../app');
const {pool,isDbConfigured}=require('../db');
const {prepareIntegrationTestDatabase}=require('./integrationTestSetup');
const repo=require('../services/developmentBudgetRepository');
const {hashCanonicalJson,verifyJsonIntegrity}=require('../services/canonicalJsonIntegrity');
const {PERMISSIONS}=require('../auth/permissions');
const sql=name=>fs.readFileSync(path.join(__dirname,'..','migrations',name),'utf8');
let f;
async function post(eventType,key,lines,extra={}){return repo.postEvent(f.client.id,f.dev,{eventType,effectiveDate:'2026-09-09',reference:`REF-${key}`,reason:`Reason ${key}`,idempotencyKey:key,lines,...extra},f.auth);}
async function postFor(developmentId,eventType,key,lines,extra={}){return repo.postEvent(f.client.id,developmentId,{eventType,effectiveDate:'2026-09-09',reference:`REF-${key}`,reason:`Reason ${key}`,idempotencyKey:key,lines,...extra},f.auth);}

if(!isDbConfigured())test('Development Budget Authority skipped — test DB unavailable',()=>assert.ok(true));else{
test('PostgreSQL Date values and canonical strings map to calendar-stable API dates',()=>{
  const databaseDate=new Date(2026,8,9);
  assert.equal(repo.canonicalDatabaseDate(databaseDate),'2026-09-09');
  assert.equal(repo.canonicalDatabaseDate('2026-09-09'),'2026-09-09');
  assert.equal(repo.canonicalDatabaseDate('not-a-date'),null);
});
test.before(async()=>{await prepareIntegrationTestDatabase(pool);for(const name of ['004_developments.sql','017_cost_codes_tenant_master.sql','031_rbac_identity_foundation.sql'])await pool.query(sql(name));await pool.query('DROP TABLE IF EXISTS development_budget_event_lines,development_budget_events CASCADE');await pool.query(sql('044_development_budget_authority.sql'));
 const client=(await pool.query('INSERT INTO clients(code,name,is_active) VALUES($1,$2,false) RETURNING *',[`BUD_${randomUUID().slice(0,8)}`,'Budget test'])).rows[0];const dev=`dev-budget-${randomUUID()}`;await pool.query("INSERT INTO developments(id,client_id,job_number,development_name,status,payload) VALUES($1,$2,$3,'Budget Development','live','{}')",[dev,client.id,`B-${randomUUID()}`]);
 const user=(await pool.query("INSERT INTO buildlite_users(auth_provider,provider_user_id,email_snapshot,display_name,status) VALUES('clerk',$1,'budget@test','Budget QS','active') RETURNING *",[`provider-${randomUUID()}`])).rows[0];const role=(await pool.query("SELECT id FROM roles WHERE key='qs'")).rows[0];const membership=(await pool.query('INSERT INTO client_user_memberships(client_id,user_id,role_id,is_active) VALUES($1,$2,$3,true) RETURNING *',[client.id,user.id,role.id])).rows[0];
 const customRole=(await pool.query('INSERT INTO roles(key,name,description,is_system) VALUES($1,$2,$3,false) RETURNING *',[`budget_poster_${randomUUID().slice(0,8)}`,'Budget Poster','Test permission without role-name dependency'])).rows[0];await pool.query("INSERT INTO role_permissions(role_id,permission_key) VALUES($1,'development_budget.post')",[customRole.id]);const customUser=(await pool.query("INSERT INTO buildlite_users(auth_provider,provider_user_id,email_snapshot,display_name,status) VALUES('clerk',$1,'budget-custom@test','Budget Custom','active') RETURNING *",[`provider-${randomUUID()}`])).rows[0];const customMembership=(await pool.query('INSERT INTO client_user_memberships(client_id,user_id,role_id,is_active) VALUES($1,$2,$3,true) RETURNING *',[client.id,customUser.id,customRole.id])).rows[0];
 const cc1=(await pool.query(`INSERT INTO cost_codes(client_id,code,description,commercial_head,reporting_group,hierarchy_mode,is_active) VALUES($1,'1000','Land','Land','Land','two-level',true) RETURNING *`,[client.id])).rows[0];const cc2=(await pool.query(`INSERT INTO cost_codes(client_id,code,description,commercial_head,reporting_group,hierarchy_mode,is_active) VALUES($1,'2000','Build','House Build','Build','two-level',true) RETURNING *`,[client.id])).rows[0];const inactive=(await pool.query(`INSERT INTO cost_codes(client_id,code,description,commercial_head,reporting_group,hierarchy_mode,is_active) VALUES($1,'3000','Inactive','Land','Land','two-level',false) RETURNING *`,[client.id])).rows[0];
 f={client,dev,user,membership,customRole,customUser,customMembership,cc1,cc2,inactive,auth:{clientId:client.id,userId:user.id,membershipId:membership.id,providerUserId:user.provider_user_id,displayName:user.display_name,roleKey:'qs',permissions:[PERMISSIONS.COMMERCIAL_READ,PERMISSIONS.DEVELOPMENT_BUDGET_POST]}};});
test.after(async()=>{if(!f)return;await pool.query('ALTER TABLE development_budget_event_lines DISABLE TRIGGER USER');await pool.query('ALTER TABLE development_budget_events DISABLE TRIGGER USER');await pool.query('DELETE FROM development_budget_event_lines WHERE client_id=$1',[f.client.id]);await pool.query('DELETE FROM development_budget_events WHERE client_id=$1',[f.client.id]);await pool.query('ALTER TABLE development_budget_event_lines ENABLE TRIGGER USER');await pool.query('ALTER TABLE development_budget_events ENABLE TRIGGER USER');await pool.query('ALTER TABLE authorization_action_audit DISABLE TRIGGER USER');await pool.query('DELETE FROM authorization_action_audit WHERE client_id=$1',[f.client.id]);await pool.query('ALTER TABLE authorization_action_audit ENABLE TRIGGER USER');await pool.query('DELETE FROM cost_codes WHERE client_id=$1',[f.client.id]);await pool.query('DELETE FROM developments WHERE client_id=$1',[f.client.id]);await pool.query('DELETE FROM client_user_memberships WHERE client_id=$1',[f.client.id]);await pool.query('DELETE FROM clients WHERE id=$1',[f.client.id]);await pool.query('DELETE FROM buildlite_users WHERE id IN($1,$2)',[f.user.id,f.customUser.id]);await pool.query('DELETE FROM role_permissions WHERE role_id=$1',[f.customRole.id]);await pool.query('DELETE FROM roles WHERE id=$1',[f.customRole.id]);});

test('migration is additive, immutable, permissioned and zero-backfill',async()=>{const migration=sql('044_development_budget_authority.sql');assert.doesNotMatch(migration,/INSERT INTO development_budget_events/i);assert.match(migration,/development_budget\.post/);assert.equal(Number((await pool.query('SELECT count(*) n FROM development_budget_events WHERE client_id=$1',[f.client.id])).rows[0].n),0);const grants=await pool.query("SELECT r.key FROM roles r JOIN role_permissions rp ON rp.role_id=r.id WHERE rp.permission_key='development_budget.post' AND r.is_system ORDER BY r.key");assert.deepEqual(grants.rows.map(r=>r.key),['commercial_director','commercial_manager','qs']);assert.equal(grants.rows.some(r=>r.key==='admin'),false);});

test('opening, addition, omission, transfer and correction derive exact original/current authority',async()=>{const opening=await post('opening_budget','opening',[{costCodeId:f.cc1.id,amount:'1000.01'},{costCodeId:f.cc2.id,amount:'2000.02'}]);assert.equal(opening.status,201);assert.equal(opening.authority.totalOriginalBudget,3000.03);assert.equal(opening.authority.totalCurrentBudget,3000.03);assert.equal(opening.event.createdBy.userId,f.user.id);assert.equal(opening.event.createdBy.permission,'development_budget.post');assert.equal(verifyJsonIntegrity(opening.event.sourceSnapshot,opening.event.sourceSnapshotSha256,opening.event.sourceSnapshotHashScheme).valid,true);
 assert.equal((await post('opening_budget','opening-2',[{costCodeId:f.cc1.id,amount:'1'}])).status,409);
 await post('opening_adjustment','opening-adjustment',[{costCodeId:f.cc1.id,amount:'10.00'},{costCodeId:f.cc2.id,amount:'-1.00'}]);await post('addition','add',[{costCodeId:f.cc1.id,amount:'100.10'}]);await post('omission','omit',[{costCodeId:f.cc2.id,amount:'-50.05'}]);assert.equal((await post('transfer','short-transfer',[{costCodeId:f.cc1.id,amount:'1'}])).status,400);assert.equal((await post('transfer','bad-transfer',[{costCodeId:f.cc1.id,amount:'10'},{costCodeId:f.cc2.id,amount:'-9.99'}])).status,400);await post('transfer','transfer',[{costCodeId:f.cc1.id,amount:'-25.01'},{costCodeId:f.cc2.id,amount:'25.01'}]);await post('correction','correct',[{costCodeId:f.cc1.id,amount:'-0.01'},{costCodeId:f.cc2.id,amount:'1.00'}]);const read=(await repo.getAuthority(f.client.id,f.dev,f.auth)).authority;assert.equal(read.totalOriginalBudget,3000.03);assert.equal(read.totalCurrentBudget,3060.07);assert.equal(read.perCostCode.find(x=>x.costCode==='1000').currentBudget,1085.09);assert.equal(read.perCostCode.find(x=>x.costCode==='2000').currentBudget,1974.98);assert.equal(read.canonicalDigest,hashCanonicalJson(read.sourceDocument));assert.equal((await repo.getAuthority(f.client.id,f.dev,f.auth)).authority.canonicalDigest,read.canonicalDigest);});

test('idempotency, reversal, exact negation and immutable history',async()=>{const first=await post('addition','idem',[{costCodeId:f.cc1.id,amount:'12.34'}]);const replay=await post('addition','idem',[{costCodeId:f.cc1.id,amount:'12.34'}]);assert.equal(replay.replayed,true);assert.equal(replay.event.id,first.event.id);assert.equal((await post('addition','idem',[{costCodeId:f.cc1.id,amount:'12.35'}])).status,409);const reversal=await post('reversal','reverse',[],{reversesEventId:first.event.id});assert.equal(reversal.event.lines[0].signedAmount,-12.34);assert.equal((await post('reversal','reverse-again',[],{reversesEventId:first.event.id})).status,409);await assert.rejects(pool.query('UPDATE development_budget_events SET reason=$1 WHERE id=$2',['rewrite',first.event.id]),/append-only/i);await assert.rejects(pool.query('DELETE FROM development_budget_event_lines WHERE event_id=$1',[first.event.id]),/append-only/i);});

test('known-answer budget position and non-opening reversal preserve the original baseline',async()=>{const dev=`dev-budget-known-${randomUUID()}`;await pool.query("INSERT INTO developments(id,client_id,job_number,development_name,status,payload) VALUES($1,$2,$3,'Known Answer','live','{}')",[dev,f.client.id,`K-${randomUUID()}`]);const opening=await postFor(dev,'opening_budget','known-opening',[{costCodeId:f.cc1.id,amount:'100000.00'},{costCodeId:f.cc2.id,amount:'50000.00'}]);const addition=await postFor(dev,'addition','known-add',[{costCodeId:f.cc1.id,amount:'10000.00'}]);await postFor(dev,'omission','known-omit',[{costCodeId:f.cc2.id,amount:'-5000.00'}]);await postFor(dev,'transfer','known-transfer',[{costCodeId:f.cc1.id,amount:'-2000.00'},{costCodeId:f.cc2.id,amount:'2000.00'}]);let authority=(await repo.getAuthority(f.client.id,dev,f.auth)).authority;assert.equal(authority.totalOriginalBudget,150000);assert.equal(authority.perCostCode.find(x=>x.costCode==='1000').currentBudget,108000);assert.equal(authority.perCostCode.find(x=>x.costCode==='2000').currentBudget,47000);assert.equal(authority.totalCurrentBudget,155000);assert.equal((await postFor(dev,'reversal','known-opening-reversal',[],{reversesEventId:opening.event.id})).status,400);await postFor(dev,'reversal','known-add-reversal',[],{reversesEventId:addition.event.id});authority=(await repo.getAuthority(f.client.id,dev,f.auth)).authority;assert.equal(authority.totalOriginalBudget,150000);assert.equal(authority.perCostCode.find(x=>x.costCode==='1000').currentBudget,98000);assert.equal(authority.perCostCode.find(x=>x.costCode==='2000').currentBudget,47000);assert.equal(authority.totalCurrentBudget,145000);});

test('database guards sequence, source-bound lines, immutable headers and opening reversal',async()=>{const current=(await repo.getAuthority(f.client.id,f.dev,f.auth)).authority;const opening=current.events.find(event=>event.eventType==='opening_budget');const add=current.events.find(event=>event.eventType==='addition');await assert.rejects(pool.query(`INSERT INTO development_budget_events(client_id,development_id,sequence_number,event_type,effective_date,reference,reason,idempotency_key,source_snapshot,source_snapshot_sha256,source_snapshot_hash_scheme,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name,created_role_key,created_permission_key) VALUES($1,$2,$3,'correction','2026-09-09','BAD-SEQ','Bad sequence','bad-sequence','{"lines":[]}','0000000000000000000000000000000000000000000000000000000000000000','canonical_json_sha256_v1',$4,$5,$6,$7,'qs','development_budget.post')`,[f.client.id,f.dev,current.dataVersion+2,f.user.id,f.membership.id,f.user.provider_user_id,f.user.display_name]),/sequence is invalid/i);await assert.rejects(pool.query(`INSERT INTO development_budget_events(client_id,development_id,sequence_number,event_type,effective_date,reference,reason,reverses_event_id,idempotency_key,source_snapshot,source_snapshot_sha256,source_snapshot_hash_scheme,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name,created_role_key,created_permission_key) VALUES($1,$2,$3,'reversal','2026-09-09','BAD-OPENING','Bad opening reversal',$4,'bad-opening-reversal','{"lines":[]}','0000000000000000000000000000000000000000000000000000000000000000','canonical_json_sha256_v1',$5,$6,$7,$8,'qs','development_budget.post')`,[f.client.id,f.dev,current.dataVersion+1,opening.id,f.user.id,f.membership.id,f.user.provider_user_id,f.user.display_name]),/reversal boundary is invalid/i);await assert.rejects(pool.query('INSERT INTO development_budget_event_lines(client_id,development_id,event_id,line_number,cost_code_id,signed_amount) VALUES($1,$2,$3,99,$4,1.00)',[f.client.id,f.dev,add.id,f.cc1.id]),/frozen source snapshot/i);await assert.rejects(pool.query('DELETE FROM development_budget_events WHERE id=$1',[add.id]),/append-only/i);});

test('sign, empty, active cost-code, tenant and permission guards',async()=>{assert.equal((await post('addition','negative-add',[{costCodeId:f.cc1.id,amount:'-1'}])).status,400);assert.equal((await post('omission','positive-omit',[{costCodeId:f.cc1.id,amount:'1'}])).status,400);assert.equal((await post('correction','zero',[{costCodeId:f.cc1.id,amount:'0'}])).status,400);assert.equal((await post('correction','empty',[])).status,400);assert.equal((await post('correction','inactive',[{costCodeId:f.inactive.id,amount:'1'}])).status,400);await assert.rejects(repo.postEvent(f.client.id,f.dev,{eventType:'addition'}, {...f.auth,permissions:[PERMISSIONS.COMMERCIAL_READ]}),/development_budget\.post/);const other=(await pool.query('INSERT INTO clients(code,name,is_active) VALUES($1,$2,false) RETURNING *',[`OTHER_${randomUUID().slice(0,8)}`,'Other'])).rows[0];const otherDev=`dev-other-${randomUUID()}`;await pool.query("INSERT INTO developments(id,client_id,job_number,development_name,status,payload) VALUES($1,$2,$3,'Other Development','live','{}')",[otherDev,other.id,`O-${randomUUID()}`]);const foreign=(await pool.query(`INSERT INTO cost_codes(client_id,code,description,commercial_head,reporting_group,hierarchy_mode,is_active) VALUES($1,'X','X','Land','Land','two-level',true) RETURNING *`,[other.id])).rows[0];assert.equal((await post('correction','foreign',[{costCodeId:foreign.id,amount:'1'}])).status,400);assert.equal((await postFor(otherDev,'correction','wrong-tenant',[{costCodeId:f.cc1.id,amount:'1'}])).status,404);await pool.query('DELETE FROM cost_codes WHERE client_id=$1',[other.id]);await pool.query('DELETE FROM developments WHERE client_id=$1',[other.id]);await pool.query('DELETE FROM clients WHERE id=$1',[other.id]);});

test('concurrent posts serialize sequence allocation and do not touch legacy CVR',async()=>{const before=Number((await pool.query(`SELECT count(*) n FROM cvr_periods`)).rows[0].n);const [a,b]=await Promise.all([post('addition',`con-a-${randomUUID()}`,[{costCodeId:f.cc1.id,amount:'0.01'}]),post('addition',`con-b-${randomUUID()}`,[{costCodeId:f.cc2.id,amount:'0.01'}])]);assert.equal(a.ok,true);assert.equal(b.ok,true);assert.notEqual(a.event.sequenceNumber,b.event.sequenceNumber);assert.equal(Number((await pool.query(`SELECT count(*) n FROM cvr_periods`)).rows[0].n),before);});

test('purpose-built API and service enforce permission rather than a role name',async()=>{const app=createApp({testPrincipal:f.auth});const read=await request(app).get(`/api/developments/${f.dev}/budget-authority`);assert.equal(read.status,200);assert.equal(read.body.exists,true);assert.equal(read.body.canonicalHashScheme,'canonical_json_sha256_v1');assert.match(read.body.events[0].effectiveDate,/^\d{4}-\d{2}-\d{2}$/);const posted=await request(app).post(`/api/developments/${f.dev}/budget-authority/events`).send({eventType:'correction',effectiveDate:'2026-09-09',reference:'API-1',reason:'API correction',idempotencyKey:`api-${randomUUID()}`,lines:[{costCodeId:f.cc1.id,amount:'0.01'}]});assert.equal(posted.status,201);const customAuth={clientId:f.client.id,userId:f.customUser.id,membershipId:f.customMembership.id,providerUserId:f.customUser.provider_user_id,displayName:f.customUser.display_name,roleKey:f.customRole.key,permissions:[PERMISSIONS.COMMERCIAL_READ,PERMISSIONS.DEVELOPMENT_BUDGET_POST]};const custom=await repo.postEvent(f.client.id,f.dev,{eventType:'correction',effectiveDate:'2026-09-09',reference:'CUSTOM-ROLE',reason:'Permission based',idempotencyKey:`custom-${randomUUID()}`,lines:[{costCodeId:f.cc1.id,amount:'0.01'}]},customAuth);assert.equal(custom.status,201);assert.equal(custom.event.createdBy.roleKey,f.customRole.key);const forbidden=createApp({testPrincipal:{...f.auth,permissions:[PERMISSIONS.COMMERCIAL_READ]}});assert.equal((await request(forbidden).post(`/api/developments/${f.dev}/budget-authority/events`).send({})).status,403);});
}
