const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {pool}=require('../db');
const {assertActiveTestDatabase}=require('../utils/testDatabaseGuard');

const OLD_OPERATIONS=['bootstrap_admin_established','invitation_created','invitation_accepted','membership_activated','primary_role_changed','capability_granted','capability_revoked','membership_deactivated','membership_reactivated'];
const migration=fs.readFileSync(path.join(__dirname,'..','migrations','064_membership_invitation_cancellation_audit.sql'),'utf8');

test('Migration 064 preserves the 063 vocabulary and immutable rows while adding cancellation only',async()=>{await assertActiveTestDatabase(pool);const c=await pool.connect(),oldSql=OLD_OPERATIONS.map(value=>`'${value}'`).join(',');try{await c.query('BEGIN');await c.query('SET LOCAL search_path=pg_temp,public');await c.query(`CREATE TEMP TABLE tenant_membership_authority_audit(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),operation TEXT NOT NULL CONSTRAINT tenant_membership_authority_audit_operation_check CHECK(operation IN(${oldSql})))`);await c.query(`CREATE TRIGGER trg_tenant_membership_authority_audit_immutable BEFORE UPDATE OR DELETE ON tenant_membership_authority_audit FOR EACH ROW EXECUTE FUNCTION protect_tenant_membership_authority_audit()`);for(const operation of OLD_OPERATIONS)await c.query('INSERT INTO tenant_membership_authority_audit(operation) VALUES($1)',[operation]);const before=(await c.query('SELECT id,operation FROM tenant_membership_authority_audit ORDER BY operation')).rows;await c.query(migration);assert.deepEqual((await c.query('SELECT id,operation FROM tenant_membership_authority_audit ORDER BY operation')).rows,before);for(const operation of OLD_OPERATIONS)assert.equal((await c.query('INSERT INTO tenant_membership_authority_audit(operation) VALUES($1) RETURNING operation',[operation])).rows[0].operation,operation);assert.equal((await c.query("INSERT INTO tenant_membership_authority_audit(operation) VALUES('invitation_cancelled') RETURNING operation")).rows[0].operation,'invitation_cancelled');await c.query('SAVEPOINT unknown_operation');await assert.rejects(c.query("INSERT INTO tenant_membership_authority_audit(operation) VALUES('invitation_reissued')"),/check constraint/i);await c.query('ROLLBACK TO SAVEPOINT unknown_operation');await c.query('SAVEPOINT immutable_update');await assert.rejects(c.query('UPDATE tenant_membership_authority_audit SET operation=operation WHERE id=$1',[before[0].id]),/append-only/i);await c.query('ROLLBACK TO SAVEPOINT immutable_update');await c.query('SAVEPOINT immutable_delete');await assert.rejects(c.query('DELETE FROM tenant_membership_authority_audit WHERE id=$1',[before[0].id]),/append-only/i);await c.query('ROLLBACK TO SAVEPOINT immutable_delete');}finally{await c.query('ROLLBACK');c.release();await pool.end();}});
