const test=require('node:test');const assert=require('node:assert/strict');
const {validatePaymentRulesV2,noticeReadiness}=require('../services/paymentRulesV2');
const {calculatePaymentDeadlines}=require('../services/paymentRulesV1');
const base={configurationState:'complete',ruleType:'uk_subcontract_payment_cycle',jurisdiction:'england_wales',timezone:'Europe/London',anchor:{type:'contractual_valuation_date'},dueDate:{relativeTo:'anchor',direction:'after',days:7,dayBasis:'calendar'},paymentNoticeDeadline:{relativeTo:'due_date',direction:'after',days:5,dayBasis:'calendar'},finalDateForPayment:{relativeTo:'due_date',direction:'after',days:28,dayBasis:'calendar'},payLessNoticeDeadline:{relativeTo:'final_date_for_payment',direction:'before',days:7,dayBasis:'calendar'}};
const notice=mode=>({paymentNoticeMode:mode,paymentNoticeIssuer:'company',certificateDocumentConstitutesNotice:mode==='certificate_as_payment_notice',basisOfCalculationRequired:true,paymentNoticeDocumentIdentity:mode==='certificate_only'?'payment_certificate':mode==='certificate_as_payment_notice'?'combined_certificate_payment_notice':'payment_notice',payLessIssuer:'company',payLessWorkflowSupported:true});

test('Payment Rules V1 remains timetable-capable but notice-unconfigured',()=>{assert.equal(noticeReadiness({rulesSchemaVersion:1,paymentRules:base}).state,'configuration_unavailable');assert.equal(calculatePaymentDeadlines({rulesSnapshot:{rulesSchemaVersion:1,paymentRules:base},cycleInputs:{contractualValuationDate:'2026-09-01'}}).dates.dueDate,'2026-09-08');});
for(const mode of ['certificate_only','certificate_as_payment_notice','separate_payment_notice'])test(`V2 validates ${mode}`,()=>{const rules={...base,notice:notice(mode)};assert.deepEqual(validatePaymentRulesV2(rules,2),{valid:true,complete:true,errors:[],code:null});assert.equal(noticeReadiness({rulesSchemaVersion:2,paymentRules:rules}).mode,mode);});
test('V2 does not silently default notice mode or inconsistent document identity',()=>{assert.equal(validatePaymentRulesV2({...base,notice:{...notice('separate_payment_notice'),paymentNoticeMode:null}},2).valid,false);assert.equal(validatePaymentRulesV2({...base,notice:{...notice('certificate_as_payment_notice'),certificateDocumentConstitutesNotice:false}},2).valid,false);});
test('V2 preserves deterministic V1 dates in BST and GMT',()=>{for(const anchor of ['2026-09-01','2026-12-01']){const result=calculatePaymentDeadlines({rulesSnapshot:{rulesSchemaVersion:2,paymentRules:{...base,notice:notice('separate_payment_notice')}},cycleInputs:{contractualValuationDate:anchor}});assert.equal(result.readiness,'ready');assert.equal(result.resolvedAnchor.value,anchor);}});
test('incomplete V2 Draft may omit notice configuration but cannot be complete',()=>{const value=validatePaymentRulesV2({configurationState:'incomplete'},2);assert.equal(value.valid,true);assert.equal(value.complete,false);});
