const test=require('node:test'); const assert=require('node:assert/strict');
const {buildPaymentCertificateSourceAuthority,legacySourceAuthority}=require('../services/paymentCertificateSourceAuthority');
const po=(number,value)=>({poNumber:number,subtotal:value,status:'approved',approval:{status:'approved'}});
const base=(overrides={})=>buildPaymentCertificateSourceAuthority({certificateId:'cert',matrixGross:0,approvedPos:[po('PO-1',1000)],...overrides});

test('ordinary ordered work is reconciled inside approved PO authority',()=>{const result=base({matrixGross:600});assert.equal(result.orderedWorkBackedGross,600);assert.equal(result.unapprovedCertifiedGross,0);});
test('multiple approved POs combine once and historic positive certification consumes authority',()=>{const result=base({matrixGross:500,approvedPos:[po('A',600),po('B',400)],priorLockedCertificates:[{matrixGross:700}]});assert.equal(result.approvedPoAuthority,1000);assert.equal(result.remainingApprovedPoAuthorityBeforeCertificate,300);assert.equal(result.orderedWorkExcessGross,200);assert.equal(result.unapprovedCertifiedGross,200);});
test('payment-discovered positive is scrutiny exposure and signed credit cannot hide it',()=>{const result=base({paymentDiscoveredItems:[{id:'a',signedAmount:250},{id:'b',signedAmount:-100}],commercialLines:[{lineType:'recoveryDeduction',amountThisCertificate:-50}]});assert.equal(result.paymentDiscoveredGross,150);assert.equal(result.unapprovedCertifiedGross,250);assert.equal(result.signedUnapprovedCredits,-100);assert.equal(result.recoverySigned,-50);});
test('approved CE and Issued VO authority remain separately evidenced without double counting',()=>{const lines=[{id:'ce',sourceType:'commercialEvent',amountThisCertificate:100},{id:'vo',sourceType:'variationOrder',amountThisCertificate:80,variationOrderId:'v',variationOrderLineId:'vl'}];const result=base({commercialLines:lines});assert.equal(result.approvedCeGross,100);assert.equal(result.issuedVoGross,80);assert.equal(result.unapprovedCertifiedGross,0);});
test('invalid positive inclusion is exposed while invalid credit stays separate',()=>{const lines=[{id:'bad+',amountThisCertificate:40},{id:'bad-',amountThisCertificate:-20}];const result=base({commercialLines:lines,validatedCommercialLines:new Set()});assert.equal(result.unapprovedCertifiedGross,40);assert.equal(result.signedUnapprovedCredits,-20);});
test('historic credits do not restore consumed ordered authority',()=>{const result=base({matrixGross:200,priorLockedCertificates:[{matrixGross:900},{matrixGross:-500}]});assert.equal(result.remainingApprovedPoAuthorityBeforeCertificate,100);assert.equal(result.unapprovedCertifiedGross,100);});
test('legacy locked certificate is explicitly unavailable rather than fake zero',()=>{assert.deepEqual(legacySourceAuthority().state,'not_captured');assert.equal(legacySourceAuthority().unapprovedCertifiedGross,undefined);});
test('payment-discovered evidence freezes authenticated provenance and identity',()=>{const result=base({paymentDiscoveredItems:[{id:'item-1',signedAmount:25,description:'On account',basis:'QS assessment',costCode:'4330',status:'draft',createdBy:{userId:'u',membershipId:'m',providerUserId:'p',displayName:'QS'}}]});assert.equal(result.evidence.paymentDiscoveredItems[0].id,'item-1');assert.equal(result.evidence.paymentDiscoveredItems[0].createdBy.providerUserId,'p');});
test('later CE or VO regularisation cannot rewrite the frozen payment-discovered classification',()=>{const item={id:'item-1',signedAmount:25,description:'On account',basis:'QS assessment',status:'locked'};const frozen=structuredClone(base({paymentDiscoveredItems:[item]}));item.regularisationLinks=[{authorityType:'commercial_event',commercialEventId:'ce-1'}];assert.equal(frozen.unapprovedCertifiedGross,25);assert.equal(frozen.evidence.paymentDiscoveredItems[0].id,'item-1');assert.equal(frozen.evidence.paymentDiscoveredItems[0].regularisationLinks,undefined);});
test('VA assessment is exposed once as canonical unapproved authority',()=>{const result=base({variationAssessments:[{id:'assessment-1',variationAccountItemId:'va-1',variationReference:'VA-0001',description:'Drainage design changes',currentAssessment:8000,previousCertified:0,cumulativeCertified:8000,basis:'QS assessment'}]});assert.equal(result.variationAssessmentGross,8000);assert.equal(result.unapprovedCertifiedGross,8000);assert.equal(result.paymentDiscoveredGross,0);assert.equal(result.evidence.variationAssessments.length,1);assert.equal(result.evidence.variationAssessments[0].variationReference,'VA-0001');});
