const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const path=require('path');
const {randomUUID}=require('crypto');
const {pool,isDbConfigured}=require('../db');
const {prepareIntegrationTestDatabase}=require('./integrationTestSetup');
const repo=require('../services/subcontractTermsRepository');
const migration=fs.readFileSync(path.join(__dirname,'..','migrations','027_subcontract_terms_foundation.sql'),'utf8');
const clients=[];
const completeRules=()=>({configurationState:'complete',ruleType:'uk_subcontract_payment_cycle',jurisdiction:'england_wales',timezone:'Europe/London',anchor:{type:'certificate_date'},dueDate:{relativeTo:'anchor',direction:'after',days:7,dayBasis:'calendar'},paymentNoticeDeadline:{relativeTo:'due_date',direction:'after',days:5,dayBasis:'calendar'},finalDateForPayment:{relativeTo:'due_date',direction:'after',days:28,dayBasis:'calendar'},payLessNoticeDeadline:{relativeTo:'final_date_for_payment',direction:'before',days:7,dayBasis:'calendar'}});
const familyBody=name=>({name,paymentRules:completeRules(),rulesSchemaVersion:1});
async function seed(label){
  const client=(await pool.query(`INSERT INTO clients(code,name,is_active) VALUES($1,$2,false) RETURNING *`,[`TERMS_${label}_${randomUUID().slice(0,6)}`,`Terms ${label}`])).rows[0];clients.push(client.id);
  const development=`dev-terms-${randomUUID()}`;await pool.query(`INSERT INTO developments(id,client_id,job_number,development_name,status,payload) VALUES($1,$2,$3,$4,'live','{}')`,[development,client.id,`T-${randomUUID().slice(0,6)}`,`Terms ${label}`]);
  const po=`TPO-${randomUUID()}`;await pool.query(`INSERT INTO purchase_orders(po_number,client_id,payload) VALUES($1,$2,$3)`,[po,client.id,JSON.stringify({poNumber:po,status:'Draft',developmentId:development,type:'SUBCONTRACT'})]);
  return {client,development,po};
}
test.before(async()=>{if(!isDbConfigured())return;await prepareIntegrationTestDatabase(pool);for(const name of ['004_developments.sql','005_packages.sql'])await pool.query(fs.readFileSync(path.join(__dirname,'..','migrations',name),'utf8'));await pool.query(migration);});
test.after(async()=>{if(!isDbConfigured()||!clients.length)return;await pool.query(`DELETE FROM purchase_order_terms_bindings WHERE client_id=ANY($1::uuid[])`,[clients]);await pool.query(`DELETE FROM purchase_order_terms_overrides WHERE client_id=ANY($1::uuid[])`,[clients]);await pool.query(`DELETE FROM packages WHERE client_id=ANY($1::uuid[])`,[clients]);await pool.query(`DELETE FROM purchase_orders WHERE client_id=ANY($1::uuid[])`,[clients]);await pool.query(`DELETE FROM developments WHERE client_id=ANY($1::uuid[])`,[clients]);await pool.query(`DELETE FROM clients WHERE id=ANY($1::uuid[])`,[clients]);});
test('migration is additive and contains lifecycle/immutability guards',()=>{assert.match(migration,/CREATE TABLE IF NOT EXISTS subcontract_terms_families/);assert.match(migration,/uq_subcontract_terms_one_draft/);assert.match(migration,/Published subcontract terms are immutable/);assert.doesNotMatch(migration,/\bUPDATE\s+purchase_orders\b/i);});
test('Draft publishes immutably, list exposes tenant default, clones next revision and isolates tenants',async t=>{if(!isDbConfigured())return t.skip();const a=await seed('A'),b=await seed('B');const created=await repo.createFamily(a.client.id,familyBody('Standard'));assert.equal(created.version.status,'draft');assert.equal((await repo.setTenantDefault(a.client.id,created.version.id)).status,400);const pub=await repo.publish(a.client.id,created.version.id);assert.equal(pub.version.status,'published');await repo.setTenantDefault(a.client.id,pub.version.id);const read=await repo.list(a.client.id);assert.equal(read.defaultVersionId,pub.version.id);assert.equal(read.families[0].versions.find(v=>v.id===pub.version.id).isCompanyDefault,true);const isolated=await repo.list(b.client.id);assert.equal(isolated.defaultVersionId,null);assert.equal(isolated.families.some(f=>f.versions.some(v=>v.id===pub.version.id)),false);assert.equal((await repo.updateDraft(a.client.id,pub.version.id,{recordVersion:1,paymentRules:{x:1}})).status,409);assert.equal(await repo.mapVersion(b.client.id,pub.version.id),null);const cloned=await repo.cloneVersion(a.client.id,pub.version.id);assert.equal(cloned.version.revisionNumber,2);assert.equal((await repo.cloneVersion(a.client.id,pub.version.id)).status,409);});

test('complete V1 rules are validated centrally before save/publish',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('V');const draft=await repo.createFamily(s.client.id,{name:'Validation'});const invalid={configurationState:'complete',ruleType:'uk_subcontract_payment_cycle',jurisdiction:'england_wales',timezone:'Europe/London'};assert.equal((await repo.updateDraft(s.client.id,draft.version.id,{recordVersion:1,rulesSchemaVersion:1,paymentRules:invalid})).status,400);const schema={configurationState:'complete',ruleType:'uk_subcontract_payment_cycle',jurisdiction:'england_wales',timezone:'Europe/London',anchor:{type:'certificate_date'},dueDate:{relativeTo:'anchor',direction:'after',days:0,dayBasis:'calendar'},paymentNoticeDeadline:{relativeTo:'anchor',direction:'after',days:0,dayBasis:'calendar'},finalDateForPayment:{relativeTo:'due_date',direction:'after',days:0,dayBasis:'calendar'},payLessNoticeDeadline:{relativeTo:'final_date_for_payment',direction:'before',days:0,dayBasis:'calendar'}};const saved=await repo.updateDraft(s.client.id,draft.version.id,{recordVersion:1,rulesSchemaVersion:1,paymentRules:schema});assert.equal(saved.ok,true);assert.equal((await repo.publish(s.client.id,draft.version.id)).ok,true);});

test('Incomplete Drafts save blank, partial and exact UAT rules while malformed values reject',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('I');const draft=await repo.createFamily(s.client.id,{name:'Incomplete saves'});assert.equal((await repo.updateDraft(s.client.id,draft.version.id,{recordVersion:1,rulesSchemaVersion:1,paymentRules:{configurationState:'incomplete'}})).ok,true);const partial={configurationState:'incomplete',ruleType:'uk_subcontract_payment_cycle',jurisdiction:'england_wales',timezone:'Europe/London',anchor:{type:'contractual_valuation_date'},dueDate:{relativeTo:'anchor',direction:'after',days:7,dayBasis:'calendar'}};assert.equal((await repo.updateDraft(s.client.id,draft.version.id,{recordVersion:2,rulesSchemaVersion:1,paymentRules:partial})).ok,true);const exact={...completeRules(),configurationState:'incomplete',anchor:{type:'contractual_valuation_date'}};const saved=await repo.updateDraft(s.client.id,draft.version.id,{recordVersion:3,rulesSchemaVersion:1,paymentRules:exact});assert.equal(saved.ok,true);assert.deepEqual(saved.version.paymentRules,exact);assert.equal((await repo.publish(s.client.id,draft.version.id)).status,400);const malformed={...exact,dueDate:{...exact.dueDate,days:-1}};assert.equal((await repo.updateDraft(s.client.id,draft.version.id,{recordVersion:4,rulesSchemaVersion:1,paymentRules:malformed})).status,400);});

test('publish rejects Incomplete and legacy Complete-invalid rules without changing Draft status',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('PUB');const incomplete=await repo.createFamily(s.client.id,{name:'Publish guards'});let result=await repo.publish(s.client.id,incomplete.version.id);assert.equal(result.status,400);assert.match(result.message,/Complete and valid/);assert.equal((await repo.mapVersion(s.client.id,incomplete.version.id)).status,'draft');await pool.query(`UPDATE subcontract_terms_versions SET payment_rules=$3 WHERE client_id=$1 AND id=$2`,[s.client.id,incomplete.version.id,JSON.stringify({configurationState:'complete',ruleType:'uk_subcontract_payment_cycle'})]);result=await repo.publish(s.client.id,incomplete.version.id);assert.equal(result.status,400);assert.equal((await repo.mapVersion(s.client.id,incomplete.version.id)).status,'draft');});
test('order > development > tenant precedence and approval binding is immutable',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('P');const versions=[];for(const name of ['Tenant','Development','Order']){const v=await repo.createFamily(s.client.id,familyBody(name));versions.push((await repo.publish(s.client.id,v.version.id)).version);}await repo.setTenantDefault(s.client.id,versions[0].id);assert.equal((await repo.resolveForPo(s.client.id,s.po)).source,'tenant_default');await repo.setDevelopmentDefault(s.client.id,s.development,versions[1].id);assert.equal((await repo.resolveForPo(s.client.id,s.po)).source,'development_default');assert.equal((await repo.setPoOverride(s.client.id,s.po,versions[2].id,'')).status,400);await repo.setPoOverride(s.client.id,s.po,versions[2].id,'Bespoke amendment');const proposed=await repo.resolveForPo(s.client.id,s.po);assert.equal(proposed.source,'order_override');const db=await pool.connect();try{await db.query('BEGIN');await db.query(`UPDATE purchase_orders SET payload=jsonb_set(payload,'{status}','\"Approved\"') WHERE po_number=$1`,[s.po]);await repo.bindOnApproval(s.client.id,s.po,{dbClient:db,actor:'QS',resolvedTerms:proposed});await db.query('COMMIT');}finally{db.release();}await repo.setTenantDefault(s.client.id,versions[1].id);const bound=await repo.resolveForPo(s.client.id,s.po);assert.equal(bound.state,'bound');assert.equal(bound.version.id,versions[2].id);assert.equal((await repo.setPoOverride(s.client.id,s.po,versions[0].id,'late')).status,409);});
test('package reports common, mixed and unconfigured without fabricating rules',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('M');const second=`TPO-${randomUUID()}`;await pool.query(`INSERT INTO purchase_orders(po_number,client_id,payload) VALUES($1,$2,$3)`,[second,s.client.id,JSON.stringify({poNumber:second,status:'Draft',developmentId:s.development})]);const pkg=(await pool.query(`INSERT INTO packages(client_id,development_id,supplier_id,cost_code,order_key) VALUES($1,$2,'supplier','1',$3) RETURNING *`,[s.client.id,s.development,`subcontract:${randomUUID()}`])).rows[0];for(const po of [s.po,second])await pool.query(`INSERT INTO package_purchase_orders(package_id,client_id,po_number) VALUES($1,$2,$3)`,[pkg.id,s.client.id,po]);let value=await repo.resolveForPackage(s.client.id,pkg.id);assert.equal(value.state,'unconfigured');assert.equal((await repo.snapshotForPackage(s.client.id,pkg.id)).paymentRules,null);const rules=completeRules();const f=await repo.createFamily(s.client.id,{name:'Common',paymentRules:rules}),v=(await repo.publish(s.client.id,f.version.id)).version;await repo.setTenantDefault(s.client.id,v.id);value=await repo.resolveForPackage(s.client.id,pkg.id);assert.equal(value.state,'common');assert.deepEqual((await repo.snapshotForPackage(s.client.id,pkg.id)).paymentRules,rules);const other=await repo.createFamily(s.client.id,familyBody('Other')),otherV=(await repo.publish(s.client.id,other.version.id)).version;await repo.setPoOverride(s.client.id,second,otherV.id,'Different subcontract');assert.equal((await repo.resolveForPackage(s.client.id,pkg.id)).state,'mixed');});

test('certificate snapshot captures exact configured rules without calculating legal dates',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('S');const pkg=(await pool.query(`INSERT INTO packages(client_id,development_id,supplier_id,cost_code,order_key) VALUES($1,$2,'supplier','2',$3) RETURNING *`,[s.client.id,s.development,`subcontract:${randomUUID()}`])).rows[0];await pool.query(`INSERT INTO package_purchase_orders(package_id,client_id,po_number) VALUES($1,$2,$3)`,[pkg.id,s.client.id,s.po]);const rules=completeRules();const f=await repo.createFamily(s.client.id,{name:'Snapshot',paymentRules:rules}),v=(await repo.publish(s.client.id,f.version.id)).version;await repo.setTenantDefault(s.client.id,v.id);const {buildApplicationSnapshot}=require('../services/paymentCertificateRepository');const payload=await buildApplicationSnapshot(null,s.client.id,pkg.id,{id:randomUUID()},{grossWorksThisCertificate:1000},{progress:{}},'submission');assert.equal(payload.submissionGoverningTermsSnapshot.termsVersionId,v.id);assert.deepEqual(payload.submissionGoverningTermsSnapshot.paymentRules,rules);assert.equal('dueDate' in payload.submissionGoverningTermsSnapshot,false);});

test('legacy confirmation is prospective, retirement preserves history, and rollback leaves no binding',async t=>{if(!isDbConfigured())return t.skip();const s=await seed('L');const f=await repo.createFamily(s.client.id,familyBody('Legacy confirmation')),v=(await repo.publish(s.client.id,f.version.id)).version;await pool.query(`UPDATE purchase_orders SET payload=jsonb_set(payload,'{status}','\"Approved\"') WHERE po_number=$1`,[s.po]);assert.equal((await repo.resolveForPo(s.client.id,s.po)).state,'legacy');assert.equal((await repo.confirmLegacy(s.client.id,s.po,v.id,'Confirmed for future payment cycles')).terms.legacyProspective,true);const other=await seed('R');const draftTerms=await repo.createFamily(other.client.id,familyBody('Rollback')),published=(await repo.publish(other.client.id,draftTerms.version.id)).version;await repo.setTenantDefault(other.client.id,published.id);const proposed=await repo.resolveForPo(other.client.id,other.po);const db=await pool.connect();try{await db.query('BEGIN');await repo.bindOnApproval(other.client.id,other.po,{dbClient:db,resolvedTerms:proposed});await db.query('ROLLBACK');}finally{db.release();}assert.equal((await pool.query(`SELECT count(*)::int n FROM purchase_order_terms_bindings WHERE client_id=$1 AND po_number=$2`,[other.client.id,other.po])).rows[0].n,0);const replacement=await repo.createFamily(other.client.id,familyBody('Replacement')),replacementV=(await repo.publish(other.client.id,replacement.version.id)).version;await repo.setTenantDefault(other.client.id,replacementV.id);const retired=await repo.retire(other.client.id,published.id);assert.equal(retired.version.status,'retired');assert.equal((await repo.setTenantDefault(other.client.id,published.id)).status,400);assert.equal((await repo.mapVersion(other.client.id,published.id)).status,'retired');});
