const { pool, query } = require('../db');
const { assertServicePermission } = require('../auth/authorization');
const { PERMISSIONS } = require('../auth/permissions');

const TYPES = Object.freeze({
  head: { table:'commercial_structure_heads', parent: null },
  family: { table:'commercial_structure_families', parent:'head' },
  reporting_group: { table:'commercial_structure_reporting_groups', parent:'head' },
});
const clean = value => String(value || '').trim();
const fail = (status,message) => ({ok:false,status,message});
const actor = auth => [auth.userId,auth.membershipId,auth.providerUserId,auth.displayName];
function mapped(row){return row&&{id:row.id,name:row.name,headId:row.head_id||null,familyId:row.family_id||null,displayOrder:Number(row.display_order),active:row.is_active,version:Number(row.version),origin:row.origin,createdAt:row.created_at,updatedAt:row.updated_at};}
async function audit(db,clientId,type,id,operation,before,after,auth){await db.query(`INSERT INTO commercial_structure_audit(client_id,entity_type,entity_id,operation,before_document,after_document,resulting_version,actor_user_id,actor_membership_id,actor_provider_user_id,actor_display_name,actor_role_key,actor_permission_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[clientId,type,id,operation,before?JSON.stringify(before):null,JSON.stringify(after),after.version,...actor(auth),auth.roleKey,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE]);}
async function listStructure(clientId,db=null){const run=db?.query?db.query.bind(db):query;const [heads,families,groups,issues]=await Promise.all([
  run('SELECT * FROM commercial_structure_heads WHERE client_id=$1 ORDER BY display_order,name',[clientId]),run('SELECT * FROM commercial_structure_families WHERE client_id=$1 ORDER BY display_order,name',[clientId]),run('SELECT * FROM commercial_structure_reporting_groups WHERE client_id=$1 ORDER BY display_order,name',[clientId]),run('SELECT cost_code_id,reason,evidence,detected_at FROM commercial_structure_adoption_issues WHERE client_id=$1 ORDER BY detected_at,cost_code_id',[clientId])]);
 return {heads:heads.rows.map(mapped),families:families.rows.map(mapped),reportingGroups:groups.rows.map(mapped),adoptionIssues:issues.rows.map(x=>({costCodeId:x.cost_code_id,reason:x.reason,evidence:x.evidence,detectedAt:x.detected_at}))};}
async function validateParents(db,clientId,type,body){if(type==='head')return true;const head=(await db.query('SELECT id FROM commercial_structure_heads WHERE client_id=$1 AND id=$2',[clientId,body.headId])).rows[0];if(!head)return false;if(type==='reporting_group'&&body.familyId){const family=(await db.query('SELECT id FROM commercial_structure_families WHERE client_id=$1 AND id=$2 AND head_id=$3',[clientId,body.familyId,body.headId])).rows[0];if(!family)return false;}return true;}
async function createNode(clientId,type,body,auth){assertServicePermission(auth,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE);if(String(auth.clientId)!==String(clientId))throw Object.assign(new Error('Tenant boundary violation.'),{status:403});const spec=TYPES[type];if(!spec)return fail(400,'Unknown Commercial Structure entity type.');const name=clean(body.name);if(!name||name.length>120)return fail(400,'A name of 120 characters or fewer is required.');const db=await pool.connect();try{await db.query('BEGIN');if(!await validateParents(db,clientId,type,body)){await db.query('ROLLBACK');return fail(400,'The selected hierarchy parent is invalid.');}const columns=['client_id','name','display_order','created_by_user_id','created_by_membership_id','created_by_provider_user_id','created_by_display_name'];const values=[clientId,name,Number.isInteger(Number(body.displayOrder))?Number(body.displayOrder):0,...actor(auth)];if(type!=='head'){columns.push('head_id');values.push(body.headId);}if(type==='reporting_group'){columns.push('family_id');values.push(body.familyId||null);}const params=values.map((_,i)=>`$${i+1}`).join(',');const row=(await db.query(`INSERT INTO ${spec.table}(${columns.join(',')}) VALUES(${params}) RETURNING *`,values)).rows[0];const result=mapped(row);await audit(db,clientId,type,row.id,'create',null,result,auth);await db.query('COMMIT');return {ok:true,status:201,node:result};}catch(error){await db.query('ROLLBACK');if(error.code==='23505')return fail(409,'A hierarchy item with this name already exists in that location.');throw error;}finally{db.release();}}
async function updateNode(clientId,type,id,body,auth){assertServicePermission(auth,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE);if(String(auth.clientId)!==String(clientId))throw Object.assign(new Error('Tenant boundary violation.'),{status:403});const spec=TYPES[type];if(!spec)return fail(400,'Unknown Commercial Structure entity type.');const version=Number(body.version),name=clean(body.name);if(!Number.isInteger(version)||version<1||!name||name.length>120)return fail(400,'Valid version and name are required.');const db=await pool.connect();try{await db.query('BEGIN');const beforeRow=(await db.query(`SELECT * FROM ${spec.table} WHERE client_id=$1 AND id=$2 FOR UPDATE`,[clientId,id])).rows[0];if(!beforeRow){await db.query('ROLLBACK');return fail(404,'Commercial Structure item not found.');}if(Number(beforeRow.version)!==version){await db.query('ROLLBACK');return fail(409,'Commercial Structure item has changed. Reload and try again.');}const next={...body,headId:body.headId??beforeRow.head_id,familyId:body.familyId===undefined?beforeRow.family_id:body.familyId};if(!await validateParents(db,clientId,type,next)){await db.query('ROLLBACK');return fail(400,'The selected hierarchy parent is invalid.');}const active=body.active===undefined?beforeRow.is_active:Boolean(body.active);const row=(await db.query(`UPDATE ${spec.table} SET name=$1,display_order=$2,is_active=$3,version=version+1,updated_at=NOW() WHERE client_id=$4 AND id=$5 RETURNING *`,[name,Number.isInteger(Number(body.displayOrder))?Number(body.displayOrder):beforeRow.display_order,active,clientId,id])).rows[0];const result=mapped(row),before=mapped(beforeRow);await audit(db,clientId,type,id,active===before.active?'update':active?'restore':'archive',before,result,auth);await db.query('COMMIT');return {ok:true,status:200,node:result};}catch(error){await db.query('ROLLBACK');if(error.code==='23505')return fail(409,'A hierarchy item with this name already exists in that location.');throw error;}finally{db.release();}}
async function reorderSiblings(clientId,type,body,auth){assertServicePermission(auth,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE);if(String(auth.clientId)!==String(clientId))throw Object.assign(new Error('Tenant boundary violation.'),{status:403});const spec=TYPES[type];if(!spec)return fail(400,'Unknown Commercial Structure entity type.');const items=Array.isArray(body.items)?body.items:[];if(!items.length||items.some(x=>!x.id||!Number.isInteger(Number(x.version))))return fail(400,'A valid ordered sibling list is required.');const db=await pool.connect();try{await db.query('BEGIN');const ids=items.map(x=>x.id);const rows=(await db.query(`SELECT * FROM ${spec.table} WHERE client_id=$1 AND id=ANY($2::uuid[]) FOR UPDATE`,[clientId,ids])).rows;if(rows.length!==items.length){await db.query('ROLLBACK');return fail(404,'Commercial Structure item not found.');}const parent=x=>`${x.head_id||''}:${x.family_id||''}`;if(new Set(rows.map(parent)).size!==1){await db.query('ROLLBACK');return fail(400,'Only siblings can be reordered together.');}for(const [displayOrder,item] of items.entries()){const before=rows.find(x=>x.id===item.id);if(Number(before.version)!==Number(item.version)){await db.query('ROLLBACK');return fail(409,'Commercial Structure item has changed. Reload and try again.');}const row=(await db.query(`UPDATE ${spec.table} SET display_order=$1,version=version+1,updated_at=NOW() WHERE client_id=$2 AND id=$3 RETURNING *`,[displayOrder,clientId,item.id])).rows[0];await audit(db,clientId,type,item.id,'update',mapped(before),mapped(row),auth);}await db.query('COMMIT');return {ok:true,status:200,structure:await listStructure(clientId)};}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
module.exports={listStructure,createNode,updateNode,reorderSiblings};
