/**
 * BL-033B — BuildLite semantic classification keys.
 * These are engine taxonomy keys, not Commercial Head labels.
 * Unmapped codes resolve as UNCLASSIFIED + STANDARD_CVR without a row.
 */

const SEMANTIC_GROUPS = {
  UNCLASSIFIED: "UNCLASSIFIED",
  LAND: "LAND",
  FEES: "FEES",
  INFRASTRUCTURE: "INFRASTRUCTURE",
  BUILD: "BUILD",
  PRELIMS: "PRELIMS",
  SELLING: "SELLING",
  OTHER: "OTHER",
};

const PERSISTED_SEMANTIC_GROUPS = [
  SEMANTIC_GROUPS.LAND,
  SEMANTIC_GROUPS.FEES,
  SEMANTIC_GROUPS.INFRASTRUCTURE,
  SEMANTIC_GROUPS.BUILD,
  SEMANTIC_GROUPS.PRELIMS,
  SEMANTIC_GROUPS.SELLING,
  SEMANTIC_GROUPS.OTHER,
];

const FORECAST_DRIVERS = {
  STANDARD_CVR: "STANDARD_CVR",
  TIME: "TIME",
  LUMP_SUM: "LUMP_SUM",
  QUANTITY: "QUANTITY",
  MILESTONE: "MILESTONE",
  PERCENTAGE: "PERCENTAGE",
  MANUAL: "MANUAL",
};

const FORECAST_DRIVER_KEYS = Object.values(FORECAST_DRIVERS);

const DEFAULT_SEMANTIC_GROUP = SEMANTIC_GROUPS.UNCLASSIFIED;
const DEFAULT_FORECAST_DRIVER = FORECAST_DRIVERS.STANDARD_CVR;

const MAX_COST_CODE_KEY_LENGTH = 64;

module.exports = {
  SEMANTIC_GROUPS,
  PERSISTED_SEMANTIC_GROUPS,
  FORECAST_DRIVERS,
  FORECAST_DRIVER_KEYS,
  DEFAULT_SEMANTIC_GROUP,
  DEFAULT_FORECAST_DRIVER,
  MAX_COST_CODE_KEY_LENGTH,
};
