const crypto=require('crypto');
const {pool}=require('../db');
const {assertServicePermission}=require('../auth/authorization');
const {PERMISSIONS}=require('../auth/permissions');
const {validateCreateCostCodeBody,validateUpdateCostCodeBody}=require('./costCodeMasterValidation');

const STATES={MATCHED:'MATCHED',NEW:'NEW_STRUCTURE_REQUIRED',AMBIGUOUS:'AMBIGUOUS',UNALLOCATED:'UNALLOCATED',INVALID:'INVALID',ARCHIVED:'ARCHIVED_MATCH'};
const clean=value=>String(value??'').trim().replace(/\s+/g,' ');
const key=value=>clean(value).toLocaleLowerCase('en-GB');
const fail=(status,message)=>({ok:false,status,message,errors:[message]});
function reviewSecret(){const configured=process.env.COST_CODE_IMPORT_REVIEW_SECRET||process.env.CLERK_SECRET_KEY||process.env.DATABASE_URL;if(!configured)throw Object.assign(Error('Cost Code import review signing is unavailable.'),{status:503});return crypto.createHash('sha256').update(`buildlite-cost-code-import-review-v1\0${configured}`).digest();}
function reviewedEvidence(preview){return {catalogueRevision:preview.catalogueRevision,rows:preview.rows.map(row=>({rowNumber:row.rowNumber,code:row.code,description:row.description,isUpdate:row.isUpdate,costCodeId:row.costCodeId,costCodeVersion:row.costCodeVersion,resolution:row.resolution,fields:row.fields})),proposals:preview.proposals};}
function signReview(preview){return crypto.createHmac('sha256',reviewSecret()).update(JSON.stringify(reviewedEvidence(preview))).digest('hex');}
function reviewMatches(preview,token){if(typeof token!=='string'||token.length!==64)return false;const expected=Buffer.from(signReview(preview),'hex'),actual=Buffer.from(token,'hex');return actual.length===expected.length&&crypto.timingSafeEqual(actual,expected);}
function catalogueToken(structure){const compact=['heads','families','reportingGroups'].flatMap(type=>(structure[type]||[]).map(x=>[type,x.id,x.headId||'',x.familyId||'',x.name,x.active,x.version]));return crypto.createHash('sha256').update(JSON.stringify(compact)).digest('hex');}
async function load(db,clientId){const [h,f,g,c]=await Promise.all([
 db.query('SELECT id,name,is_active,version,display_order FROM commercial_structure_heads WHERE client_id=$1 ORDER BY id',[clientId]),
 db.query('SELECT id,head_id,name,is_active,version,display_order FROM commercial_structure_families WHERE client_id=$1 ORDER BY id',[clientId]),
 db.query('SELECT id,head_id,family_id,name,is_active,version,display_order FROM commercial_structure_reporting_groups WHERE client_id=$1 ORDER BY id',[clientId]),
 db.query('SELECT * FROM cost_codes WHERE client_id=$1 ORDER BY id',[clientId])]);
 return {heads:h.rows.map(x=>({id:x.id,name:x.name,active:x.is_active,version:Number(x.version)})),families:f.rows.map(x=>({id:x.id,headId:x.head_id,name:x.name,active:x.is_active,version:Number(x.version)})),reportingGroups:g.rows.map(x=>({id:x.id,headId:x.head_id,familyId:x.family_id||null,name:x.name,active:x.is_active,version:Number(x.version)})),costCodes:c.rows};}
function matches(rows,name,predicate=()=>true){return rows.filter(x=>key(x.name)===key(name)&&predicate(x));}
function resolvePath(structure,input){const head=clean(input.commercialHead),family=clean(input.commercialFamily),group=clean(input.reportingGroup||input.trade);
 if(!head&&!family&&!group)return {state:STATES.UNALLOCATED,path:{commercialHeadId:null,commercialFamilyId:null,reportingGroupId:null},labels:{commercialHead:'',commercialFamily:'',reportingGroup:''}};
 if(!head||!group)return {state:STATES.INVALID,reason:'Commercial Head and Reporting Group are both required for an allocated row.'};
 const heads=matches(structure.heads,head);if(heads.length>1)return {state:STATES.AMBIGUOUS,reason:'Commercial Head is ambiguous.'};
 const h=heads[0];if(h&&!h.active)return {state:STATES.ARCHIVED,reason:'Commercial Head is archived.'};
 if(!h)return {state:STATES.NEW,proposal:{commercialHead:head,commercialFamily:family,reportingGroup:group},labels:{commercialHead:head,commercialFamily:family,reportingGroup:group}};
 let f=null;if(family){const fs=matches(structure.families,family,x=>x.headId===h.id);if(fs.length>1)return {state:STATES.AMBIGUOUS,reason:'Commercial Family is ambiguous.'};f=fs[0];if(f&&!f.active)return {state:STATES.ARCHIVED,reason:'Commercial Family is archived.'};if(!f)return {state:STATES.NEW,proposal:{commercialHead:head,commercialFamily:family,reportingGroup:group},existing:{commercialHeadId:h.id,commercialHeadVersion:h.version},labels:{commercialHead:h.name,commercialFamily:family,reportingGroup:group}};}
 const groups=matches(structure.reportingGroups,group,x=>x.headId===h.id&&(x.familyId||null)===(f?.id||null));if(groups.length>1)return {state:STATES.AMBIGUOUS,reason:'Reporting Group is ambiguous.'};const g=groups[0];if(g&&!g.active)return {state:STATES.ARCHIVED,reason:'Reporting Group is archived.'};if(!g)return {state:STATES.NEW,proposal:{commercialHead:head,commercialFamily:family,reportingGroup:group},existing:{commercialHeadId:h.id,commercialHeadVersion:h.version,...(f?{commercialFamilyId:f.id,commercialFamilyVersion:f.version}:{})},labels:{commercialHead:h.name,commercialFamily:f?.name||'',reportingGroup:group}};
 return {state:STATES.MATCHED,path:{commercialHeadId:h.id,commercialFamilyId:f?.id||null,reportingGroupId:g.id},versions:{commercialHead:h.version,commercialFamily:f?.version||null,reportingGroup:g.version},labels:{commercialHead:h.name,commercialFamily:f?.name||'',reportingGroup:g.name}};}
function previewDocument(structure,rows=[]){const seen=new Set();const existing=new Map(structure.costCodes.map(x=>[key(x.code),x]));const resolved=(Array.isArray(rows)?rows:[]).map((raw,index)=>{const code=clean(raw.code),description=clean(raw.description);let resolution=resolvePath(structure,raw);if(!code||!description)resolution={state:STATES.INVALID,reason:'Cost Code and Description are required.'};else if(seen.has(key(code)))resolution={state:STATES.INVALID,reason:'Duplicate Cost Code in import.'};seen.add(key(code));const current=existing.get(key(code));return {rowNumber:raw.rowNumber||index+1,code,description,isUpdate:Boolean(current),costCodeId:current?.id||null,costCodeVersion:current?Number(current.version):null,resolution,fields:{defaultOrderType:raw.defaultOrderType||'S',defaultVatTreatment:raw.defaultVatTreatment||'Standard',reportingOrder:Number(raw.reportingOrder)||0,active:raw.active!==false}};});
 const proposals=[];for(const row of resolved.filter(x=>x.resolution.state===STATES.NEW)){const p=row.resolution.proposal,id=[key(p.commercialHead),key(p.commercialFamily),key(p.reportingGroup)].join('::');let item=proposals.find(x=>x.key===id);if(!item){item={key:id,...p,costCodes:[]};proposals.push(item);}item.costCodes.push(row.code);}return {catalogueRevision:catalogueToken(structure),rows:resolved,proposals,summary:{matched:resolved.filter(x=>x.resolution.state===STATES.MATCHED).length,newStructure:resolved.filter(x=>x.resolution.state===STATES.NEW).length,unallocated:resolved.filter(x=>x.resolution.state===STATES.UNALLOCATED).length,blocked:resolved.filter(x=>[STATES.INVALID,STATES.AMBIGUOUS,STATES.ARCHIVED].includes(x.resolution.state)).length}};}
async function preview(clientId,body,auth){assertServicePermission(auth,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE);if(String(auth.clientId)!==String(clientId))return fail(403,'Tenant boundary violation.');const db=await pool.connect();try{const document=previewDocument(await load(db,clientId),body.rows);document.reviewToken=signReview(document);return {ok:true,status:200,preview:document}}finally{db.release();}}
async function audit(db,clientId,type,row,auth){await db.query(`INSERT INTO commercial_structure_audit(client_id,entity_type,entity_id,operation,after_document,resulting_version,actor_user_id,actor_membership_id,actor_provider_user_id,actor_display_name,actor_role_key,actor_permission_key) VALUES($1,$2,$3,'create',$4,$5,$6,$7,$8,$9,$10,$11)`,[clientId,type,row.id,JSON.stringify({id:row.id,name:row.name,headId:row.head_id||null,familyId:row.family_id||null,displayOrder:Number(row.display_order),active:row.is_active,version:Number(row.version),origin:row.origin}),row.version,auth.userId,auth.membershipId,auth.providerUserId,auth.displayName,auth.roleKey,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE]);}
async function createPath(db,clientId,p,auth){let h=(await db.query('SELECT * FROM commercial_structure_heads WHERE client_id=$1 AND lower(btrim(name))=lower(btrim($2)) FOR UPDATE',[clientId,p.commercialHead])).rows[0];if(!h){h=(await db.query(`INSERT INTO commercial_structure_heads(client_id,name,display_order,origin,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,(SELECT count(*) FROM commercial_structure_heads WHERE client_id=$1),'cost_code_import',$3,$4,$5,$6) RETURNING *`,[clientId,p.commercialHead,auth.userId,auth.membershipId,auth.providerUserId,auth.displayName])).rows[0];await audit(db,clientId,'head',h,auth);}if(!h.is_active)throw Object.assign(Error('Reviewed Commercial Head is now archived.'),{status:409});
 let f=null;if(p.commercialFamily){f=(await db.query('SELECT * FROM commercial_structure_families WHERE client_id=$1 AND head_id=$2 AND lower(btrim(name))=lower(btrim($3)) FOR UPDATE',[clientId,h.id,p.commercialFamily])).rows[0];if(!f){f=(await db.query(`INSERT INTO commercial_structure_families(client_id,head_id,name,display_order,origin,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,$3,(SELECT count(*) FROM commercial_structure_families WHERE client_id=$1 AND head_id=$2),'cost_code_import',$4,$5,$6,$7) RETURNING *`,[clientId,h.id,p.commercialFamily,auth.userId,auth.membershipId,auth.providerUserId,auth.displayName])).rows[0];await audit(db,clientId,'family',f,auth);}if(!f.is_active)throw Object.assign(Error('Reviewed Commercial Family is now archived.'),{status:409});}
 let g=(await db.query('SELECT * FROM commercial_structure_reporting_groups WHERE client_id=$1 AND head_id=$2 AND family_id IS NOT DISTINCT FROM $3 AND lower(btrim(name))=lower(btrim($4)) FOR UPDATE',[clientId,h.id,f?.id||null,p.reportingGroup])).rows[0];if(!g){g=(await db.query(`INSERT INTO commercial_structure_reporting_groups(client_id,head_id,family_id,name,display_order,origin,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,$3,$4,(SELECT count(*) FROM commercial_structure_reporting_groups WHERE client_id=$1 AND head_id=$2 AND family_id IS NOT DISTINCT FROM $3),'cost_code_import',$5,$6,$7,$8) RETURNING *`,[clientId,h.id,f?.id||null,p.reportingGroup,auth.userId,auth.membershipId,auth.providerUserId,auth.displayName])).rows[0];await audit(db,clientId,'reporting_group',g,auth);}if(!g.is_active)throw Object.assign(Error('Reviewed Reporting Group is now archived.'),{status:409});return {h,f,g};}
async function apply(clientId,body,auth){assertServicePermission(auth,PERMISSIONS.COMMERCIAL_STRUCTURE_MANAGE);if(String(auth.clientId)!==String(clientId))return fail(403,'Tenant boundary violation.');const db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT id FROM commercial_structure_heads WHERE client_id=$1 FOR UPDATE',[clientId]);await db.query('SELECT id FROM commercial_structure_families WHERE client_id=$1 FOR UPDATE',[clientId]);await db.query('SELECT id FROM commercial_structure_reporting_groups WHERE client_id=$1 FOR UPDATE',[clientId]);await db.query('SELECT id FROM cost_codes WHERE client_id=$1 FOR UPDATE',[clientId]);const structure=await load(db,clientId);const current=previewDocument(structure,body.rows);if(!body.catalogueRevision||body.catalogueRevision!==current.catalogueRevision){await db.query('ROLLBACK');return fail(409,'Commercial Structure changed after review. Refresh and review the import again.');}if(!reviewMatches(current,body.reviewToken)){await db.query('ROLLBACK');return fail(409,'The Cost Code import differs from the reviewed preview. Preview and review it again.');}if(current.rows.some(x=>[STATES.INVALID,STATES.AMBIGUOUS,STATES.ARCHIVED].includes(x.resolution.state))){await db.query('ROLLBACK');return fail(400,'Import contains unresolved hierarchy rows.');}
 const expected=new Map((body.expectedCostCodes||[]).map(x=>[key(x.code),Number(x.version)]));for(const row of current.rows){const existing=structure.costCodes.find(x=>key(x.code)===key(row.code));if(existing&&expected.get(key(row.code))!==Number(existing.version)){await db.query('ROLLBACK');return fail(409,`Cost Code ${row.code} changed after review.`);}}
 const pathCache=new Map();for(const row of current.rows){let ids={h:null,f:null,g:null},labels={commercialHead:null,commercialFamily:null,reportingGroup:null};if(row.resolution.state===STATES.MATCHED){const p=row.resolution.path;ids={h:p.commercialHeadId,f:p.commercialFamilyId,g:p.reportingGroupId};labels=row.resolution.labels;}else if(row.resolution.state===STATES.NEW){const pk=row.resolution.proposal,cacheKey=[key(pk.commercialHead),key(pk.commercialFamily),key(pk.reportingGroup)].join('::');if(!pathCache.has(cacheKey))pathCache.set(cacheKey,await createPath(db,clientId,pk,auth));ids=pathCache.get(cacheKey);labels={commercialHead:ids.h.name,commercialFamily:ids.f?.name||null,reportingGroup:ids.g.name};}
 const existing=structure.costCodes.find(x=>key(x.code)===key(row.code)),fields=row.fields,meta={source:'cost_code_import',reviewed:true};const payload={code:row.code,description:row.description,commercialHead:labels.commercialHead,commercialFamily:labels.commercialFamily||'',reportingGroup:labels.reportingGroup,trade:labels.reportingGroup,hierarchyMode:ids.h?(ids.f?'three-level':'two-level'):null,commercialHeadId:ids.h?.id||ids.h,commercialFamilyId:ids.f?.id||ids.f,reportingGroupId:ids.g?.id||ids.g,defaultOrderType:fields.defaultOrderType,defaultVatTreatment:fields.defaultVatTreatment,reportingOrder:fields.reportingOrder,active:fields.active,importMetadata:meta,...(existing?{version:Number(existing.version)}:{})};const checked=existing?validateUpdateCostCodeBody(payload,existing):validateCreateCostCodeBody(payload);if(!checked.ok){await db.query('ROLLBACK');return fail(400,checked.errors.join(' '));}const value=checked.value;if(existing){const updated=await db.query(`UPDATE cost_codes SET description=$1,commercial_head=$2,commercial_family=$3,reporting_group=$4,trade=$4,hierarchy_mode=$5,commercial_head_id=$6,commercial_family_id=$7,reporting_group_id=$8,default_order_type=$9,default_vat_treatment=$10,reporting_order=$11,is_active=$12,import_metadata=$13,version=version+1,updated_at=NOW(),updated_by=$14 WHERE client_id=$15 AND id=$16 AND version=$17`,[value.description,value.commercialHead,value.commercialFamily||null,value.reportingGroup,value.hierarchyMode,payload.commercialHeadId,payload.commercialFamilyId,payload.reportingGroupId,value.defaultOrderType,value.defaultVatTreatment,value.reportingOrder,value.active,JSON.stringify(value.importMetadata),auth.displayName,clientId,existing.id,checked.expectedVersion]);if(!updated.rowCount){await db.query('ROLLBACK');return fail(409,`Cost Code ${row.code} changed after review.`);}}else{await db.query(`INSERT INTO cost_codes(client_id,code,description,commercial_head,commercial_family,reporting_group,trade,hierarchy_mode,commercial_head_id,commercial_family_id,reporting_group_id,default_order_type,default_vat_treatment,reporting_order,allow_budget,allow_purchase_orders,allow_ledger_import,allow_forecast_adjustment,notes,is_active,import_metadata,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$21)`,[clientId,value.code,value.description,value.commercialHead,value.commercialFamily||null,value.reportingGroup,value.hierarchyMode,payload.commercialHeadId,payload.commercialFamilyId,payload.reportingGroupId,value.defaultOrderType,value.defaultVatTreatment,value.reportingOrder,value.allowBudget,value.allowPurchaseOrders,value.allowLedgerImport,value.allowForecastAdjustment,value.notes,value.active,JSON.stringify(value.importMetadata),auth.displayName]);}}
 await db.query('COMMIT');return {ok:true,status:200,summary:{ok:true,rowsRead:current.rows.length,imported:current.rows.filter(x=>!x.isUpdate).length,updated:current.rows.filter(x=>x.isUpdate).length,rejected:0,skipped:0,headsCreated:new Set(current.proposals.map(x=>key(x.commercialHead))).size,familiesCreated:new Set(current.proposals.filter(x=>x.commercialFamily).map(x=>`${key(x.commercialHead)}::${key(x.commercialFamily)}`)).size,reportingGroupsCreated:current.proposals.length,headsMatched:current.summary.matched,familiesMatched:0,reportingGroupsMatched:current.summary.matched,warnings:[],errors:[]}};}catch(error){await db.query('ROLLBACK');if(error.code==='23505')return fail(409,'Commercial Structure or Cost Code changed after review. Refresh and review again.');throw error;}finally{db.release();}}
module.exports={STATES,catalogueToken,previewDocument,signReview,reviewMatches,preview,apply};
