const { CANONICAL_JSON_SHA256_V1, hashCanonicalJson, verifyJsonIntegrity } = require('./canonicalJsonIntegrity');
const SCHEMA_VERSION='cvr_commercial_hierarchy_v1';
const RESOLUTION_STATES=Object.freeze({ALLOCATED:'allocated',UNALLOCATED:'unallocated',UNRESOLVED_LEGACY:'unresolved_legacy',ARCHIVED_ASSIGNMENT:'archived_assignment',INVALID_ASSIGNMENT:'invalid_assignment',MISSING_COST_CODE:'missing_cost_code'});
const clean=value=>String(value||'').trim();
const keyOf=value=>clean(value).replace(/\s+/g,'').toLowerCase();
const orderOf=value=>Number.isFinite(Number(value))?Number(value):0;
function node(row,prefix){const id=row[`${prefix}_id`];return id?{id,name:row[`${prefix}_name`]||null,displayOrder:orderOf(row[`${prefix}_display_order`]),active:row[`${prefix}_active`]!==false}:null;}
function resolveRow(row){const head=node(row,'head'),family=node(row,'family'),reportingGroup=node(row,'group');const legacyEvidence={commercialHead:clean(row.commercial_head)||null,commercialFamily:clean(row.commercial_family)||null,reportingGroup:clean(row.reporting_group||row.trade)||null};const hasAnyId=Boolean(row.commercial_head_id||row.commercial_family_id||row.reporting_group_id),hasLegacy=Object.values(legacyEvidence).some(Boolean);let resolutionState;
 if(!hasAnyId)resolutionState=hasLegacy?RESOLUTION_STATES.UNRESOLVED_LEGACY:RESOLUTION_STATES.UNALLOCATED;else{const valid=Boolean(head&&reportingGroup&&(!row.commercial_family_id||family)&&String(row.group_head_id||'')===String(head.id)&&String(row.group_family_id||'')===String(family?.id||'')&&(!family||String(row.family_head_id||'')===String(head.id)));resolutionState=!valid?RESOLUTION_STATES.INVALID_ASSIGNMENT:(!head.active||!reportingGroup.active||(family&&!family.active))?RESOLUTION_STATES.ARCHIVED_ASSIGNMENT:RESOLUTION_STATES.ALLOCATED;}
 return {costCodeId:row.id,costCodeKey:clean(row.code),costCodeLabel:clean(row.description),costCodeActive:row.is_active!==false,resolutionState,head,family,reportingGroup,legacyEvidence};}
function canonicalDocument(rows){return JSON.parse(JSON.stringify({schemaVersion:SCHEMA_VERSION,costCodes:rows.map(resolveRow).sort((a,b)=>keyOf(a.costCodeKey).localeCompare(keyOf(b.costCodeKey))||String(a.costCodeId).localeCompare(String(b.costCodeId)))}));}
async function liveDocument(db,clientId){if(!db?.query)throw new Error('Commercial Structure authority database is unavailable.');const {rows}=await db.query(`SELECT c.*,h.id head_id,h.name head_name,h.display_order head_display_order,h.is_active head_active,f.id family_id,f.name family_name,f.display_order family_display_order,f.is_active family_active,f.head_id family_head_id,g.id group_id,g.name group_name,g.display_order group_display_order,g.is_active group_active,g.head_id group_head_id,g.family_id group_family_id FROM cost_codes c LEFT JOIN commercial_structure_heads h ON h.client_id=c.client_id AND h.id=c.commercial_head_id LEFT JOIN commercial_structure_families f ON f.client_id=c.client_id AND f.id=c.commercial_family_id LEFT JOIN commercial_structure_reporting_groups g ON g.client_id=c.client_id AND g.id=c.reporting_group_id WHERE c.client_id=$1 ORDER BY c.code,c.id`,[clientId]);return canonicalDocument(rows);}
function resolveCostCodes(document,costCodeKeys=[]){const byKey=new Map((document?.costCodes||[]).map(x=>[keyOf(x.costCodeKey),x]));return [...new Set(costCodeKeys.map(keyOf).filter(Boolean))].map(key=>byKey.get(key)||{costCodeId:null,costCodeKey:key,costCodeLabel:'',costCodeActive:false,resolutionState:RESOLUTION_STATES.MISSING_COST_CODE,head:null,family:null,reportingGroup:null,legacyEvidence:{commercialHead:null,commercialFamily:null,reportingGroup:null}});}
async function appendSubmission(db,{clientId,developmentId,periodId,auth={},actor=null}){const document=await liveDocument(db,clientId);const attempt=Number((await db.query('SELECT COALESCE(MAX(attempt_number),0)+1 attempt FROM cvr_period_hierarchy_submissions WHERE client_id=$1 AND period_id=$2',[clientId,periodId])).rows[0].attempt),hash=hashCanonicalJson(document);let userId=null,membershipId=null;if(auth.userId&&auth.membershipId){const identity=(await db.query('SELECT 1 FROM buildlite_users u JOIN client_user_memberships m ON m.user_id=u.id AND m.id=$2 AND m.client_id=$3 WHERE u.id=$1',[auth.userId,auth.membershipId,clientId])).rows[0];if(identity){userId=auth.userId;membershipId=auth.membershipId;}}const row=(await db.query(`INSERT INTO cvr_period_hierarchy_submissions(client_id,development_id,period_id,attempt_number,source_snapshot,source_snapshot_hash_scheme,source_snapshot_sha256,captured_by_user_id,captured_by_membership_id,captured_by_provider_user_id,captured_by_display_name,captured_by_role_key) VALUES($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[clientId,developmentId,periodId,attempt,JSON.stringify(document),CANONICAL_JSON_SHA256_V1,hash,userId,membershipId,auth.providerUserId||null,auth.displayName||actor||null,auth.roleKey||null])).rows[0];return {ok:true,row,document,hash};}
async function latest(db,clientId,periodId){return (await db.query('SELECT * FROM cvr_period_hierarchy_submissions WHERE client_id=$1 AND period_id=$2 ORDER BY attempt_number DESC LIMIT 1',[clientId,periodId])).rows[0]||null;}
function submittedDocument(row){if(!row)return {captured:false,legacy:true,document:null,integrity:null};return {captured:true,legacy:false,document:row.source_snapshot,integrity:verifyJsonIntegrity(row.source_snapshot,row.source_snapshot_sha256,row.source_snapshot_hash_scheme),row};}
module.exports={SCHEMA_VERSION,RESOLUTION_STATES,canonicalDocument,liveDocument,resolveCostCodes,appendSubmission,latest,submittedDocument};
