const { pool, query } = require('../db');

const run = (db, sql, params) => db ? db.query(sql, params) : query(sql, params);
function map(row) { return row && { id:row.id,clientId:row.client_id,developmentId:row.development_id,packageId:row.package_id,certificateId:row.certificate_id,costCode:row.cost_code,description:row.description,signedAmount:Number(row.signed_amount),basis:row.basis,status:row.status,createdAt:row.created_at,lockedAt:row.locked_at,createdBy:{userId:row.created_by_user_id,membershipId:row.created_by_membership_id,providerUserId:row.created_by_provider_user_id,displayName:row.created_by_display_name} }; }
async function listPaymentDiscoveredItems(clientId, packageId, certificateId, db=null) { const {rows}=await run(db,`SELECT * FROM package_payment_discovered_items WHERE client_id=$1 AND package_id=$2 AND certificate_id=$3 AND status<>'withdrawn' ORDER BY created_at,id`,[clientId,packageId,certificateId]); return rows.map(map); }
async function createPaymentDiscoveredItem(clientId, packageId, certificateId, body, auth) {
  const amount=Number(body.signedAmount); const description=String(body.description||'').trim(); const basis=String(body.basis||'').trim();
  if(!description||!basis||!Number.isFinite(amount)||amount===0)return {ok:false,status:400,message:'Description, basis and a non-zero signed amount are required.'};
  const db=await pool.connect(); try { await db.query('BEGIN');
    const {rows:[certificate]}=await db.query(`SELECT c.*,p.development_id,p.cost_code FROM package_payment_certificates c JOIN packages p ON p.id=c.package_id AND p.client_id=c.client_id WHERE c.client_id=$1 AND c.package_id=$2 AND c.id=$3 FOR UPDATE`,[clientId,packageId,certificateId]);
    if(!certificate){await db.query('ROLLBACK');return {ok:false,status:404,message:'Payment certificate not found.'};}
    if(certificate.status!=='draft'){await db.query('ROLLBACK');return {ok:false,status:409,message:'Payment-discovered items can only be added to a Draft certificate.'};}
    const {rows}=await db.query(`INSERT INTO package_payment_discovered_items(client_id,development_id,package_id,certificate_id,cost_code,description,signed_amount,basis,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[clientId,certificate.development_id,packageId,certificateId,certificate.cost_code,description,amount,basis,auth.userId,auth.membershipId,auth.providerUserId,auth.displayName]);
    await db.query(`INSERT INTO package_payment_discovered_item_audit(client_id,item_id,certificate_id,action,actor_user_id,actor_membership_id,actor_display_name,detail) VALUES($1,$2,$3,'created',$4,$5,$6,$7)`,[clientId,rows[0].id,certificateId,auth.userId,auth.membershipId,auth.displayName,JSON.stringify({signedAmount:amount,basis})]);
    await db.query('COMMIT'); return {ok:true,item:map(rows[0])};
  } catch(error){await db.query('ROLLBACK');throw error;} finally{db.release();}
}
async function deletePaymentDiscoveredItem(clientId,packageId,certificateId,itemId,auth){const db=await pool.connect();try{await db.query('BEGIN');const {rows}=await db.query(`UPDATE package_payment_discovered_items i SET status='withdrawn' FROM package_payment_certificates c WHERE i.id=$1 AND i.client_id=$2 AND i.package_id=$3 AND i.certificate_id=$4 AND i.status='draft' AND c.id=i.certificate_id AND c.status='draft' RETURNING i.*`,[itemId,clientId,packageId,certificateId]);if(!rows.length){await db.query('ROLLBACK');return {ok:false,status:409,message:'Only a Draft payment-discovered item on a Draft certificate can be removed.'};}await db.query(`INSERT INTO package_payment_discovered_item_audit(client_id,item_id,certificate_id,action,actor_user_id,actor_membership_id,actor_display_name) VALUES($1,$2,$3,'withdrawn',$4,$5,$6)`,[clientId,itemId,certificateId,auth.userId,auth.membershipId,auth.displayName]);await db.query('COMMIT');return {ok:true};}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}
async function lockPaymentDiscoveredItems(db,clientId,packageId,certificateId,auth){ const items=await listPaymentDiscoveredItems(clientId,packageId,certificateId,db); for(const item of items.filter(i=>i.status==='draft')){await db.query(`UPDATE package_payment_discovered_items SET status='locked',locked_at=NOW(),locked_by_user_id=$1 WHERE client_id=$2 AND id=$3`,[auth.userId,clientId,item.id]);await db.query(`INSERT INTO package_payment_discovered_item_audit(client_id,item_id,certificate_id,action,actor_user_id,actor_membership_id,actor_display_name) VALUES($1,$2,$3,'locked',$4,$5,$6)`,[clientId,item.id,certificateId,auth.userId,auth.membershipId,auth.displayName]);} return items; }
async function linkPaymentDiscoveredRegularisation(clientId,itemId,{commercialEventId=null,variationOrderId=null,comment=''}={},auth,db=null){const authorityType=commercialEventId?'commercial_event':variationOrderId?'variation_order':null;if(!authorityType)return {ok:false,status:400,message:'A Commercial Event or Variation Order authority is required.'};const owned=await run(db,`SELECT i.*,p.order_key FROM package_payment_discovered_items i JOIN packages p ON p.id=i.package_id AND p.client_id=i.client_id WHERE i.client_id=$1 AND i.id=$2 AND i.status='locked'`,[clientId,itemId]);if(!owned.rows.length)return {ok:false,status:404,message:'Locked payment-discovered item not found.'};const valid=authorityType==='commercial_event'?await run(db,`SELECT 1 FROM commercial_events WHERE client_id=$1 AND id=$2 AND package_id=$3`,[clientId,commercialEventId,owned.rows[0].package_id]):await run(db,`SELECT 1 FROM variation_orders WHERE client_id=$1 AND id=$2 AND package_id=$3 AND status='issued'`,[clientId,variationOrderId,owned.rows[0].package_id]);if(!valid.rows.length)return {ok:false,status:400,message:'Regularisation authority must belong to the same tenant and package.'};const inserted=await run(db,`INSERT INTO package_payment_discovered_regularisation_links(client_id,payment_discovered_item_id,authority_type,commercial_event_id,variation_order_id,linked_by_user_id,linked_by_membership_id,comment) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[clientId,itemId,authorityType,commercialEventId,variationOrderId,auth.userId,auth.membershipId,String(comment||'')]);await run(db,`INSERT INTO package_payment_discovered_item_audit(client_id,item_id,certificate_id,action,actor_user_id,actor_membership_id,actor_display_name,detail) VALUES($1,$2,$3,'regularisation_linked',$4,$5,$6,$7)`,[clientId,itemId,owned.rows[0].certificate_id,auth.userId,auth.membershipId,auth.displayName,JSON.stringify({authorityType,commercialEventId,variationOrderId})]);return {ok:true,link:inserted.rows[0]};}
module.exports={listPaymentDiscoveredItems,createPaymentDiscoveredItem,deletePaymentDiscoveredItem,lockPaymentDiscoveredItems,linkPaymentDiscoveredRegularisation};
