const { pool, query } = require('../db');
const { PERMISSIONS } = require('../auth/permissions');
const { assertServicePermission } = require('../auth/authorization');
const { getBuildLiteStandardSellingCostsTemplate } = require('./buildliteStandardSellingCostsTemplate');

const DRIVERS = new Set(['PERCENT_REVENUE', 'LUMP_SUM', 'QUANTITY_RATE']);
const number = (value, fallback = null) => value == null || value === '' ? fallback : Number.isFinite(Number(value)) ? Number(value) : fallback;
const actor = (auth) => { const test=process.env.BUILDLITE_SERVER_TEST==='1'||process.env.NODE_ENV==='test'; return {userId:test?null:auth?.userId||null,membershipId:test?null:auth?.membershipId||null,providerUserId:auth?.providerUserId||null,displayName:auth?.displayName||null}; };
const destination = (row) => row?.destination_id ? {id:row.destination_id,code:row.destination_code,description:row.destination_description||null,label:[row.destination_code,row.destination_description].filter(Boolean).join(' — '),active:row.destination_active!==false} : null;
const mapHeader = (row) => ({id:row.id,name:row.name,origin:row.origin,sourceStandardVersion:number(row.source_standard_version),isDefault:Boolean(row.is_default),simpleAssumptionPercent:number(row.simple_assumption_percent,2),simpleDestination:destination(row),version:Number(row.version)||1,createdAt:row.created_at||null,updatedAt:row.updated_at||null,createdBy:row.created_by_display_name||null,updatedBy:row.updated_by_display_name||null});
const mapLine = (row) => ({id:row.id,templateId:row.template_id,templateKey:row.template_key,name:row.name,description:row.description||null,forecastDriver:row.forecast_driver,defaultPercent:number(row.default_percent),defaultLumpSum:number(row.default_lump_sum),defaultQuantity:number(row.default_quantity),defaultRate:number(row.default_rate),quantitySource:row.default_quantity_source||'MANUAL',unitCode:row.default_unit_code||null,customUnitLabel:row.default_custom_unit_label||null,unitLabel:row.default_unit_code==='CUSTOM'?(row.default_custom_unit_label||null):(row.default_unit_code||row.unit_label||null),costCode:destination({...row,destination_id:row.cost_code_id,destination_code:row.cost_code,destination_description:row.cost_code_description,destination_active:row.cost_code_active}),displayOrder:Number(row.display_order)||0,enabled:row.enabled!==false,version:Number(row.version)||1});
const headerSelect=`SELECT t.*,c.id destination_id,c.code destination_code,c.description destination_description,c.is_active destination_active FROM client_selling_cost_templates t LEFT JOIN cost_codes c ON c.id=t.simple_destination_cost_code_id AND c.client_id=t.client_id`;
const lineSelect=`SELECT l.*,c.code cost_code,c.description cost_code_description,c.is_active cost_code_active FROM client_selling_cost_template_lines l LEFT JOIN cost_codes c ON c.id=l.cost_code_id AND c.client_id=l.client_id`;

async function costCode(clientId,id,run=query){if(!id)return null;return (await run(`SELECT id,code,description,is_active FROM cost_codes WHERE client_id=$1 AND id=$2`,[clientId,id])).rows[0]||null;}
async function listTemplates(clientId){return {ok:true,templates:(await query(`${headerSelect} WHERE t.client_id=$1 ORDER BY t.is_default DESC,lower(t.name),t.id`,[clientId])).rows.map(mapHeader)};}
async function getDefaultTemplate(clientId,dbClient=null){const run=dbClient?dbClient.query.bind(dbClient):query;const row=(await run(`${headerSelect} WHERE t.client_id=$1 AND t.is_default=true LIMIT 1`,[clientId])).rows[0];if(!row)return null;const lines=(await run(`${lineSelect} WHERE l.client_id=$1 AND l.template_id=$2 ORDER BY l.display_order,l.id`,[clientId,row.id])).rows.map(mapLine);return {...mapHeader(row),lines};}
async function getTemplate(clientId,id){const row=(await query(`${headerSelect} WHERE t.client_id=$1 AND t.id=$2`,[clientId,id])).rows[0];if(!row)return {ok:false,status:404,message:'Selling Costs template not found.'};const lines=(await query(`${lineSelect} WHERE l.client_id=$1 AND l.template_id=$2 ORDER BY l.display_order,l.id`,[clientId,id])).rows.map(mapLine);return {ok:true,template:{...mapHeader(row),lines}};}

async function createTemplate(clientId,body={},auth){
  assertServicePermission(auth,PERMISSIONS.COMMERCIAL_TEMPLATES_MANAGE); const name=String(body.name||'').trim(); if(!name)return {ok:false,status:400,message:'Template name is required.'};
  const origin=body.origin==='blank'?'blank':'buildlite_standard', standard=getBuildLiteStandardSellingCostsTemplate(), a=actor(auth), db=await pool.connect();
  try{await db.query('BEGIN');const makeDefault=body.isDefault===true||Number((await db.query(`SELECT COUNT(*) n FROM client_selling_cost_templates WHERE client_id=$1`,[clientId])).rows[0].n)===0;if(makeDefault)await db.query(`UPDATE client_selling_cost_templates SET is_default=false WHERE client_id=$1`,[clientId]);
    const row=(await db.query(`INSERT INTO client_selling_cost_templates(client_id,name,origin,source_standard_version,is_default,simple_assumption_percent,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name,updated_by_user_id,updated_by_membership_id,updated_by_provider_user_id,updated_by_display_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$7,$8,$9,$10) RETURNING id`,[clientId,name,origin,origin==='buildlite_standard'?standard.version:null,makeDefault,number(body.simpleAssumptionPercent,2),a.userId,a.membershipId,a.providerUserId,a.displayName])).rows[0];
    if(origin==='buildlite_standard')for(const line of standard.lines)await db.query(`INSERT INTO client_selling_cost_template_lines(client_id,template_id,template_key,name,forecast_driver,display_order,enabled,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name,updated_by_user_id,updated_by_membership_id,updated_by_provider_user_id,updated_by_display_name,default_quantity_source,default_unit_code) VALUES($1,$2,$3,$4,$5,$6,true,$7,$8,$9,$10,$7,$8,$9,$10,$11,$12)`,[clientId,row.id,line.templateKey,line.name,line.forecastDriver,line.displayOrder,a.userId,a.membershipId,a.providerUserId,a.displayName,line.quantitySource,line.unitCode]);
    await db.query('COMMIT');return {...await getTemplate(clientId,row.id),status:201};
  }catch(error){await db.query('ROLLBACK');if(error.code==='23505')return {ok:false,status:409,message:'A Selling Costs template with this name or default status already exists.'};throw error;}finally{db.release();}
}

async function saveLines(db,clientId,templateId,lines,a){
  if(!Array.isArray(lines))return {ok:true}; const ids=new Set((await db.query(`SELECT id FROM client_selling_cost_template_lines WHERE client_id=$1 AND template_id=$2`,[clientId,templateId])).rows.map(r=>r.id)); const retained=[];
  for(let i=0;i<lines.length;i+=1){const line=lines[i]||{}, name=String(line.name||'').trim(), driver=String(line.forecastDriver||'').toUpperCase();if(!name||!DRIVERS.has(driver))return {ok:false,status:400,message:'Each Detailed line needs a name and supported forecast driver.'};const costCodeId=line.costCodeId||line.costCode?.id||null;if(costCodeId){const mapped=await costCode(clientId,costCodeId,db.query.bind(db));if(!mapped||!mapped.is_active)return {ok:false,status:400,message:`${name} must map to an active company Cost Code.`};}
    const values=['defaultPercent','defaultLumpSum','defaultQuantity','defaultRate'].map(k=>number(line[k]));if(values.some((v,n)=>line[['defaultPercent','defaultLumpSum','defaultQuantity','defaultRate'][n]]!=null&&(v==null||v<0)))return {ok:false,status:400,message:`${name} contains an invalid assumption.`};let id=line.id&&ids.has(line.id)?line.id:null;
    const quantitySource=driver==='QUANTITY_RATE'?String(line.quantitySource||'MANUAL').toUpperCase():null;const unitCode=driver==='QUANTITY_RATE'?(quantitySource==='MANUAL'?String(line.unitCode||'EACH').toUpperCase():'PLOTS'):null;const customUnitLabel=unitCode==='CUSTOM'?String(line.customUnitLabel||'').trim():null;if(quantitySource&&!['MANUAL','TOTAL_PLOTS','PRIVATE_SALE_PLOTS'].includes(quantitySource))return {ok:false,status:400,message:`${name} has an invalid quantity source.`};if(unitCode&&!['PLOTS','MONTHS','WEEKS','VISITS','ITEMS','EACH','FT2','M2','CUSTOM'].includes(unitCode))return {ok:false,status:400,message:`${name} has an invalid unit.`};if(unitCode==='CUSTOM'&&(!customUnitLabel||customUnitLabel.length>40))return {ok:false,status:400,message:`${name} requires a custom unit of 1–40 characters.`};
    const params=[clientId,templateId,id,name,line.description||null,driver,...values,String(line.unitLabel||'').trim()||null,costCodeId,i+1,line.enabled!==false,a.userId,a.membershipId,a.providerUserId,a.displayName,quantitySource,unitCode,customUnitLabel];
    if(id)await db.query(`UPDATE client_selling_cost_template_lines SET name=$4,description=$5,forecast_driver=$6,default_percent=$7,default_lump_sum=$8,default_quantity=$9,default_rate=$10,unit_label=$11,cost_code_id=$12,display_order=$13,enabled=$14,version=version+1,updated_at=NOW(),updated_by_user_id=$15,updated_by_membership_id=$16,updated_by_provider_user_id=$17,updated_by_display_name=$18,default_quantity_source=$19,default_unit_code=$20,default_custom_unit_label=$21 WHERE client_id=$1 AND template_id=$2 AND id=$3`,params);
    else{id=(await db.query(`INSERT INTO client_selling_cost_template_lines(client_id,template_id,template_key,name,description,forecast_driver,default_percent,default_lump_sum,default_quantity,default_rate,unit_label,cost_code_id,display_order,enabled,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name,updated_by_user_id,updated_by_membership_id,updated_by_provider_user_id,updated_by_display_name,default_quantity_source,default_unit_code,default_custom_unit_label) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$15,$16,$17,$18,$19,$20,$21) RETURNING id`,[clientId,templateId,`company.${Date.now()}.${i}`,name,line.description||null,driver,...values,String(line.unitLabel||'').trim()||null,costCodeId,i+1,line.enabled!==false,a.userId,a.membershipId,a.providerUserId,a.displayName,quantitySource,unitCode,customUnitLabel])).rows[0].id;}retained.push(id);}
  if(retained.length)await db.query(`DELETE FROM client_selling_cost_template_lines WHERE client_id=$1 AND template_id=$2 AND NOT(id=ANY($3::uuid[]))`,[clientId,templateId,retained]);else await db.query(`DELETE FROM client_selling_cost_template_lines WHERE client_id=$1 AND template_id=$2`,[clientId,templateId]);return {ok:true};
}

async function updateTemplate(clientId,id,body={},auth){
  assertServicePermission(auth,PERMISSIONS.COMMERCIAL_TEMPLATES_MANAGE);const expected=Number(body.version);if(!Number.isInteger(expected)||expected<1)return {ok:false,status:400,message:'A valid template version is required.'};const a=actor(auth),db=await pool.connect();
  try{await db.query('BEGIN');const current=(await db.query(`SELECT * FROM client_selling_cost_templates WHERE client_id=$1 AND id=$2 FOR UPDATE`,[clientId,id])).rows[0];if(!current){await db.query('ROLLBACK');return {ok:false,status:404,message:'Selling Costs template not found.'};}if(Number(current.version)!==expected){await db.query('ROLLBACK');return {ok:false,status:409,message:'Selling Costs template version conflict.',template:(await getTemplate(clientId,id)).template};}
    const costCodeId=Object.hasOwn(body,'simpleDestinationCostCodeId')?(body.simpleDestinationCostCodeId||null):current.simple_destination_cost_code_id;if(costCodeId){const mapped=await costCode(clientId,costCodeId,db.query.bind(db));if(!mapped||!mapped.is_active){await db.query('ROLLBACK');return {ok:false,status:400,message:'Simple destination must be an active company Cost Code.'};}}
    const percent=Object.hasOwn(body,'simpleAssumptionPercent')?number(body.simpleAssumptionPercent):number(current.simple_assumption_percent,2),name=Object.hasOwn(body,'name')?String(body.name||'').trim():current.name,makeDefault=Object.hasOwn(body,'isDefault')?Boolean(body.isDefault):current.is_default;if(!name||percent==null||percent<0||percent>1000){await db.query('ROLLBACK');return {ok:false,status:400,message:'Template name and valid default percentage are required.'};}
    const lines=await saveLines(db,clientId,id,body.lines,a);if(!lines.ok){await db.query('ROLLBACK');return lines;}if(makeDefault)await db.query(`UPDATE client_selling_cost_templates SET is_default=false WHERE client_id=$1 AND id<>$2`,[clientId,id]);await db.query(`UPDATE client_selling_cost_templates SET name=$3,is_default=$4,simple_assumption_percent=$5,simple_destination_cost_code_id=$6,version=version+1,updated_at=NOW(),updated_by_user_id=$7,updated_by_membership_id=$8,updated_by_provider_user_id=$9,updated_by_display_name=$10 WHERE client_id=$1 AND id=$2`,[clientId,id,name,makeDefault,percent,costCodeId,a.userId,a.membershipId,a.providerUserId,a.displayName]);await db.query('COMMIT');return getTemplate(clientId,id);
  }catch(error){await db.query('ROLLBACK');if(error.code==='23505')return {ok:false,status:409,message:'Selling Costs template line or name conflicts with an existing value.'};throw error;}finally{db.release();}
}
module.exports={listTemplates,getTemplate,getDefaultTemplate,createTemplate,updateTemplate};
