const { pool, query } = require('../db');
const { getDefaultTemplate } = require('./sellingCostsTemplateRepository');
const { loadLiveForecastRevenue } = require('./sellingCostsProposal');
const { buildDetailedProposal, asNumber } = require('./sellingCostsDetailedProposal');
const { findDevelopmentById } = require('./developmentRepository');
const { assertServicePermission } = require('../auth/authorization');
const { PERMISSIONS } = require('../auth/permissions');

const SOURCES=new Set(['MANUAL','TOTAL_PLOTS','PRIVATE_SALE_PLOTS']);
const UNITS=new Set(['PLOTS','MONTHS','WEEKS','VISITS','ITEMS','EACH','FT2','M2','CUSTOM']);
async function loadAssumptions(clientId,developmentId,run=query){
  const rows=(await run(`SELECT a.*,c.code destination_code,c.description destination_description,c.is_active destination_active FROM development_selling_cost_line_assumptions a LEFT JOIN cost_codes c ON c.id=a.destination_cost_code_id AND c.client_id=a.client_id WHERE a.client_id=$1 AND a.development_id=$2`,[clientId,developmentId])).rows;
  return rows.map(row=>({templateLineId:row.template_line_id,driver:row.driver,percent:asNumber(row.percent),lumpSum:asNumber(row.lump_sum),quantity:asNumber(row.quantity),rate:asNumber(row.rate),quantitySource:row.quantity_source||'MANUAL',unitCode:row.unit_code||null,customUnitLabel:row.custom_unit_label||null,destinationCostCodeId:row.destination_cost_code_id||null,destination:row.destination_cost_code_id?{id:row.destination_cost_code_id,code:row.destination_code,description:row.destination_description,label:[row.destination_code,row.destination_description].filter(Boolean).join(' — '),active:row.destination_active!==false}:null,assumptionOverridden:row.assumption_overridden,destinationOverridden:row.destination_overridden,version:Number(row.version)}));
}
async function composeDetailed(clientId,developmentId,dbClient=null){
  const run=dbClient?dbClient.query.bind(dbClient):query;const template=await getDefaultTemplate(clientId,dbClient);const {revenue}=await loadLiveForecastRevenue(clientId,developmentId,{dbClient});const development=await findDevelopmentById(clientId,developmentId,dbClient);const assumptions=await loadAssumptions(clientId,developmentId,run);const settings=(await run(`SELECT id,version,source_template_id,source_template_version,updated_at,updated_by FROM development_selling_costs_settings WHERE client_id=$1 AND development_id=$2`,[clientId,developmentId])).rows[0]||null;
  return {...buildDetailedProposal({template,revenue,assumptions,development}),settings:{exists:Boolean(settings),id:settings?.id||null,version:Number(settings?.version)||0,sourceTemplateId:settings?.source_template_id||template?.id||null,sourceTemplateVersion:Number(settings?.source_template_version)||template?.version||null,updatedAt:settings?.updated_at||null,updatedBy:settings?.updated_by||null}};
}
function validateLine(line,templateLine){
  if(!templateLine)return 'Detailed line does not belong to the company template.';if(!['PERCENT_REVENUE','LUMP_SUM','QUANTITY_RATE'].includes(line.driver))return 'Unsupported Detailed forecast driver.';
  for(const key of ['percent','lumpSum','quantity','rate']){const value=asNumber(line[key]);if(line[key]!=null&&line[key]!==''&&(value==null||value<0))return 'Detailed assumptions must be non-negative numbers.';}
  const source=String(line.quantitySource||'MANUAL').toUpperCase(),unit=source==='MANUAL'?String(line.unitCode||'EACH').toUpperCase():'PLOTS';if(!SOURCES.has(source))return 'Unsupported Detailed quantity source.';if(!UNITS.has(unit))return 'Unsupported Detailed unit.';if(unit==='CUSTOM'&&(!String(line.customUnitLabel||'').trim()||String(line.customUnitLabel).trim().length>40))return 'Custom unit must contain 1–40 characters.';return null;
}
async function saveDetailed(clientId,developmentId,body,auth){
  assertServicePermission(auth,PERMISSIONS.CVR_EDIT);const expected=Number(body.version);if(!Number.isInteger(expected)||expected<0||!Array.isArray(body.lines))return {ok:false,status:400,message:'Version and Detailed lines are required.'};const db=await pool.connect();
  try{await db.query('BEGIN');const development=(await db.query(`SELECT id FROM developments WHERE client_id=$1 AND id=$2`,[clientId,developmentId])).rows[0];if(!development){await db.query('ROLLBACK');return {ok:false,status:404,message:'Development not found.'};}const template=await getDefaultTemplate(clientId,db);if(!template){await db.query('ROLLBACK');return {ok:false,status:409,message:'A company Selling Costs template is required.'};}const settings=(await db.query(`SELECT * FROM development_selling_costs_settings WHERE client_id=$1 AND development_id=$2 FOR UPDATE`,[clientId,developmentId])).rows[0];if(Number(settings?.version||0)!==expected){await db.query('ROLLBACK');return {ok:false,status:409,message:'Selling Costs settings version conflict.',proposal:await composeDetailed(clientId,developmentId)};}
    const byId=new Map(template.lines.map(line=>[line.id,line]));for(const line of body.lines){const problem=validateLine(line,byId.get(line.templateLineId));if(problem){await db.query('ROLLBACK');return {ok:false,status:400,message:problem};}if(line.destinationCostCodeId&&!((await db.query(`SELECT id FROM cost_codes WHERE client_id=$1 AND id=$2 AND is_active=true`,[clientId,line.destinationCostCodeId])).rows[0])){await db.query('ROLLBACK');return {ok:false,status:400,message:'Detailed destination must be an active company Cost Code.'};}}
    const userId=auth?.userId&&(await db.query(`SELECT 1 FROM buildlite_users WHERE id=$1`,[auth.userId])).rowCount?auth.userId:null,membershipId=auth?.membershipId&&(await db.query(`SELECT 1 FROM client_user_memberships WHERE id=$1 AND client_id=$2`,[auth.membershipId,clientId])).rowCount?auth.membershipId:null,actor=[userId,membershipId,auth?.providerUserId||null,auth?.displayName||null];
    if(settings)await db.query(`UPDATE development_selling_costs_settings SET mode='detailed',source_template_id=$3,source_template_version=$4,version=version+1,updated_at=NOW(),updated_by_user_id=$5,updated_by_membership_id=$6,updated_by_provider_user_id=$7,updated_by=$8 WHERE client_id=$1 AND development_id=$2`,[clientId,developmentId,template.id,template.version,...actor]);else await db.query(`INSERT INTO development_selling_costs_settings(client_id,development_id,mode,assumption_percent,source_template_id,source_template_version,version,updated_by_user_id,updated_by_membership_id,updated_by_provider_user_id,updated_by) VALUES($1,$2,'detailed',NULL,$3,$4,1,$5,$6,$7,$8)`,[clientId,developmentId,template.id,template.version,...actor]);
    for(const line of body.lines){const inherited=byId.get(line.templateLineId),override=Boolean(line.assumptionOverridden),source=override?String(line.quantitySource||'MANUAL').toUpperCase():(inherited.quantitySource||'MANUAL'),unit=source==='MANUAL'?(override?String(line.unitCode||'EACH').toUpperCase():(inherited.unitCode||'EACH')):'PLOTS',custom=unit==='CUSTOM'?(override?String(line.customUnitLabel||'').trim():inherited.customUnitLabel):null;
      await db.query(`INSERT INTO development_selling_cost_line_assumptions(client_id,development_id,template_id,template_line_id,driver,percent,lump_sum,quantity,rate,unit_label,destination_cost_code_id,assumption_overridden,destination_overridden,updated_by_user_id,updated_by_membership_id,updated_by_provider_user_id,updated_by_display_name,quantity_source,unit_code,custom_unit_label) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) ON CONFLICT(client_id,development_id,template_line_id) DO UPDATE SET driver=EXCLUDED.driver,percent=EXCLUDED.percent,lump_sum=EXCLUDED.lump_sum,quantity=EXCLUDED.quantity,rate=EXCLUDED.rate,unit_label=EXCLUDED.unit_label,destination_cost_code_id=EXCLUDED.destination_cost_code_id,assumption_overridden=EXCLUDED.assumption_overridden,destination_overridden=EXCLUDED.destination_overridden,version=development_selling_cost_line_assumptions.version+1,updated_at=NOW(),updated_by_user_id=EXCLUDED.updated_by_user_id,updated_by_membership_id=EXCLUDED.updated_by_membership_id,updated_by_provider_user_id=EXCLUDED.updated_by_provider_user_id,updated_by_display_name=EXCLUDED.updated_by_display_name,quantity_source=EXCLUDED.quantity_source,unit_code=EXCLUDED.unit_code,custom_unit_label=EXCLUDED.custom_unit_label`,[clientId,developmentId,template.id,line.templateLineId,override?line.driver:inherited.forecastDriver,override?asNumber(line.percent):null,override?asNumber(line.lumpSum):null,override&&source==='MANUAL'?asNumber(line.quantity):null,override?asNumber(line.rate):null,custom,line.destinationOverridden?(line.destinationCostCodeId||null):null,override,Boolean(line.destinationOverridden),...actor,source,unit,custom]);}
    await db.query('COMMIT');return {ok:true,proposal:await composeDetailed(clientId,developmentId)};
  }catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}
}
module.exports={composeDetailed,saveDetailed,loadAssumptions,validateLine};
