const { pool, query } = require('../db');
const { assertServicePermission } = require('../auth/authorization');
const { PERMISSIONS } = require('../auth/permissions');
const { isQualifyingContractEvent } = require('./variationOrderAuthority');

function toPence(value){
 const raw=String(value??'0').trim(),match=raw.match(/^([+-]?)(\d+)(?:\.(\d+))?$/);
 if(!match){const numeric=Number(value);return Number.isFinite(numeric)?Math.round(numeric*100):0;}
 const sign=match[1]==='-'?-1:1,whole=Number(match[2]),fraction=(match[3]||'').padEnd(3,'0');
 return sign*(whole*100+Number(fraction.slice(0,2))+(Number(fraction[2])>=5?1:0));
}
const fromPence=value=>Number(value||0)/100;
const money=value=>fromPence(toPence(value));
const fail = (status,message) => ({ok:false,status,message});
const actor = auth => [auth.userId,auth.membershipId,auth.providerUserId,auth.displayName];
const text = value => String(value ?? '').trim();
function requireActor(auth,permission){assertServicePermission(auth,permission);if(!auth?.userId||!auth?.membershipId||!auth?.providerUserId){const error=new Error('Authenticated BuildLite identity is required.');error.status=401;throw error;}}

function mapAllocation(row){return {id:row.id,variationAccountItemId:row.variation_account_item_id,sourceType:row.source_type,commercialEventId:row.commercial_event_id,variationOrderLineId:row.variation_order_line_id,futureSourceId:row.future_source_id,paymentAuthorityDecisionLineId:row.payment_authority_decision_line_id||null,allocatedAmount:Number(row.signed_allocated_amount),allocationKind:row.allocation_kind,reversesAllocationId:row.reverses_allocation_id,reason:row.reason,sourceStatus:row.source_status_snapshot,sourceValue:Number(row.source_value_snapshot),sourceReference:row.source_reference_snapshot,createdAt:row.created_at,createdBy:{userId:row.created_by_user_id,membershipId:row.created_by_membership_id,providerUserId:row.created_by_provider_user_id,displayName:row.created_by_display_name}};}
function mapSubstitution(row){return {id:row.id,successorAllocationId:row.successor_allocation_id,predecessorAllocationId:row.predecessor_allocation_id,substitutedAmount:Number(row.signed_substituted_amount),reason:row.reason,createdAt:row.created_at};}

function buildProjection({item,allocations=[],substitutions=[]}={}){
  const outgoing=new Map();for(const substitution of substitutions)outgoing.set(substitution.predecessorAllocationId,(outgoing.get(substitution.predecessorAllocationId)||0)+toPence(substitution.substitutedAmount));
  const projected=allocations.map(allocation=>{const allocated=toPence(allocation.allocatedAmount),substituted=outgoing.get(allocation.id)||0;return {...allocation,substitutedAmount:fromPence(substituted),effectiveAmount:fromPence(allocated-substituted)};});
  const sumPence=values=>values.reduce((sum,value)=>sum+toPence(value),0);
  const allocatedCe=fromPence(sumPence(allocations.filter(x=>x.sourceType==='commercial_event').map(x=>x.allocatedAmount)));
  const allocatedVo=fromPence(sumPence(allocations.filter(x=>x.sourceType==='variation_order_line').map(x=>x.allocatedAmount)));
  const allocatedPaymentAuthority=fromPence(sumPence(allocations.filter(x=>x.sourceType==='payment_authority').map(x=>x.allocatedAmount)));
  const effectiveCe=fromPence(sumPence(projected.filter(x=>x.sourceType==='commercial_event').map(x=>x.effectiveAmount)));
  const effectiveVo=fromPence(sumPence(projected.filter(x=>x.sourceType==='variation_order_line').map(x=>x.effectiveAmount)));
  const effectivePaymentAuthority=fromPence(sumPence(projected.filter(x=>x.sourceType==='payment_authority').map(x=>x.effectiveAmount)));
  const effectiveRecognised=fromPence(toPence(effectiveCe)+toPence(effectiveVo)+toPence(effectivePaymentAuthority));
  const forecast=money(item?.qsForecast);
  const mixedSign=forecast!==0&&effectiveRecognised!==0&&Math.sign(forecast)!==Math.sign(effectiveRecognised);
  const below=mixedSign||(effectiveRecognised>0?forecast<effectiveRecognised:effectiveRecognised<0?forecast>effectiveRecognised:false);
  const effectiveFinal=mixedSign?effectiveRecognised:effectiveRecognised>0?Math.max(forecast,effectiveRecognised):effectiveRecognised<0?Math.min(forecast,effectiveRecognised):forecast;
  const exception=mixedSign?'QS Forecast and effective recognised authority have opposing signs and require reconciliation.':below?`QS Forecast is below effective recognised authority by £${Math.abs(money(effectiveRecognised-forecast)).toFixed(2)}.`:null;
  return {variationAccountItemId:item?.id||null,reference:item?.reference||null,qsForecast:forecast,allocatedCeAuthority:allocatedCe,allocatedVoAuthority:allocatedVo,allocatedPaymentAuthority,effectiveCeAuthority:effectiveCe,effectiveVoAuthority:effectiveVo,effectivePaymentAuthority,effectiveRecognisedAuthority:effectiveRecognised,remainingForecastExposure:fromPence(toPence(effectiveFinal)-toPence(effectiveRecognised)),effectiveFinalExposure:money(effectiveFinal),forecastBelowAuthority:below,mixedSignAuthority:mixedSign,exception,allocations:projected,substitutions};
}

async function loadItem(db,clientId,itemId,lock=false){return (await db.query(`SELECT * FROM package_variation_account_items WHERE client_id=$1 AND id=$2${lock?' FOR UPDATE':''}`,[clientId,itemId])).rows[0]||null;}
async function loadFacts(db,clientId,itemId){const [a,s]=await Promise.all([db.query('SELECT * FROM package_variation_account_authority_allocations WHERE client_id=$1 AND variation_account_item_id=$2 ORDER BY created_at,id',[clientId,itemId]),db.query('SELECT * FROM package_variation_account_authority_substitutions WHERE client_id=$1 AND variation_account_item_id=$2 ORDER BY created_at,id',[clientId,itemId])]);return {allocations:a.rows.map(mapAllocation),substitutions:s.rows.map(mapSubstitution)};}
async function getProjection(clientId,itemId,auth,db=null){requireActor(auth,PERMISSIONS.VARIATION_ACCOUNT_VIEW);const run=db||{query};const row=await loadItem(run,clientId,itemId);if(!row)return null;const facts=await loadFacts(run,clientId,itemId);return buildProjection({item:{id:row.id,reference:row.variation_reference,qsForecast:Number(row.current_qs_forecast)},...facts});}

async function loadSource(db,clientId,packageId,sourceType,sourceId){
 if(sourceType==='commercial_event'){const row=(await db.query('SELECT * FROM commercial_events WHERE client_id=$1 AND package_id=$2 AND id=$3',[clientId,packageId,sourceId])).rows[0];if(!row||!isQualifyingContractEvent({status:row.status,eventType:row.event_type,relationshipType:row.relationship_type,financialTreatment:row.financial_treatment}))return null;return {type:sourceType,id:row.id,value:money(row.value),status:row.status,reference:row.event_number||row.id};}
 if(sourceType==='variation_order_line'){const row=(await db.query(`SELECT l.id,l.net_value,vo.status,vo.source_po_number,vo.variation_order_number,vo.id variation_order_id FROM variation_order_lines l JOIN variation_orders vo ON vo.client_id=l.client_id AND vo.id=l.variation_order_id WHERE l.client_id=$1 AND vo.package_id=$2 AND l.id=$3`,[clientId,packageId,sourceId])).rows[0];if(!row||row.status!=='issued')return null;return {type:sourceType,id:row.id,value:money(row.net_value),status:row.status,reference:`${row.source_po_number}/${row.variation_order_number}`,variationOrderId:row.variation_order_id};}
 return null;
}
async function sourceAllocated(db,clientId,sourceType,sourceId){const column=sourceType==='commercial_event'?'commercial_event_id':'variation_order_line_id';const row=(await db.query(`SELECT COALESCE(SUM(signed_allocated_amount),0) total FROM package_variation_account_authority_allocations WHERE client_id=$1 AND ${column}=$2`,[clientId,sourceId])).rows[0];return money(row.total);}

async function listEligibleSources(clientId,itemId,auth){requireActor(auth,PERMISSIONS.VARIATION_ACCOUNT_VIEW);const db=await pool.connect();try{const item=await loadItem(db,clientId,itemId);if(!item)return null;const [ces,vos]=await Promise.all([db.query(`SELECT id,event_number reference,value,status FROM commercial_events WHERE client_id=$1 AND package_id=$2 AND status IN('approved','includedInCertificate','closed') AND COALESCE(relationship_type,'')<>'recovery' AND COALESCE(event_type,'')<>'budgetTransfer'`,[clientId,item.package_id]),db.query(`SELECT l.id,(vo.source_po_number||'/'||vo.variation_order_number) reference,l.net_value value,vo.status FROM variation_order_lines l JOIN variation_orders vo ON vo.client_id=l.client_id AND vo.id=l.variation_order_id WHERE l.client_id=$1 AND vo.package_id=$2 AND vo.status='issued' ORDER BY vo.issued_at,l.line_number`,[clientId,item.package_id])]);const sources=[];for(const row of [...ces.rows.map(x=>({...x,sourceType:'commercial_event'})),...vos.rows.map(x=>({...x,sourceType:'variation_order_line'}))]){const allocated=await sourceAllocated(db,clientId,row.sourceType,row.id);sources.push({sourceType:row.sourceType,sourceId:row.id,reference:row.reference,sourceValue:Number(row.value),allocatedAmount:allocated,availableAmount:money(Number(row.value)-allocated),status:row.status});}return sources;}finally{db.release();}}

async function allocateAuthority(clientId,itemId,body,auth){requireActor(auth,PERMISSIONS.VARIATION_ACCOUNT_AUTHORITY_ALLOCATE);const sourceType=text(body.sourceType),sourceId=text(body.sourceId),amount=money(body.allocatedAmount),reason=text(body.reason),mode=body.overlapMode||'additional';if(!['commercial_event','variation_order_line'].includes(sourceType))return fail(400,'VA-3 supports Approved CE and Issued VO-line authority only.');if(!sourceId||!amount||!reason)return fail(400,'Source, non-zero signed allocation and reason are required.');if(!['additional','replaces'].includes(mode))return fail(400,'Choose Additional authority or Replaces existing authority.');const db=await pool.connect();try{await db.query('BEGIN');const item=await loadItem(db,clientId,itemId,true);if(!item){await db.query('ROLLBACK');return fail(404,'Variation Account item not found.');}if(item.status==='withdrawn'){await db.query('ROLLBACK');return fail(409,'Withdrawn Variation Account items cannot receive authority.');}const source=await loadSource(db,clientId,item.package_id,sourceType,sourceId);if(!source){await db.query('ROLLBACK');return fail(409,'Authority source is not eligible for this tenant/package or lifecycle.');}if(Math.sign(amount)!==Math.sign(source.value)){await db.query('ROLLBACK');return fail(400,'Allocation sign must match the authority source.');}const already=await sourceAllocated(db,clientId,sourceType,sourceId);if(Math.abs(money(already+amount))>Math.abs(source.value)+0.005||Math.sign(money(already+amount))!==Math.sign(source.value)){await db.query('ROLLBACK');return fail(409,'Allocation exceeds the remaining authoritative source amount.');}
 const inserted=(await db.query(`INSERT INTO package_variation_account_authority_allocations(client_id,development_id,package_id,variation_account_item_id,source_type,commercial_event_id,variation_order_line_id,signed_allocated_amount,reason,source_status_snapshot,source_value_snapshot,source_reference_snapshot,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) RETURNING *`,[clientId,item.development_id,item.package_id,item.id,sourceType,sourceType==='commercial_event'?source.id:null,sourceType==='variation_order_line'?source.id:null,amount,reason,source.status,source.value,source.reference,...actor(auth)])).rows[0];
 await db.query(`INSERT INTO package_variation_account_authority_audit(client_id,variation_account_item_id,allocation_id,action,detail,actor_user_id,actor_membership_id,actor_provider_user_id,actor_display_name) VALUES($1,$2,$3,'allocated',$4,$5,$6,$7,$8)`,[clientId,item.id,inserted.id,JSON.stringify({overlapMode:mode,sourceType,sourceId,amount}),...actor(auth)]);
 if(mode==='replaces'){const predecessorId=text(body.predecessorAllocationId),subPence=toPence(body.substitutedAmount),amountPence=toPence(amount),subAmount=fromPence(subPence);if(!predecessorId||!subPence||Math.sign(subPence)!==Math.sign(amountPence)||Math.abs(subPence)>Math.abs(amountPence)){throw Object.assign(new Error('A valid same-sign predecessor substitution within the new allocation is required.'),{status:400});}const predecessor=(await db.query('SELECT * FROM package_variation_account_authority_allocations WHERE client_id=$1 AND variation_account_item_id=$2 AND id=$3',[clientId,item.id,predecessorId])).rows[0];if(!predecessor)throw Object.assign(new Error('Predecessor authority allocation is invalid.'),{status:409});const used=toPence((await db.query('SELECT COALESCE(SUM(ABS(signed_substituted_amount)),0) total FROM package_variation_account_authority_substitutions WHERE client_id=$1 AND predecessor_allocation_id=$2',[clientId,predecessorId])).rows[0].total),predecessorPence=toPence(predecessor.signed_allocated_amount);if(Math.sign(subPence)!==Math.sign(predecessorPence)||used+Math.abs(subPence)>Math.abs(predecessorPence))throw Object.assign(new Error('Substitution exceeds the predecessor effective authority or has the wrong sign.'),{status:409});if(sourceType==='variation_order_line'&&predecessor.source_type==='commercial_event'){const link=(await db.query(`SELECT 1 FROM variation_order_line_commercial_event_allocations WHERE client_id=$1 AND variation_order_line_id=$2 AND commercial_event_id=$3`,[clientId,source.id,predecessor.commercial_event_id])).rows[0];if(!link)throw Object.assign(new Error('Issued VO line does not carry explicit source provenance for the CE being replaced.'),{status:409});}const substitution=(await db.query(`INSERT INTO package_variation_account_authority_substitutions(client_id,package_id,variation_account_item_id,successor_allocation_id,predecessor_allocation_id,signed_substituted_amount,reason,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[clientId,item.package_id,item.id,inserted.id,predecessorId,subAmount,reason,...actor(auth)])).rows[0];await db.query(`INSERT INTO package_variation_account_authority_audit(client_id,variation_account_item_id,substitution_id,action,detail,actor_user_id,actor_membership_id,actor_provider_user_id,actor_display_name) VALUES($1,$2,$3,'substituted',$4,$5,$6,$7,$8)`,[clientId,item.id,substitution.id,JSON.stringify({successorAllocationId:inserted.id,predecessorAllocationId:predecessorId,amount:subAmount}),...actor(auth)]);}
 await db.query('COMMIT');return {ok:true,status:201,projection:await getProjection(clientId,item.id,{...auth,permissions:[...(auth.permissions||[]),PERMISSIONS.VARIATION_ACCOUNT_VIEW]})};}catch(error){await db.query('ROLLBACK');if(error.status)return fail(error.status,error.message);throw error;}finally{db.release();}}

async function appendSubstitution(clientId,itemId,body,auth){
 requireActor(auth,PERMISSIONS.VARIATION_ACCOUNT_AUTHORITY_ALLOCATE);
 const successorId=text(body.successorAllocationId),predecessorId=text(body.predecessorAllocationId),reason=text(body.reason),amountPence=toPence(body.substitutedAmount);
 if(!successorId||!predecessorId||!amountPence||!reason)return fail(400,'Successor allocation, predecessor allocation, non-zero signed amount and reason are required.');
 const db=await pool.connect();
 try{
  await db.query('BEGIN');
  const item=await loadItem(db,clientId,itemId,true);
  if(!item){await db.query('ROLLBACK');return fail(404,'Variation Account item not found.');}
  if(item.status==='withdrawn'){await db.query('ROLLBACK');return fail(409,'Withdrawn Variation Account items cannot receive authority.');}
  const rows=(await db.query(`SELECT * FROM package_variation_account_authority_allocations WHERE client_id=$1 AND package_id=$2 AND variation_account_item_id=$3 AND id=ANY($4::uuid[]) FOR UPDATE`,[clientId,item.package_id,item.id,[successorId,predecessorId]])).rows;
  const successor=rows.find(row=>row.id===successorId),predecessor=rows.find(row=>row.id===predecessorId);
  if(!successor||!predecessor||successor.id===predecessor.id){await db.query('ROLLBACK');return fail(409,'Successor and predecessor allocations must be distinct authorities on this Variation Account item.');}
  const successorPence=toPence(successor.signed_allocated_amount),predecessorPence=toPence(predecessor.signed_allocated_amount);
  if(Math.sign(amountPence)!==Math.sign(successorPence)||Math.sign(amountPence)!==Math.sign(predecessorPence)){await db.query('ROLLBACK');return fail(400,'Substitution sign must match both predecessor and successor authority.');}
  if(successor.source_type==='variation_order_line'&&predecessor.source_type==='commercial_event'){
   const linked=(await db.query(`SELECT 1 FROM variation_order_line_commercial_event_allocations WHERE client_id=$1 AND variation_order_line_id=$2 AND commercial_event_id=$3`,[clientId,successor.variation_order_line_id,predecessor.commercial_event_id])).rows[0];
   if(!linked){await db.query('ROLLBACK');return fail(409,'Issued VO line does not carry explicit source provenance for the CE being replaced.');}
  }
  const consumed=(await db.query(`SELECT COALESCE(SUM(ABS(signed_substituted_amount)),0) predecessor_total,COALESCE((SELECT SUM(ABS(signed_substituted_amount)) FROM package_variation_account_authority_substitutions WHERE client_id=$1 AND successor_allocation_id=$3),0) successor_total FROM package_variation_account_authority_substitutions WHERE client_id=$1 AND predecessor_allocation_id=$2`,[clientId,predecessorId,successorId])).rows[0];
  if(toPence(consumed.predecessor_total)+Math.abs(amountPence)>Math.abs(predecessorPence)){await db.query('ROLLBACK');return fail(409,'Substitution exceeds the predecessor effective authority.');}
  if(toPence(consumed.successor_total)+Math.abs(amountPence)>Math.abs(successorPence)){await db.query('ROLLBACK');return fail(409,'Cumulative substitutions exceed the successor authority.');}
  const amount=fromPence(amountPence);
  const row=(await db.query(`INSERT INTO package_variation_account_authority_substitutions(client_id,package_id,variation_account_item_id,successor_allocation_id,predecessor_allocation_id,signed_substituted_amount,reason,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[clientId,item.package_id,item.id,successorId,predecessorId,amount,reason,...actor(auth)])).rows[0];
  await db.query(`INSERT INTO package_variation_account_authority_audit(client_id,variation_account_item_id,substitution_id,action,detail,actor_user_id,actor_membership_id,actor_provider_user_id,actor_display_name) VALUES($1,$2,$3,'substituted',$4,$5,$6,$7,$8)`,[clientId,item.id,row.id,JSON.stringify({successorAllocationId:successorId,predecessorAllocationId:predecessorId,amount,appendOnlyCorrection:true}),...actor(auth)]);
  await db.query('COMMIT');
  return {ok:true,status:201,substitution:mapSubstitution(row),projection:await getProjection(clientId,item.id,{...auth,permissions:[...(auth.permissions||[]),PERMISSIONS.VARIATION_ACCOUNT_VIEW]})};
 }catch(error){await db.query('ROLLBACK');if(error.status)return fail(error.status,error.message);throw error;}finally{db.release();}
}

async function reverseAllocation(clientId,itemId,allocationId,body,auth){requireActor(auth,PERMISSIONS.VARIATION_ACCOUNT_AUTHORITY_ALLOCATE);const reason=text(body.reason);if(!reason)return fail(400,'A reversal reason is required.');const db=await pool.connect();try{await db.query('BEGIN');const item=await loadItem(db,clientId,itemId,true);const original=(await db.query('SELECT * FROM package_variation_account_authority_allocations WHERE client_id=$1 AND variation_account_item_id=$2 AND id=$3',[clientId,itemId,allocationId])).rows[0];if(!item||!original){await db.query('ROLLBACK');return fail(404,'Authority allocation not found.');}const priorReversed=Number((await db.query(`SELECT COALESCE(SUM(ABS(signed_allocated_amount)),0) total FROM package_variation_account_authority_allocations WHERE client_id=$1 AND reverses_allocation_id=$2`,[clientId,allocationId])).rows[0].total);const requested=body.amount==null?Math.abs(Number(original.signed_allocated_amount))-priorReversed:Math.abs(money(body.amount));if(!requested||requested>Math.abs(Number(original.signed_allocated_amount))-priorReversed+.005){await db.query('ROLLBACK');return fail(409,'Reversal exceeds the unreversed allocation balance.');}const amount=money(-Math.sign(Number(original.signed_allocated_amount))*requested);const row=(await db.query(`INSERT INTO package_variation_account_authority_allocations(client_id,development_id,package_id,variation_account_item_id,source_type,commercial_event_id,variation_order_line_id,future_source_id,signed_allocated_amount,allocation_kind,reverses_allocation_id,reason,source_status_snapshot,source_value_snapshot,source_reference_snapshot,created_by_user_id,created_by_membership_id,created_by_provider_user_id,created_by_display_name) SELECT client_id,development_id,package_id,variation_account_item_id,source_type,commercial_event_id,variation_order_line_id,future_source_id,$4,'reversal',id,$5,source_status_snapshot,source_value_snapshot,source_reference_snapshot,$6,$7,$8,$9 FROM package_variation_account_authority_allocations WHERE client_id=$1 AND variation_account_item_id=$2 AND id=$3 RETURNING *`,[clientId,itemId,allocationId,amount,reason,...actor(auth)])).rows[0];await db.query(`INSERT INTO package_variation_account_authority_audit(client_id,variation_account_item_id,allocation_id,action,detail,actor_user_id,actor_membership_id,actor_provider_user_id,actor_display_name) VALUES($1,$2,$3,'reversed',$4,$5,$6,$7,$8)`,[clientId,itemId,row.id,JSON.stringify({reversesAllocationId:allocationId,amount}),...actor(auth)]);await db.query('COMMIT');return {ok:true,status:201,projection:await getProjection(clientId,itemId,{...auth,permissions:[...(auth.permissions||[]),PERMISSIONS.VARIATION_ACCOUNT_VIEW]})};}catch(error){await db.query('ROLLBACK');throw error;}finally{db.release();}}

module.exports={buildProjection,getProjection,listEligibleSources,allocateAuthority,appendSubstitution,reverseAllocation,mapAllocation,mapSubstitution,toPence,fromPence};
