import {useEffect,useState} from 'react';
import {confirmIntendedPayment,createPayLessNotice,createPaymentNotice,getPaymentAuthority,issuePaymentNotice,preparePaymentNotice,updatePaymentNotice} from '../api/paymentNotices';

const pounds=value=>value==null?'Not set':new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:2}).format(value);
const date=value=>{if(typeof value!=='string')return 'Not captured';const exact=/^\d{4}-\d{2}-\d{2}$/.test(value),parsed=new Date(exact?`${value}T12:00:00Z`:value);return Number.isNaN(parsed.valueOf())?'Not captured':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:exact?'UTC':'Europe/London'}).format(parsed);};
function deadlineText(label,value,asOf){if(!value)return `${label}: Not captured`;if(!asOf)return `${label}: ${date(value)}`;return value===asOf?`${label} is today, ${date(value)}`:value<asOf?`Configured ${label} passed on ${date(value)}`:`${label}: ${date(value)}`;}

export default function PaymentCertificateNotices({certificate,packageId,asOfDate}){
  const [workspace,setWorkspace]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [amount,setAmount]=useState(''),[basis,setBasis]=useState(''),[payLessBasis,setPayLessBasis]=useState('');
  const asOf=asOfDate||new Date().toISOString().slice(0,10);
  async function load(){if(!packageId||!certificate?.id)return;const value=await getPaymentAuthority(packageId,certificate.id,asOf);setWorkspace(value);const pn=value.notices?.find(n=>n.type==='payment_notice'),pl=value.notices?.find(n=>n.type==='pay_less_notice'&&!['superseded','voided'].includes(n.status));if(pn?.draft?.notifiedSum!=null)setAmount(String(pn.draft.notifiedSum));setPayLessBasis(pl?.draft?.basisConfirmed===true?pl.draft.basisOfCalculation||'':'');}
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[packageId,certificate?.id]);
  async function act(fn){setBusy(true);setMessage('');try{await fn();await load();setMessage('Authority updated.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  if(!workspace)return <section className="po-module-card"><h3>Payment notice</h3><p>{message||'Loading payment authority…'}</p></section>;
  const config=workspace.noticeConfiguration||{},payment=workspace.notices?.find(n=>n.type==='payment_notice'&&!['superseded','voided'].includes(n.status)),payLess=workspace.notices?.find(n=>n.type==='pay_less_notice'&&!['superseded','voided'].includes(n.status)),payLessAuthority=workspace.payLess||{state:'configuration_unavailable',deadline:null},frozenPayment=payment?.issuedSnapshot||payment?.preparedSnapshot||null,frozenIssuedPayLess=payLess?.status==='issued'?payLess.issuedSnapshot:null;
  const locked=certificate.status==='locked';
  return <section className="po-module-card po-cert-notices" aria-labelledby="payment-notice-heading">
    <div className="po-cert-notices__heading"><div><h3 id="payment-notice-heading">Payment notice</h3><p>{config.state==='ready'?`Configured mode: ${String(config.mode).replaceAll('_',' ')}`:config.reasons?.[0]||'Notice configuration unavailable'}</p></div>{payment?<span className="admin-chip">{payment.status}</span>:null}</div>
    {config.state!=='ready'?<p>Payment Rules V1 remains timetable-capable; no Payment Notice authority is inferred.</p>:config.mode==='certificate_only'?<p>Certificate-only mode is configured. BuildLite does not assert that this certificate is a Payment Notice.</p>:<>
      {!payment&&locked?<button disabled={busy} onClick={()=>act(()=>createPaymentNotice(packageId,certificate.id,{}))}>Prepare Payment Notice</button>:null}
      {payment?.status==='draft'?<div className="po-cert-notices__form"><label>Explicit notified sum<input className="input" type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Basis of calculation<textarea className="input" value={basis} onChange={e=>setBasis(e.target.value)}/></label><button disabled={busy} onClick={()=>act(async()=>{await updatePaymentNotice(payment.id,{version:payment.version,notifiedSum:Number(amount),notifiedSumConfirmed:true,basisOfCalculation:basis});await preparePaymentNotice(payment.id);})}>Confirm &amp; Prepare</button></div>:null}
      {payment?.status==='prepared'?<button disabled={busy} onClick={()=>act(()=>issuePaymentNotice(payment.id))}>Issue Payment Notice</button>:null}
      {frozenPayment?<dl className="po-cert-notices__facts"><div><dt>Notified sum</dt><dd>{pounds(frozenPayment.notifiedSum)}</dd></div><div><dt>Basis of calculation</dt><dd>{frozenPayment.basisOfCalculation||'Not captured'}</dd></div><div><dt>Assessed net basis</dt><dd>{pounds(frozenPayment.assessedNet)}</dd></div><div><dt>Reference</dt><dd>{payment.reference}</dd></div></dl>:null}
    </>}
    <div className="po-cert-notices__payless"><h4>Intended payment &amp; Pay Less review</h4><p>{String(payLessAuthority.state||'configuration_unavailable').replaceAll('_',' ')}</p><p>{deadlineText('Pay Less deadline',payLessAuthority.deadline,asOf)}</p>
      {payment?.status==='issued'?<div className="po-cert-notices__form"><label>Intended payment<input className="input" type="number" step="0.01" defaultValue={payLessAuthority.intendedPayment??payment.issuedSnapshot.notifiedSum}/></label><button disabled={busy} onClick={e=>{const input=e.currentTarget.parentElement.querySelector('input');act(()=>confirmIntendedPayment(packageId,certificate.id,{intendedAmount:Number(input.value),source:'manual'}));}}>Confirm Intended Payment</button></div>:null}
      {payLessAuthority.state==='review_required'&&!payLess?<button disabled={busy} onClick={()=>act(()=>createPayLessNotice(packageId,certificate.id,{}))}>Prepare Pay Less Notice</button>:null}
      {payLess&&['draft','prepared'].includes(payLess.status)&&payLess.draft?.basisConfirmed!==true?<div className="po-cert-notices__form"><p>Notified {pounds(payLessAuthority.notifiedSum)} · Intended {pounds(payLessAuthority.intendedPayment)} · Reduction {pounds(payLessAuthority.reduction)}</p><label>Pay Less basis of calculation<textarea className="input" value={payLessBasis} onChange={e=>setPayLessBasis(e.target.value)}/></label><button disabled={busy||!payLessBasis.trim()} onClick={()=>act(async()=>{await updatePaymentNotice(payLess.id,{version:payLess.version,basisOfCalculation:payLessBasis});await preparePaymentNotice(payLess.id);})}>Confirm Basis &amp; Prepare</button></div>:null}
      {payLess?.status==='prepared'&&payLess.draft?.basisConfirmed===true?<><dl className="po-cert-notices__facts"><div><dt>Notified sum</dt><dd>{pounds(payLess.preparedSnapshot?.notifiedSum)}</dd></div><div><dt>Intended payment</dt><dd>{pounds(payLess.preparedSnapshot?.intendedPayment)}</dd></div><div><dt>Reduction</dt><dd>{pounds(payLess.preparedSnapshot?.reduction)}</dd></div><div><dt>Basis of calculation</dt><dd>{payLess.preparedSnapshot?.basisOfCalculation||'Not captured'}</dd></div></dl><button disabled={busy} onClick={()=>act(()=>issuePaymentNotice(payLess.id))}>Issue Pay Less Notice</button></>:null}
      {frozenIssuedPayLess?<dl className="po-cert-notices__facts"><div><dt>Status</dt><dd>Issued</dd></div><div><dt>Reference</dt><dd>{frozenIssuedPayLess.reference||payLess.reference}</dd></div><div><dt>Notified sum</dt><dd>{pounds(frozenIssuedPayLess.notifiedSum)}</dd></div><div><dt>Intended payment</dt><dd>{pounds(frozenIssuedPayLess.intendedPayment)}</dd></div><div><dt>Reduction</dt><dd>{pounds(frozenIssuedPayLess.reduction)}</dd></div><div><dt>Basis of calculation</dt><dd>{frozenIssuedPayLess.basisOfCalculation||'Not captured'}</dd></div><div><dt>Pay Less deadline</dt><dd>{date(frozenIssuedPayLess.payLessDeadline)}</dd></div></dl>:null}
      {payLessAuthority.notifiedSum!=null?<p>Notified {pounds(payLessAuthority.notifiedSum)} · Intended {pounds(payLessAuthority.intendedPayment)} · Reduction {pounds(payLessAuthority.reduction)}</p>:null}
    </div>{message?<p role={message==='Authority updated.'?'status':'alert'}>{message}</p>:null}
  </section>;
}
