// @vitest-environment jsdom
import React from 'react';import {act} from 'react';import {createRoot} from 'react-dom/client';import {afterEach,describe,it,expect,vi} from 'vitest';
const mocks=vi.hoisted(()=>({list:vi.fn(),save:vi.fn(),withdraw:vi.fn(),refresh:vi.fn()}));
vi.mock('../auth/BuildLiteAuthProvider',()=>({useBuildLitePermission:()=>true}));
vi.mock('../api/paymentCertificates',()=>({listVariationAssessments:mocks.list,saveVariationAssessment:mocks.save,withdrawVariationAssessment:mocks.withdraw}));
vi.mock('../payments/paymentCertificateServerCache',()=>({refreshCertificatesForPackage:mocks.refresh}));
import PaymentCertificateVariationAssessments from './PaymentCertificateVariationAssessments';globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const item={variationAccountItemId:'va1',reference:'VA-0001',description:'Drainage design changes',contractorValue:20000,contractorClaim:10000,qsForecast:17000,previousCertified:0,applicationVariationLineId:'line1',inCurrentApplication:true,assessment:null};
describe('PaymentCertificateVariationAssessments',()=>{afterEach(()=>{vi.clearAllMocks();document.body.innerHTML='';});it('shows distinct contractor, claim, forecast and assessment facts',async()=>{mocks.list.mockResolvedValue({items:[item]});const host=document.createElement('div');document.body.appendChild(host);const root=createRoot(host);await act(async()=>root.render(<PaymentCertificateVariationAssessments packageId="pkg" certificate={{id:'cert',version:1}} editable/>));await act(async()=>Promise.resolve());expect(host.textContent).toContain('VA-0001');expect(host.textContent).toContain('£20,000.00');expect(host.textContent).toContain('£10,000.00');expect(host.textContent).toContain('£17,000.00');expect(host.textContent).toContain('Matched to current application');expect(host.textContent).not.toContain('payment-discovered');await act(async()=>root.unmount());});it('labels an unclaimed active VA item and requires a basis before Apply',async()=>{mocks.list.mockResolvedValue({items:[{...item,contractorClaim:null,applicationVariationLineId:null,inCurrentApplication:false}]});const host=document.createElement('div');document.body.appendChild(host);const root=createRoot(host);await act(async()=>root.render(<PaymentCertificateVariationAssessments packageId="pkg" certificate={{id:'cert'}} editable/>));await act(async()=>Promise.resolve());expect(host.textContent).toContain('Not included in current application');expect([...host.querySelectorAll('button')].find(x=>x.textContent.includes('Apply')).disabled).toBe(true);await act(async()=>root.unmount());});});
