// @vitest-environment jsdom
import React from 'react';import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';import {act} from 'react';import {createRoot} from 'react-dom/client';
import PaymentCertificateNotices from './PaymentCertificateNotices';
vi.mock('../api/paymentNotices',()=>({getPaymentAuthority:vi.fn(),createPaymentNotice:vi.fn(),updatePaymentNotice:vi.fn(),preparePaymentNotice:vi.fn(),issuePaymentNotice:vi.fn(),confirmIntendedPayment:vi.fn(),createPayLessNotice:vi.fn()}));
import {getPaymentAuthority} from '../api/paymentNotices';
describe('Payment Certificate notice authority',()=>{let host,root;beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);});afterEach(()=>{act(()=>root.unmount());host.remove();vi.clearAllMocks();});async function render(value){getPaymentAuthority.mockResolvedValue(value);await act(async()=>root.render(<PaymentCertificateNotices certificate={{id:'c1',status:'locked'}} packageId="p1"/>));await act(async()=>{});}
it('states V1 is timetable-only without fabricating notice authority',async()=>{await render({noticeConfiguration:{state:'configuration_unavailable',reasons:['Payment Rules V1 is timetable-capable but has no Payment Notice configuration.']},notices:[],payLess:{state:'configuration_unavailable'}});expect(host.textContent).toContain('Payment Rules V1');expect(host.textContent).not.toContain('Notified sum£');});
it('distinguishes notified sum, intended payment and factual Pay Less review',async()=>{await render({noticeConfiguration:{state:'ready',mode:'separate_payment_notice'},notices:[{id:'n1',type:'payment_notice',status:'issued',reference:'PN-1',issuedSnapshot:{notifiedSum:1000,assessedNet:900,basisOfCalculation:'Assessment'}}],payLess:{state:'review_required',notifiedSum:1000,intendedPayment:800,reduction:200,deadline:'2026-09-29'}});expect(host.textContent).toContain('Notified £1,000.00');expect(host.textContent).toContain('Intended £800.00');expect(host.textContent).toContain('Reduction £200.00');expect(host.textContent).toContain('Prepare Pay Less Notice');});
it('shows frozen Prepared notified sum and basis before Payment Notice Issue',async()=>{await render({noticeConfiguration:{state:'ready',mode:'certificate_as_payment_notice'},notices:[{id:'n1',type:'payment_notice',status:'prepared',reference:'PN-1',preparedSnapshot:{notifiedSum:1140,assessedNet:1140,basisOfCalculation:'Payment Certificate No. 1 assessment'}}],payLess:{state:'no_intended_payment',notifiedSum:1140,intendedPayment:null,reduction:null,deadline:'2026-09-29'}});expect(host.textContent).toContain('£1,140.00');expect(host.textContent).toContain('Payment Certificate No. 1 assessment');expect(host.textContent).toContain('Issue Payment Notice');});
it('blocks Pay Less Issue and requests human basis when a legacy Prepared attempt lacks confirmation provenance',async()=>{await render({noticeConfiguration:{state:'ready',mode:'certificate_as_payment_notice'},notices:[{id:'pn',type:'payment_notice',status:'issued',reference:'PN-1',issuedSnapshot:{notifiedSum:1140,assessedNet:1140,basisOfCalculation:'Assessment'}},{id:'pl',type:'pay_less_notice',status:'prepared',version:2,reference:'PLN-1',draft:{basisOfCalculation:'Payment decision below notified sum'},preparedSnapshot:{notifiedSum:1140,intendedPayment:900,reduction:240,basisOfCalculation:'Payment decision below notified sum'}}],payLess:{state:'draft_prepared',notifiedSum:1140,intendedPayment:900,reduction:240,deadline:'2026-09-29'}});expect(host.textContent).toContain('Pay Less basis of calculation');expect(host.textContent).toContain('Confirm Basis & Prepare');expect(host.textContent).not.toContain('Issue Pay Less Notice');});
it('shows frozen Pay Less basis and Issue only after explicit confirmation',async()=>{await render({noticeConfiguration:{state:'ready',mode:'certificate_as_payment_notice'},notices:[{id:'pn',type:'payment_notice',status:'issued',reference:'PN-1',issuedSnapshot:{notifiedSum:1140,assessedNet:1140,basisOfCalculation:'Assessment'}},{id:'pl',type:'pay_less_notice',status:'prepared',version:5,reference:'PLN-1',draft:{basisOfCalculation:'£240 reduction agreed following QS review',basisConfirmed:true},preparedSnapshot:{notifiedSum:1140,intendedPayment:900,reduction:240,basisOfCalculation:'£240 reduction agreed following QS review'}}],payLess:{state:'draft_prepared',notifiedSum:1140,intendedPayment:900,reduction:240,deadline:'2026-09-29'}});expect(host.textContent).toContain('£240 reduction agreed following QS review');expect(host.textContent).toContain('Issue Pay Less Notice');});
it('renders Issued Pay Less review from its frozen Issued snapshot',async()=>{await render({noticeConfiguration:{state:'ready',mode:'certificate_as_payment_notice'},notices:[{id:'pn',type:'payment_notice',status:'issued',reference:'PN-1',issuedSnapshot:{notifiedSum:1140,assessedNet:1140,basisOfCalculation:'Assessment'}},{id:'pl',type:'pay_less_notice',status:'issued',version:5,reference:'PLN-1',draft:{basisOfCalculation:'mutable text'},issuedSnapshot:{reference:'PLN-1',notifiedSum:1140,intendedPayment:900,reduction:240,basisOfCalculation:'£240 withheld pending resolution of outstanding defects',payLessDeadline:'2026-09-29'}}],payLess:{state:'issued',notifiedSum:999,intendedPayment:999,reduction:0,deadline:'2026-10-01'}});expect(host.textContent).toContain('StatusIssued');expect(host.textContent).toContain('ReferencePLN-1');expect(host.textContent).toContain('Notified sum£1,140.00');expect(host.textContent).toContain('Intended payment£900.00');expect(host.textContent).toContain('Reduction£240.00');expect(host.textContent).toContain('£240 withheld pending resolution of outstanding defects');expect(host.textContent).toContain('29 Sept 2026');expect(host.textContent).not.toContain('Issue Pay Less Notice');});
it('renders the real PostgreSQL DATE response shape without crashing',async()=>{await render({noticeConfiguration:{state:'ready',mode:'certificate_as_payment_notice',reasons:[]},notices:[],decisions:[],payLess:{state:'no_notified_sum',notifiedSum:null,intendedPayment:null,reduction:null,deadline:'2026-09-28T23:00:00.000Z'}});expect(host.textContent).toContain('Prepare Payment Notice');expect(host.textContent).toContain('29 Sept 2026');});
it('fails closed when Pay Less authority is absent',async()=>{await render({noticeConfiguration:{state:'configuration_unavailable',reasons:['Notice configuration unavailable']},notices:[]});expect(host.textContent).toContain('configuration unavailable');expect(host.textContent).toContain('Pay Less deadline: Not captured');});});
