// @vitest-environment jsdom
import React from 'react';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { createRoot } from 'react-dom/client';
import { act } from 'react';
let permissions=[];
vi.mock('../auth/BuildLiteAuthProvider',()=>({useBuildLitePermission:value=>permissions.includes(value)}));
const api=vi.hoisted(()=>({getPaymentApprovalQueue:vi.fn(),approveSubmittedCertificate:vi.fn(),rejectCertificateForPackage:vi.fn()}));
vi.mock('../api/paymentAuthority',()=>({getPaymentApprovalQueue:api.getPaymentApprovalQueue,approveSubmittedCertificate:api.approveSubmittedCertificate}));
vi.mock('../api/paymentCertificates',()=>({rejectCertificateForPackage:api.rejectCertificateForPackage}));
import PaymentApprovalRun from './PaymentApprovalRun';

const base={id:'c1',certificateId:'c1',packageId:'p1',certificateVersion:2,certificateNumber:1,development:'Hawthorn Gardens UAT',subcontractor:'Peak Roofing Ltd',packageTrade:'4180 / Roofing',gross:38400,contractorApplication:38400,applicationDifference:0,orderedWorks:38400,variations:0,otherAssessed:0,appliedPriorAuthority:0,unapprovedAtLock:0,retention:1920,recoveries:0,vat:7296,net:43776,notifiedSum:43776,intendedPayment:43776,payLessReduction:0,cashAmountProposed:43776,dueDate:'2026-10-05',paymentNoticeDeadline:'2026-10-10',payLessDeadline:'2026-10-14',finalPaymentDate:'2026-10-19',submittedBy:'QS User',submittedAt:'2026-09-29T14:11:25Z',workflowState:'awaiting_approval',statusSummary:'Awaiting Approval',eligible:true,warnings:[],hardBlockers:[],lines:[]};
const warning={...base,id:'c2',certificateId:'c2',certificateNumber:2,statusSummary:'1 warning',warnings:[{code:'payment_notice_incomplete',meaning:'The required Payment Notice has not been issued.'}]};
const blocked={...base,id:'c3',certificateId:'c3',certificateNumber:3,eligible:false,statusSummary:'Approval blocked',hardBlockers:['Authoritative certificate calculation is unavailable.']};
const authorised={...base,id:'c4',certificateId:'c4',certificateNumber:4,workflowState:'authorised',statusSummary:'Payment Authorised',authorisedCashAmount:900};
const setValue=async(node,value)=>{const prototype=node.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(prototype,'value').set;await act(async()=>{setter.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));});};
const button=(host,label,dialog=false)=>[...(dialog?document.querySelector('[role="dialog"]'):host).querySelectorAll('button')].find(node=>node.textContent===label||node.textContent.includes(label));

describe('PaymentApprovalRun single commercial approval',()=>{
 let host,root;
 beforeEach(async()=>{permissions=['payment_approval_run.view','certificate.lock','payment_authority.approve'];host=document.createElement('div');document.body.append(host);root=createRoot(host);api.getPaymentApprovalQueue.mockResolvedValue([base,warning,blocked,authorised]);api.approveSubmittedCertificate.mockResolvedValue({ok:true});api.rejectCertificateForPackage.mockResolvedValue({});await act(async()=>{root.render(<PaymentApprovalRun/>);await Promise.resolve();});});
 afterEach(()=>{root.unmount();host.remove();vi.clearAllMocks();});
 it('defaults to the Submitted queue and keeps genuine authority history separate',()=>{expect(host.textContent).toContain('Awaiting Approval (3)');expect(host.textContent).toContain('Certificate 1');expect(host.textContent).not.toContain('Certificate 4');expect(host.textContent).toContain('Payment Authorised (1)');expect(host.querySelector('input[aria-label="Select certificate 3"]').disabled).toBe(true);});
 it('keeps process warnings visible without requiring acknowledgement or comment',async()=>{await act(async()=>host.querySelector('input[aria-label="Select certificate 2"]').click());expect(button(host,'Approve & Authorise Selected').disabled).toBe(false);await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 2')).querySelector('button').click());expect(host.textContent).toContain('The required Payment Notice has not been issued.');expect(host.querySelector('input[aria-label="Acknowledge warnings for certificate 2"]')).toBeNull();});
 it('shows the submitted payment bridge and every contractual timetable date',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 1')).querySelector('button').click());expect(host.textContent).toContain('Payment calculation');expect(host.textContent).toContain('Gross assessment£38,400.00');expect(host.textContent).toContain('Retention−£1,920.00');expect(host.textContent).toContain('VAT£7,296.00');expect(host.textContent).toContain('Net payment£43,776.00');expect(host.textContent).toContain('Due date5 Oct 2026');expect(host.textContent).toContain('Payment Notice deadline10 Oct 2026');expect(host.textContent).toContain('Pay Less deadline14 Oct 2026');expect(host.textContent).toContain('Final payment date19 Oct 2026');});
 it('requires acknowledgement and reason for an exceptional cash authority',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 1')).querySelector('button').click());await setValue(host.querySelector('input[aria-label="Certificate 1 cash authority"]'),'850');await act(async()=>host.querySelector('input[aria-label="Select certificate 1"]').click());expect(button(host,'Approve & Authorise Selected').disabled).toBe(true);expect(host.textContent).toContain('Commercial authority exception');await act(async()=>host.querySelector('input[aria-label="Acknowledge commercial exception for certificate 1"]').click());await setValue(host.querySelector('textarea[aria-label="Certificate 1 exception reason"]'),'Exceptional cash position approved.');expect(button(host,'Approve & Authorise Selected').disabled).toBe(false);});
 it('uses the combined endpoint without actor, browser totals or process-warning declarations',async()=>{await act(async()=>host.querySelector('input[aria-label="Select certificate 2"]').click());await act(async()=>button(host,'Approve & Authorise Selected').click());await act(async()=>button(host,'Approve & Authorise',true).click());const payload=api.approveSubmittedCertificate.mock.calls[0][0];expect(payload).toMatchObject({packageId:'p1',certificateId:'c2',certificateVersion:2,cashAmount:43776,reason:'Payment authorisation',warningAcknowledgements:[],warningComment:''});expect(payload).not.toHaveProperty('actor');expect(payload).not.toHaveProperty('gross');expect(payload).not.toHaveProperty('net');});
 it('returns to QS only after a reason',async()=>{await act(async()=>button(host,'Return to QS').click());const action=button(host,'Return to QS',true);expect(action.disabled).toBe(true);await setValue(document.querySelector('textarea[aria-label="Return to QS reason"]'),'Please revise.');await act(async()=>action.click());expect(api.rejectCertificateForPackage).toHaveBeenCalledWith('p1','c1',{version:2,comment:'Please revise.'});});
 it('requires both domain permissions for selection',async()=>{permissions=['payment_approval_run.view','certificate.lock'];await act(async()=>root.render(<PaymentApprovalRun/>));expect(host.querySelector('input[aria-label="Select certificate 1"]').disabled).toBe(true);});
});
