// @vitest-environment jsdom
import React from 'react';
import { createRoot } from 'react-dom/client';
import { act } from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import PaymentCertificateApplication from './PaymentCertificateApplication';
import { createPaymentApplication, listPaymentApplications, revisePaymentApplication } from '../api/paymentApplications';

vi.mock('../api/paymentApplications',()=>({listPaymentApplications:vi.fn(async()=>[]),createPaymentApplication:vi.fn(),revisePaymentApplication:vi.fn()}));
let container;
let root;
afterEach(()=>{if(root)act(()=>root.unmount());container?.remove();container=null;root=null;vi.mocked(listPaymentApplications).mockResolvedValue([]);vi.clearAllMocks();});
async function render(props={}){container=document.createElement('div');document.body.append(container);root=createRoot(container);await act(async()=>{root.render(<PaymentCertificateApplication packageId="pkg" certificate={{id:'cert',status:'draft'}} assessmentGross={1000} editable {...props}/>);await Promise.resolve();});return container;}

describe('PaymentCertificateApplication',()=>{
  it('renders focused capture without notice, comparison, source or variation clutter',async()=>{const node=await render();expect(node.textContent).toContain('Application Ref');expect(node.textContent).toContain('Application Date');expect(node.textContent).toContain('Application this period');expect(node.textContent).not.toContain('Notice readiness');expect(node.textContent).not.toContain('BuildLite Assessment');expect(node.textContent).not.toContain('Comparison basis');expect(node.textContent).not.toContain('Show source breakdown');expect(node.textContent).not.toContain('Application Variations');});
  it('shows only the amount fields required by the selected application basis',async()=>{const node=await render();const select=node.querySelector('select');await act(async()=>{select.value='cumulative_less_previous_application';select.dispatchEvent(new Event('change',{bubbles:true}));});expect(node.textContent).toContain('Cumulative gross');expect(node.textContent).toContain('Previous application');expect(node.textContent).not.toContain('Previous certified');await act(async()=>{select.value='cumulative_less_previous_certified';select.dispatchEvent(new Event('change',{bubbles:true}));});expect(node.textContent).toContain('Previous certified');});
  it('renders frozen submitted application read-only with immutable comparison evidence',async()=>{const application={applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1500,retentionStated:null};const node=await render({editable:false,certificate:{id:'cert',status:'submitted',submissionApplicationSnapshot:{application,comparison:{comparable:true,applicationCurrentGross:1500,assessmentCurrentGross:1000,difference:-500,comparisonBasis:'Current-period gross'}}}});expect(node.textContent).toContain('£1,500.00');expect(node.textContent).toContain('-£500.00');expect(node.textContent).toContain('Assessment differs from application');expect(node.querySelector('input')).toBeNull();});
  it('uses active Revision 2 for a rejected Draft without repeating saved facts or comparison',async()=>{const revision1={id:'rev-1',applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1500,revisionNumber:1,status:'superseded'};const revision2={...revision1,id:'rev-2',currentPeriodGrossClaimed:1400,revisionNumber:2,status:'recorded',supersedesId:'rev-1'};vi.mocked(listPaymentApplications).mockResolvedValue([revision2,revision1]);const node=await render({certificate:{id:'cert',status:'draft',version:4,submissionApplicationSnapshot:{application:revision1,comparison:{comparable:true,applicationCurrentGross:1500,assessmentCurrentGross:1000,difference:-500,comparisonBasis:'Current-period gross'}}}});expect(node.textContent).toContain('Saved · Revision 2');expect(node.textContent).not.toContain('BuildLite Assessment');expect(node.textContent).not.toContain('Application Variations');expect(node.querySelector('input[type="number"]').value).toBe('1400');});
  it('uses the immutable locked snapshot for an approved certificate',async()=>{const application={id:'rev-2',applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1400,revisionNumber:2,status:'recorded'};const node=await render({editable:false,certificate:{id:'cert',status:'locked',lockedApplicationSnapshot:{application,comparison:{comparable:true,applicationCurrentGross:1400,assessmentCurrentGross:1000,difference:-400,comparisonBasis:'Current-period gross'}}}});expect(node.textContent).toContain('£1,400.00');expect(node.textContent).toContain('-£400.00');expect(node.textContent).toContain('Revision2');expect(node.querySelector('input')).toBeNull();});
  it('shares the frozen comparison with the page summary without another application request',async()=>{vi.mocked(listPaymentApplications).mockClear();const onComparisonChanged=vi.fn();const application={id:'rev-2',applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1400,revisionNumber:2,status:'recorded'};await render({editable:false,onComparisonChanged,certificate:{id:'cert',status:'locked',lockedApplicationSnapshot:{application,comparison:{comparable:true,applicationCurrentGross:1400,assessmentCurrentGross:1000,difference:-400,comparisonBasis:'Current-period gross'}}}});expect(onComparisonChanged).toHaveBeenCalledWith(expect.objectContaining({applicationCurrentGross:1400,difference:-400}));expect(listPaymentApplications).not.toHaveBeenCalled();});
  it('records and revises through the existing authoritative commands',async()=>{const created={id:'app-1',applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1500,revisionNumber:1,status:'recorded'};vi.mocked(createPaymentApplication).mockResolvedValue(created);const node=await render();await act(async()=>{[...node.querySelectorAll('button')].find((button)=>button.textContent==='Record application').click();await Promise.resolve();});expect(createPaymentApplication).toHaveBeenCalledWith('pkg',expect.objectContaining({certificateId:'cert',applicationBasis:'current_period_gross'}));expect(node.textContent).toContain('Saved · Revision 1');vi.mocked(revisePaymentApplication).mockResolvedValue({...created,id:'app-2',revisionNumber:2});await act(async()=>{[...node.querySelectorAll('button')].find((button)=>button.textContent==='Record revised application').click();await Promise.resolve();});expect(revisePaymentApplication).toHaveBeenCalledWith('pkg','app-1',expect.objectContaining({certificateId:'cert'}));});
});
