const gbp=(value)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(value)||0);
export default function PaymentCertificateSourceAuthority({certificate}){
 const items=certificate?.paymentDiscoveredItems||[]; const authority=certificate?.sourceAuthority; const assessments=authority?.evidence?.variationAssessments||[];
 return <section className="po-module-card po-cert-source-authority">
  <h3 className="po-matrix-section__title">Source authority</h3>
  <p className="po-cert-detail__matrix-lead">Explain what backs this assessment. Payment-discovered items are clearly retained as not previously approved.</p>
  {authority?.state==='not_captured'?<p className="po-cert-detail__readonly-note">Legacy locked certificate — source authority not captured.</p>:authority?<><dl className="po-cert-detail__commercial-grid"><div><dt>Ordered work</dt><dd>{gbp(authority.orderedWorkGross)}</dd></div><div><dt>Approved PO authority</dt><dd>{gbp(authority.approvedPoAuthority)}</dd></div><div><dt>Ordered work backed</dt><dd>{gbp(authority.orderedWorkBackedGross)}</dd></div><div><dt>Ordered excess</dt><dd>{gbp(authority.orderedWorkExcessGross)}</dd></div><div><dt>Approved CE</dt><dd>{gbp(authority.approvedCeGross)}</dd></div><div><dt>Issued VO</dt><dd>{gbp(authority.issuedVoGross)}</dd></div><div><dt>Variation Account assessment</dt><dd>{gbp(authority.variationAssessmentGross)}</dd></div><div className="po-cert-detail__commercial-item--emphasis"><dt>Unapproved certified gross</dt><dd>{gbp(authority.unapprovedCertifiedGross)}</dd></div></dl>{assessments.length?<div className="po-cert-detail__readonly-note"><strong>Variation Account evidence</strong>{assessments.map(item=><div key={item.id}>{item.variationReference||'Variation Account item'}{item.description?` — ${item.description}`:''}: assessment {gbp(item.signedAmount)} · prior authority {gbp(item.priorAuthority)} · unapproved {gbp(item.unapprovedAmount)}</div>)}</div>:null}</>:null}
  {items.length?<><h4>Legacy payment-discovered evidence</h4><table className="po-data-table"><thead><tr><th>Description</th><th>Basis</th><th>Status / provenance</th><th>Signed amount</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.description}</td><td>{item.basis}</td><td>Legacy payment-discovered / not previously approved · {item.status}</td><td>{gbp(item.signedAmount)}</td></tr>)}</tbody></table></>:<p className="po-cert-detail__readonly-note">No legacy payment-discovered items.</p>}
 </section>;
}
