import {useEffect,useState} from 'react';
import {useBuildLitePermission} from '../auth/BuildLiteAuthProvider';
import {listVariationAssessments,saveVariationAssessment,withdrawVariationAssessment} from '../api/paymentCertificates';
import {refreshCertificatesForPackage} from '../payments/paymentCertificateServerCache';
const gbp=value=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(value)||0);
export default function PaymentCertificateVariationAssessments({packageId,certificate,editable,onChanged}){
 const canAssess=useBuildLitePermission('variation_account.assess'),[items,setItems]=useState([]),[drafts,setDrafts]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{if(!packageId||!certificate?.id)return;const result=await listVariationAssessments(packageId,certificate.id);setItems(result.items||[]);setDrafts(Object.fromEntries((result.items||[]).map(item=>[item.variationAccountItemId,{amount:item.assessment?.currentAssessment??'',basis:item.assessment?.basis??''}])));};
 useEffect(()=>{load().catch(e=>setError(e.message));},[packageId,certificate?.id,certificate?.version]);
 const set=(id,key,value)=>setDrafts(all=>({...all,[id]:{...(all[id]||{}),[key]:value}}));
 const run=async action=>{setBusy(true);setError('');try{await action();await refreshCertificatesForPackage(packageId);await load();onChanged?.();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <section className="po-module-card po-cert-va-assessments"><h3 className="po-matrix-section__title">Variation Account — QS Assessment</h3><p className="po-cert-detail__matrix-lead">Value the canonical package variation account. Contractor position, claim, QS Forecast and certificate assessment remain separate facts.</p>{error?<div role="alert" className="po-list-feedback po-list-feedback--error">{error}</div>:null}
  {items.length?<div className="po-table-scroll"><table className="po-data-table"><thead><tr><th>Variation</th><th>Contractor Value</th><th>Contractor Claim</th><th>QS Forecast</th><th>Previous Certified</th><th>QS Assessment</th><th>Cumulative</th><th>Authority</th></tr></thead><tbody>{items.map(item=>{const draft=drafts[item.variationAccountItemId]||{},amount=Number(draft.amount)||0,cumulative=Number(item.previousCertified)+amount,aboveClaim=item.contractorClaim!=null&&(item.contractorClaim>=0?cumulative>item.contractorClaim:cumulative<item.contractorClaim);return <tr key={item.variationAccountItemId}><td><strong>{item.reference}</strong><br/>{item.description}<br/><small>{item.inCurrentApplication?'Matched to current application':'Not included in current application'}</small></td><td>{item.contractorValue==null?'Not recorded':gbp(item.contractorValue)}<br/><small>Recorded contractor position; not accepted entitlement</small></td><td>{item.contractorClaim==null?'Not claimed':gbp(item.contractorClaim)}</td><td>{gbp(item.qsForecast)}</td><td>{gbp(item.previousCertified)}</td><td>{editable&&canAssess?<><input aria-label={`${item.reference} assessment`} className="input" type="number" step="0.01" value={draft.amount??''} onChange={e=>set(item.variationAccountItemId,'amount',e.target.value)}/><input aria-label={`${item.reference} assessment basis`} className="input" placeholder="QS assessment basis" value={draft.basis??''} onChange={e=>set(item.variationAccountItemId,'basis',e.target.value)}/>{aboveClaim?<small className="po-cert-application__variance">Above contractor claim — reason required.</small>:null}<button type="button" disabled={busy||!draft.amount||!String(draft.basis||'').trim()} onClick={()=>run(()=>saveVariationAssessment(packageId,certificate.id,{variationAccountItemId:item.variationAccountItemId,applicationVariationLineId:item.applicationVariationLineId,currentAssessment:Number(draft.amount),basis:draft.basis}))}>{item.assessment?'Update':'Apply'} assessment</button>{item.assessment?<button type="button" className="po-cert-workspace__link po-cert-workspace__link--danger" disabled={busy} onClick={()=>run(()=>withdrawVariationAssessment(packageId,certificate.id,item.assessment.id))}>Remove</button>:null}</>:item.assessment?gbp(item.assessment.currentAssessment):gbp(0)}</td><td>{gbp(item.assessment?.cumulativeCertified??cumulative)}</td><td>Prior authority {gbp(item.assessment?.sourceAuthoritySnapshot?.priorAuthority||0)}<br/><strong>Unapproved {gbp(item.assessment?.sourceAuthoritySnapshot?.unapprovedAmount??Math.max(0,amount))}</strong></td></tr>})}</tbody></table></div>:<p>No active Variation Account items on this package.</p>}
 </section>;
}
