import {useEffect,useState} from 'react';
import {commercialDocumentPdfUrl,generateCombinedCertificatePaymentNoticeDocument,generatePayLessNoticeDocument,generatePaymentCertificateDocument,generatePaymentNoticeDocument,issueCommercialDocument,listCertificateDocuments} from '../api/commercialDocuments';
import {authenticatedBlob} from '../auth/authenticatedFetch';

const dateTime=value=>value?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';
const labels={payment_certificate:'Payment Certificate',payment_notice:'Payment Notice',combined_certificate_payment_notice:'Certificate + Payment Notice',pay_less_notice:'Pay Less Notice'};
export default function PaymentCertificateDocuments({certificate,packageId}){
  const [documents,setDocuments]=useState([]),[eligibility,setEligibility]=useState(null),[selectedType,setSelectedType]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function load(){if(certificate?.status!=='locked'||!packageId||!certificate?.id)return;const result=await listCertificateDocuments(packageId,certificate.id);setDocuments(result.documents||[]);setEligibility(result.eligibility||null);}
  useEffect(()=>{load().catch(error=>setMessage(error.message));},[packageId,certificate?.id,certificate?.status]);
  async function act(fn){setBusy(true);setMessage('');try{await fn();await load();setMessage('Document authority updated.');}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  if(certificate?.status!=='locked')return null;
  const available=Object.entries(eligibility?.available||{}).filter(([,value])=>value).map(([type])=>type);
  const type=available.includes(selectedType)?selectedType:(available[0]||'');
  const generate={payment_certificate:generatePaymentCertificateDocument,payment_notice:generatePaymentNoticeDocument,combined_certificate_payment_notice:generateCombinedCertificatePaymentNoticeDocument,pay_less_notice:generatePayLessNoticeDocument};
  const issuedTypes=new Set(documents.filter(document=>document.status==='issued').map(document=>document.type));
  const generations=new Map();for(const document of [...documents].sort((a,b)=>new Date(a.generatedAt)-new Date(b.generatedAt)||a.id.localeCompare(b.id))){generations.set(document.id,(generations.get(`count:${document.type}`)||0)+1);generations.set(`count:${document.type}`,generations.get(document.id));}
  return <section className="po-module-card po-cert-documents" aria-labelledby="certificate-documents-heading"><div className="po-cert-notices__heading"><div><h3 id="certificate-documents-heading">Commercial documents</h3><p>Generated PDFs freeze existing authority. Document Issue is a separate explicit action.</p></div>{type?<div><label>Document type<select value={type} disabled={busy} onChange={event=>setSelectedType(event.target.value)}>{available.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><button className="po-btn-primary" disabled={busy} onClick={()=>act(()=>generate[type](packageId,certificate.id))}>{busy?'Working…':`Generate ${labels[type]}`}</button></div>:<p>No further document generation is currently available.</p>}</div>
    {documents.length?<div className="po-table-wrap"><table className="po-data-table"><thead><tr><th>Type</th><th>Reference</th><th>Generation</th><th>Generated</th><th>Status</th><th>Checksum</th><th>Actions</th></tr></thead><tbody>{documents.map(document=><tr key={document.id}><td>{labels[document.type]||document.type}</td><td>{document.reference}</td><td>Generation {generations.get(document.id)}</td><td>{dateTime(document.generatedAt)}</td><td>{document.status}</td><td title={document.sha256}>{document.sha256?.slice(0,12)}…</td><td><button className="po-list-btn-secondary" onClick={()=>act(()=>authenticatedBlob(commercialDocumentPdfUrl(document.id)))}>View</button> <button className="po-list-btn-secondary" onClick={()=>act(()=>authenticatedBlob(commercialDocumentPdfUrl(document.id,{download:true}),{downloadName:`${document.reference}.pdf`}))}>Download</button>{!issuedTypes.has(document.type)&&document.status==='generated'?<button disabled={busy} onClick={()=>act(()=>issueCommercialDocument(document.id))}>Issue</button>:null}</td></tr>)}</tbody></table></div>:<p>No commercial documents generated.</p>}
    {message?<p role={message==='Document authority updated.'?'status':'alert'}>{message}</p>:null}
  </section>;
}
