// @vitest-environment jsdom
import React from 'react';import {act} from 'react';import {createRoot} from 'react-dom/client';import {afterEach,beforeEach,expect,it,vi} from 'vitest';import PaymentCertificateDocuments from './PaymentCertificateDocuments';
vi.mock('../api/commercialDocuments',()=>({listCertificateDocuments:vi.fn(),generatePaymentCertificateDocument:vi.fn(),issueCommercialDocument:vi.fn(),commercialDocumentPdfUrl:vi.fn(id=>`/documents/${id}.pdf`)}));
import {generatePaymentCertificateDocument,issueCommercialDocument,listCertificateDocuments} from '../api/commercialDocuments';
let host,root;beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);listCertificateDocuments.mockResolvedValue({documents:[]});});afterEach(()=>{act(()=>root.unmount());host.remove();vi.clearAllMocks();});
it('is unavailable before the certificate is Locked',async()=>{await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'submitted'}} packageId="p"/>));expect(host.textContent).toBe('');expect(listCertificateDocuments).not.toHaveBeenCalled();});
it('labels generations and hides Generate and Issue after an Issued authority exists',async()=>{listCertificateDocuments.mockResolvedValue({documents:[{id:'d1',reference:'PC-1',status:'generated',generatedAt:'2026-09-01T10:00:00Z',sha256:'a'.repeat(64)},{id:'d2',reference:'PC-1',status:'issued',generatedAt:'2026-09-01T09:00:00Z',sha256:'b'.repeat(64)}]});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});expect(host.textContent).toContain('Generation 1');expect(host.textContent).toContain('Generation 2');expect(host.textContent).toContain('Issued authority is frozen');expect(host.querySelectorAll('button')).toHaveLength(0);});
it('permits Issue from Generated before any document is Issued',async()=>{listCertificateDocuments.mockResolvedValue({documents:[{id:'d1',reference:'PC-1',status:'generated',generatedAt:'2026-09-01T10:00:00Z',sha256:'a'.repeat(64)}]});issueCommercialDocument.mockResolvedValue({});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});const issue=[...host.querySelectorAll('button')].find(x=>x.textContent==='Issue');await act(async()=>issue.click());expect(issueCommercialDocument).toHaveBeenCalledWith('d1');});
it('generates a new frozen document through the explicit action',async()=>{generatePaymentCertificateDocument.mockResolvedValue({});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});await act(async()=>host.querySelector('button').click());expect(generatePaymentCertificateDocument).toHaveBeenCalledWith('p','c');});
