// @vitest-environment jsdom
import React from 'react';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { createRoot } from 'react-dom/client';
import { act } from 'react';
let permissions=[];
vi.mock('../auth/BuildLiteAuthProvider',()=>({useBuildLitePermission:value=>permissions.includes(value)}));
const api=vi.hoisted(()=>({getPaymentApprovalQueue:vi.fn(),approveSubmittedCertificate:vi.fn(),rejectCertificateForPackage:vi.fn()}));
vi.mock('../api/paymentAuthority',()=>({getPaymentApprovalQueue:api.getPaymentApprovalQueue,approveSubmittedCertificate:api.approveSubmittedCertificate}));
vi.mock('../api/paymentCertificates',()=>({rejectCertificateForPackage:api.rejectCertificateForPackage}));
import PaymentApprovalRun from './PaymentApprovalRun';

const base={id:'c1',certificateId:'c1',packageId:'p1',certificateVersion:2,certificateNumber:1,development:'Hawthorn Gardens UAT',subcontractor:'Peak Roofing Ltd',packageTrade:'4180 / Roofing',gross:38400,contractorApplication:38400,applicationDifference:0,orderedWorks:38400,variations:0,otherAssessed:0,appliedPriorAuthority:0,unapprovedAtLock:0,retention:1920,recoveries:0,vat:7296,net:43776,notifiedSum:43776,intendedPayment:43776,payLessReduction:0,cashAmountProposed:43776,dueDate:'2026-10-05',paymentNoticeDeadline:'2026-10-10',payLessDeadline:'2026-10-14',finalPaymentDate:'2026-10-19',submittedBy:'QS User',submittedAt:'2026-09-29T14:11:25Z',workflowState:'awaiting_approval',statusSummary:'Awaiting Approval',eligible:true,warnings:[],hardBlockers:[],lines:[]};
const warning={...base,id:'c2',certificateId:'c2',certificateNumber:2,statusSummary:'1 warning',warnings:[{code:'payment_notice_incomplete',meaning:'The required Payment Notice has not been issued.'}]};
const blocked={...base,id:'c3',certificateId:'c3',certificateNumber:3,eligible:false,statusSummary:'Approval blocked',hardBlockers:['Authoritative certificate calculation is unavailable.']};
const authorised={...base,id:'c4',certificateId:'c4',certificateNumber:4,workflowState:'authorised',statusSummary:'Payment Authorised',authorisedCashAmount:900};
const exceptional={...base,id:'c5',certificateId:'c5',certificateNumber:5,gross:48600,contractorApplication:52000,applicationDifference:-3400,orderedWorks:38400,variations:10200,appliedPriorAuthority:7200,unapprovedAtLock:3000,retention:2430,vat:9234,net:55404,notifiedSum:55404,intendedPayment:55404,cashAmountProposed:55404,lines:[{assessmentId:'a-supported',variationAccountItemId:'va-1',reference:'VA-0001',description:'Drainage',assessment:7200,appliedPriorAuthority:7200,authorityEnvelope:9600,unapprovedAtLock:0,unresolvedAmount:0,supportingSources:[{allocationId:'vo-1',sourceType:'variation_order_line',sourceReference:'S0001/VO-0001',appliedAmount:7200}]},{assessmentId:'a-exception',variationAccountItemId:'va-2',reference:'VA-0002',description:'Additional muck away',assessment:3000,appliedPriorAuthority:0,authorityEnvelope:0,unapprovedAtLock:3000,unresolvedAmount:3000,supportingSources:[]}]};
const authorisedExceptional={...exceptional,id:'c6',certificateId:'c6',certificateNumber:6,workflowState:'authorised',statusSummary:'Payment Authorised',authorisedCashAmount:55404,paymentAuthority:{decisionId:'decision-6',runReference:'PAR-COMB-006',authorisedCash:55404,reason:'Payment authorisation',certificateVersion:5,approvedBy:{displayName:'David Morris'},approvedAt:'2026-09-30T14:49:06Z'},lines:exceptional.lines.map(line=>line.assessmentId==='a-exception'?{...line,unresolvedAmount:0,exceptionalAuthorityDecisions:[{decisionId:'decision-6',authorityGranted:3000,reversedAmount:0,activeAuthority:3000,status:'active',sourceType:'payment_authority',sourceReference:'Payment Authority · Certificate 6',reason:'Work verified on site; formal instruction outstanding.',approvedBy:{displayName:'David Morris'},approvedAt:'2026-09-30T14:49:06Z'}]}:line)};
const setValue=async(node,value)=>{const prototype=node.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(prototype,'value').set;await act(async()=>{setter.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));});};
const button=(host,label,dialog=false)=>[...(dialog?document.querySelector('[role="dialog"]'):host).querySelectorAll('button')].find(node=>node.textContent===label||node.textContent.includes(label));

describe('PaymentApprovalRun single commercial approval',()=>{
 let host,root;
 beforeEach(async()=>{permissions=['payment_approval_run.view','certificate.lock','payment_authority.approve'];host=document.createElement('div');document.body.append(host);root=createRoot(host);api.getPaymentApprovalQueue.mockResolvedValue([base,warning,blocked,exceptional,authorised,authorisedExceptional]);api.approveSubmittedCertificate.mockResolvedValue({ok:true});api.rejectCertificateForPackage.mockResolvedValue({});await act(async()=>{root.render(<PaymentApprovalRun/>);await Promise.resolve();});});
 afterEach(()=>{root.unmount();host.remove();vi.clearAllMocks();});
 it('defaults to the Submitted queue and keeps genuine authority history separate',()=>{expect(host.textContent).toContain('Awaiting Approval (4)');expect(host.textContent).toContain('Certificate 1');expect(host.textContent).not.toContain('Certificate 4');expect(host.textContent).toContain('Payment Authorised (2)');expect(host.querySelector('input[aria-label="Select certificate 3"]').disabled).toBe(true);});
 it('keeps process warnings visible without requiring acknowledgement or comment',async()=>{await act(async()=>host.querySelector('input[aria-label="Select certificate 2"]').click());expect(button(host,'Approve & Authorise Selected').disabled).toBe(false);await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 2')).querySelector('button').click());expect(host.textContent).toContain('The required Payment Notice has not been issued.');expect(host.querySelector('input[aria-label="Acknowledge warnings for certificate 2"]')).toBeNull();});
 it('shows the submitted payment bridge and every contractual timetable date',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 1')).querySelector('button').click());expect(host.textContent).toContain('Payment calculation');expect(host.textContent).toContain('Gross assessment£38,400.00');expect(host.textContent).toContain('Retention−£1,920.00');expect(host.textContent).toContain('VAT£7,296.00');expect(host.textContent).toContain('Net payment£43,776.00');expect(host.textContent).toContain('Due date5 Oct 2026');expect(host.textContent).toContain('Payment Notice deadline10 Oct 2026');expect(host.textContent).toContain('Pay Less deadline14 Oct 2026');expect(host.textContent).toContain('Final payment date19 Oct 2026');});
 it('requires acknowledgement and reason for an exceptional cash authority',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 1')).querySelector('button').click());await setValue(host.querySelector('input[aria-label="Certificate 1 cash authority"]'),'850');await act(async()=>host.querySelector('input[aria-label="Select certificate 1"]').click());expect(button(host,'Approve & Authorise Selected').disabled).toBe(true);expect(host.textContent).toContain('Commercial authority exception');await act(async()=>host.querySelector('input[aria-label="Acknowledge commercial exception for certificate 1"]').click());await setValue(host.querySelector('textarea[aria-label="Certificate 1 exception reason"]'),'Exceptional cash position approved.');expect(button(host,'Approve & Authorise Selected').disabled).toBe(false);});
 it('uses the combined endpoint without actor, browser totals or process-warning declarations',async()=>{await act(async()=>host.querySelector('input[aria-label="Select certificate 2"]').click());await act(async()=>button(host,'Approve & Authorise Selected').click());await act(async()=>button(host,'Approve & Authorise',true).click());const payload=api.approveSubmittedCertificate.mock.calls[0][0];expect(payload).toMatchObject({packageId:'p1',certificateId:'c2',certificateVersion:2,cashAmount:43776,reason:'Payment authorisation',warningAcknowledgements:[],warningComment:''});expect(payload).not.toHaveProperty('actor');expect(payload).not.toHaveProperty('gross');expect(payload).not.toHaveProperty('net');});
 it('returns to QS only after a reason',async()=>{await act(async()=>button(host,'Return to QS').click());const action=button(host,'Return to QS',true);expect(action.disabled).toBe(true);await setValue(document.querySelector('textarea[aria-label="Return to QS reason"]'),'Please revise.');await act(async()=>action.click());expect(api.rejectCertificateForPackage).toHaveBeenCalledWith('p1','c1',{version:2,comment:'Please revise.'});});
 it('requires both domain permissions for selection',async()=>{permissions=['payment_approval_run.view','certificate.lock'];await act(async()=>root.render(<PaymentApprovalRun/>));expect(host.querySelector('input[aria-label="Select certificate 1"]').disabled).toBe(true);});
 it('gates unsupported authority until the exact VA decision and human reason are explicit',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 5')).querySelector('button').click());expect(host.textContent).toContain('Exceptional commercial authority required');expect(host.textContent).toContain('has not previously been authorised through a Commercial Event or Variation Order');expect(host.textContent).toContain('Unsupported£3,000.00');await act(async()=>host.querySelector('input[aria-label="Select certificate 5"]').click());expect(button(host,'Approve & Authorise Selected').disabled).toBe(true);await act(async()=>host.querySelector('input[aria-label="Approve exceptional authority for VA-0002"]').click());expect(host.querySelector('input[aria-label="VA-0002 new commercial authority"]').value).toBe('3000');expect(button(host,'Approve & Authorise Selected').disabled).toBe(true);await setValue(host.querySelector('textarea[aria-label="VA-0002 exceptional authority reason"]'),'Work verified; instruction outstanding.');expect(button(host,'Approve & Authorise Selected').disabled).toBe(false);});
 it('keeps refusal out of the approval payload and directs the approver to Return to QS',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 5')).querySelector('button').click());await act(async()=>host.querySelector('input[aria-label="Do not approve exceptional authority for VA-0002"]').click());await act(async()=>host.querySelector('input[aria-label="Select certificate 5"]').click());expect(button(host,'Approve & Authorise Selected').disabled).toBe(true);expect(host.textContent).toContain('Return the certificate to QS');});
 it('enumerates exceptional authority separately in confirmation and sends explicit immutable evidence',async()=>{await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 5')).querySelector('button').click());await act(async()=>host.querySelector('input[aria-label="Approve exceptional authority for VA-0002"]').click());await setValue(host.querySelector('textarea[aria-label="VA-0002 exceptional authority reason"]'),'Work verified; instruction outstanding.');await act(async()=>host.querySelector('input[aria-label="Select certificate 5"]').click());await act(async()=>button(host,'Approve & Authorise Selected').click());const dialog=document.querySelector('[role="dialog"]');expect(dialog.textContent).toContain('Lock Certificate 5 at £48,600.00 gross');expect(dialog.textContent).toContain('Create Payment Authority for £55,404.00');expect(dialog.textContent).toContain('Create £3,000.00 exceptional commercial authority for VA-0002');expect(dialog.textContent).toContain('Current Contract will not change');expect(dialog.textContent).toContain('no Commercial Event or Variation Order');await act(async()=>button(host,'Approve & Authorise',true).click());expect(api.approveSubmittedCertificate.mock.calls[0][0].lines[1]).toMatchObject({assessmentId:'a-exception',exceptionalAuthorityDecision:'approve',exceptionalAuthorityReason:'Work verified; instruction outstanding.',newCommercialAuthority:3000});});
 it('shows persisted exceptional authority and overall Payment Authority provenance only in authorised history',async()=>{await act(async()=>button(host,'Payment Authorised').click());await act(async()=>[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 6')).querySelector('button').click());expect(host.textContent).toContain('Prior authority at submission£0.00');expect(host.textContent).toContain('Unsupported at submission£3,000.00');expect(host.textContent).toContain('Authority granted£3,000.00');expect(host.textContent).toContain('Payment Authority · Certificate 6');expect(host.textContent).toContain('Work verified on site; formal instruction outstanding.');expect(host.textContent).toContain('Approved byDavid Morris');expect(host.textContent).toContain('did not create a Commercial Event or Variation Order and did not change Current Contract');expect(host.textContent).toContain('PAR-COMB-006');expect(host.textContent).toContain('Authorised cash £55,404.00');const routine=[...host.querySelectorAll('tr')].find(row=>row.textContent.includes('Certificate 4'));await act(async()=>routine.querySelector('button').click());expect(routine.nextSibling.textContent).not.toContain('Exceptional authority decision');});
});
