// @vitest-environment jsdom
import React from 'react';
import { createRoot } from 'react-dom/client';
import { act } from 'react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import PaymentCertificateApplication from './PaymentCertificateApplication';
import { listPaymentApplications } from '../api/paymentApplications';

vi.mock('../api/paymentApplications',()=>({listPaymentApplications:vi.fn(async()=>[]),createPaymentApplication:vi.fn(),revisePaymentApplication:vi.fn()}));
let container;
afterEach(()=>{container?.remove();container=null;vi.mocked(listPaymentApplications).mockResolvedValue([]);});
async function render(props={}){container=document.createElement('div');document.body.append(container);await act(async()=>{createRoot(container).render(<PaymentCertificateApplication packageId="pkg" certificate={{id:'cert',status:'draft'}} assessmentGross={1000} editable {...props}/>);});return container;}

describe('PaymentCertificateApplication',()=>{
  it('renders quick capture and neutral notice guard',async()=>{const node=await render();expect(node.textContent).toContain('Application Ref');expect(node.textContent).toContain('Notice readiness not yet configured');});
  it('shows only the amount fields required by the selected application basis',async()=>{const node=await render();const select=node.querySelector('select');await act(async()=>{select.value='cumulative_less_previous_application';select.dispatchEvent(new Event('change',{bubbles:true}));});expect(node.textContent).toContain('Cumulative gross');expect(node.textContent).toContain('Previous application');expect(node.textContent).not.toContain('Previous certified');await act(async()=>{select.value='cumulative_less_previous_certified';select.dispatchEvent(new Event('change',{bubbles:true}));});expect(node.textContent).toContain('Previous certified');});
  it('renders frozen submitted application read-only with variance and missing values',async()=>{const application={applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1500,retentionStated:null};const node=await render({editable:false,certificate:{id:'cert',status:'submitted',submissionApplicationSnapshot:{application,comparison:{comparable:true,applicationCurrentGross:1500,assessmentCurrentGross:1000,difference:-500,comparisonBasis:'Current-period gross'}}}});expect(node.textContent).toContain('£1,500.00');expect(node.textContent).toContain('-£500.00');expect(node.textContent).toContain('Assessment differs from application');expect(node.querySelector('input')).toBeNull();});
  it('uses active Revision 2 for a rejected Draft instead of its retained submission snapshot',async()=>{const revision1={id:'rev-1',applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1500,revisionNumber:1,status:'superseded'};const revision2={...revision1,id:'rev-2',currentPeriodGrossClaimed:1400,revisionNumber:2,status:'recorded',supersedesId:'rev-1'};vi.mocked(listPaymentApplications).mockResolvedValue([revision2,revision1]);const node=await render({certificate:{id:'cert',status:'draft',version:4,submissionApplicationSnapshot:{application:revision1,comparison:{comparable:true,applicationCurrentGross:1500,assessmentCurrentGross:1000,difference:-500,comparisonBasis:'Current-period gross'}}}});await act(async()=>{await Promise.resolve();});expect(node.textContent).toContain('£1,400.00');expect(node.textContent).toContain('-£400.00');expect(node.textContent).toContain('Revision2');expect(node.textContent).not.toContain('-£500.00');});
  it('uses the immutable locked snapshot for an approved certificate',async()=>{const application={id:'rev-2',applicationReference:'APP-1',applicationBasis:'current_period_gross',currentPeriodGrossClaimed:1400,revisionNumber:2,status:'recorded'};const node=await render({editable:false,certificate:{id:'cert',status:'locked',lockedApplicationSnapshot:{application,comparison:{comparable:true,applicationCurrentGross:1400,assessmentCurrentGross:1000,difference:-400,comparisonBasis:'Current-period gross'}}}});expect(node.textContent).toContain('£1,400.00');expect(node.textContent).toContain('-£400.00');expect(node.textContent).toContain('Revision2');expect(node.querySelector('input')).toBeNull();});
});
