// @vitest-environment jsdom
import React from 'react';import {act} from 'react';import {createRoot} from 'react-dom/client';import {afterEach,beforeEach,expect,it,vi} from 'vitest';import PaymentCertificateDocuments from './PaymentCertificateDocuments';
vi.mock('../api/commercialDocuments',()=>({listCertificateDocuments:vi.fn(),generatePaymentCertificateDocument:vi.fn(),generatePaymentNoticeDocument:vi.fn(),generateCombinedCertificatePaymentNoticeDocument:vi.fn(),generatePayLessNoticeDocument:vi.fn(),issueCommercialDocument:vi.fn(),commercialDocumentPdfUrl:vi.fn(id=>`/documents/${id}.pdf`)}));
import {generateCombinedCertificatePaymentNoticeDocument,generatePayLessNoticeDocument,generatePaymentCertificateDocument,generatePaymentNoticeDocument,issueCommercialDocument,listCertificateDocuments} from '../api/commercialDocuments';
const eligibility=available=>({locked:true,issuedPaymentNotice:true,noticeMode:'certificate_as_payment_notice',available});
let host,root;beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);listCertificateDocuments.mockResolvedValue({documents:[],eligibility:eligibility({payment_certificate:true,payment_notice:false,combined_certificate_payment_notice:false})});});afterEach(()=>{act(()=>root.unmount());host.remove();vi.clearAllMocks();});
it('is unavailable before the certificate is Locked',async()=>{await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'submitted'}} packageId="p"/>));expect(host.textContent).toBe('');expect(listCertificateDocuments).not.toHaveBeenCalled();});
it('labels generations by document type and hides later Issue for an Issued type',async()=>{listCertificateDocuments.mockResolvedValue({documents:[{id:'d1',type:'payment_certificate',reference:'PC-1',status:'generated',generatedAt:'2026-09-01T10:00:00Z',sha256:'a'.repeat(64)},{id:'d2',type:'payment_certificate',reference:'PC-1',status:'issued',generatedAt:'2026-09-01T09:00:00Z',sha256:'b'.repeat(64)},{id:'n1',type:'payment_notice',reference:'PN-1',status:'generated',generatedAt:'2026-09-01T11:00:00Z',sha256:'c'.repeat(64)}],eligibility:eligibility({payment_certificate:false,payment_notice:true,combined_certificate_payment_notice:true})});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});expect(host.textContent).toContain('Payment Notice');expect(host.textContent).toContain('Certificate + Payment Notice');expect(host.textContent.match(/Generation 1/g)).toHaveLength(2);expect(host.textContent).toContain('Generation 2');expect([...host.querySelectorAll('button')].filter(x=>x.textContent==='Issue')).toHaveLength(1);});
it('permits Issue from Generated before that document type is Issued',async()=>{listCertificateDocuments.mockResolvedValue({documents:[{id:'d1',type:'payment_certificate',reference:'PC-1',status:'generated',generatedAt:'2026-09-01T10:00:00Z',sha256:'a'.repeat(64)}],eligibility:eligibility({payment_certificate:true,payment_notice:false,combined_certificate_payment_notice:false})});issueCommercialDocument.mockResolvedValue({});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});const issue=[...host.querySelectorAll('button')].find(x=>x.textContent==='Issue');await act(async()=>issue.click());expect(issueCommercialDocument).toHaveBeenCalledWith('d1');});
it('generates only server-eligible document options',async()=>{listCertificateDocuments.mockResolvedValue({documents:[],eligibility:eligibility({payment_certificate:false,payment_notice:true,combined_certificate_payment_notice:true})});generatePaymentNoticeDocument.mockResolvedValue({});generateCombinedCertificatePaymentNoticeDocument.mockResolvedValue({});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});expect([...host.querySelectorAll('option')].map(option=>option.value)).toEqual(['payment_notice','combined_certificate_payment_notice']);await act(async()=>host.querySelector('button').click());expect(generatePaymentNoticeDocument).toHaveBeenCalledWith('p','c');await act(async()=>{const select=host.querySelector('select');select.value='combined_certificate_payment_notice';select.dispatchEvent(new Event('change',{bubbles:true}));});await act(async()=>host.querySelector('button').click());expect(generateCombinedCertificatePaymentNoticeDocument).toHaveBeenCalledWith('p','c');expect(generatePaymentCertificateDocument).not.toHaveBeenCalled();});
it('shows no generation action when all document authorities are already Issued',async()=>{listCertificateDocuments.mockResolvedValue({documents:[],eligibility:eligibility({payment_certificate:false,payment_notice:false,combined_certificate_payment_notice:false})});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});expect(host.textContent).toContain('No further document generation');expect(host.querySelector('button')).toBeNull();});
it('offers and generates Pay Less only when server eligibility allows it',async()=>{listCertificateDocuments.mockResolvedValue({documents:[],eligibility:eligibility({payment_certificate:false,payment_notice:false,combined_certificate_payment_notice:false,pay_less_notice:true})});generatePayLessNoticeDocument.mockResolvedValue({});await act(async()=>root.render(<PaymentCertificateDocuments certificate={{id:'c',status:'locked'}} packageId="p"/>));await act(async()=>{});expect([...host.querySelectorAll('option')].map(option=>option.value)).toEqual(['pay_less_notice']);expect(host.textContent).toContain('Pay Less Notice');await act(async()=>host.querySelector('button').click());expect(generatePayLessNoticeDocument).toHaveBeenCalledWith('p','c');});
