import { useEffect, useMemo, useState } from 'react';
import { getPlotTenureReview, applyPlotTenureReview } from '../api/developments';
import { PLOT_TENURE_OPTIONS } from '../developments/plotTenureAuthority';

const reviewedOptions=PLOT_TENURE_OPTIONS.filter(option=>option.value!=='UNREVIEWED');

export default function PlotTenureReviewWorkspace({developmentId,onBack,onApplied}){
  const [review,setReview]=useState(null),[choices,setChoices]=useState({}),[expanded,setExpanded]=useState(new Set()),[ack,setAck]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[info,setInfo]=useState('');
  useEffect(()=>{let live=true;setLoading(true);getPlotTenureReview(developmentId).then(next=>{if(!live)return;setReview(next);const initial={};for(const cohort of next.cohorts||[]){for(const plot of cohort.plots)initial[plot.id]=plot.tenureCode==='UNREVIEWED'?(cohort.suggestedTenureCode||'UNREVIEWED'):plot.tenureCode;}setChoices(initial);}).catch(e=>live&&setError(e.message||'Could not load tenure review.')).finally(()=>live&&setLoading(false));return()=>{live=false;};},[developmentId]);
  const decisions=useMemo(()=>review?.cohorts?.flatMap(cohort=>cohort.plots.map(plot=>({plotId:plot.id,sourceTenure:plot.sourceTenure,sourceFingerprint:plot.sourceFingerprint,previousTenureCode:plot.tenureCode,resultingTenureCode:choices[plot.id]})).filter(row=>row.resultingTenureCode&&row.resultingTenureCode!=='UNREVIEWED'&&row.resultingTenureCode!==row.previousTenureCode))||[],[review,choices]);
  const changesReviewed=decisions.some(row=>row.previousTenureCode!=='UNREVIEWED');
  const setCohort=(cohort,value)=>setChoices(current=>({...current,...Object.fromEntries(cohort.plots.map(plot=>[plot.id,value]))}));
  async function apply(){if(!decisions.length||saving||changesReviewed&&!ack)return;setSaving(true);setError('');try{const result=await applyPlotTenureReview(developmentId,{developmentVersion:review.developmentVersion,decisions,actor:'ignored'});setReview(result.review);setInfo(`${result.applied} tenure classification${result.applied===1?'':'s'} confirmed.`);onApplied?.(result.development);}catch(e){setError(e.message||'Could not confirm tenure classifications.');}finally{setSaving(false);}}
  if(loading)return <p>Loading tenure review…</p>;
  if(error&&!review)return <p role="alert">{error}</p>;
  return <section aria-label="Plot tenure review" className="po-module-card"><button type="button" className="btn btn--secondary" onClick={onBack}>← Back to Plot Master</button><h2>Tenure review</h2>
    <p><strong>Tenure classifications</strong><br/>{review.reviewed} of {review.total} reviewed · {review.needsAttention} need attention</p>
    {error?<p role="alert">{error}</p>:null}{info?<p role="status">{info}</p>:null}
    {(review.cohorts||[]).map(cohort=>{const cohortValues=new Set(cohort.plots.map(plot=>choices[plot.id]));const cohortChoice=cohortValues.size===1?[...cohortValues][0]:'MIXED';const isOpen=expanded.has(cohort.key);return <article key={cohort.key} className="po-module-card" aria-label={`Tenure cohort ${cohort.sourceTenure||'blank'}`}><h3>{cohort.sourceTenure||'Unknown / blank'}</h3><p>{cohort.plotCount} plot{cohort.plotCount===1?'':'s'}{cohort.suggestedTenureCode?` · Suggested: ${reviewedOptions.find(item=>item.value===cohort.suggestedTenureCode)?.label}`:' · Review required'}</p><label>BuildLite classification<select className="input" value={cohortChoice} onChange={e=>setCohort(cohort,e.target.value)}><option value="MIXED" disabled>Individual exceptions</option><option value="UNREVIEWED">Review required</option>{reviewedOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label><button type="button" className="btn btn--secondary" onClick={()=>setExpanded(current=>{const next=new Set(current);next.has(cohort.key)?next.delete(cohort.key):next.add(cohort.key);return next;})}>{isOpen?'Hide individual plots':'Review individual plots'}</button>{isOpen?<div>{cohort.plots.map(plot=><label key={plot.id}>Plot {plot.plotNumber}<select className="input" aria-label={`Plot ${plot.plotNumber} controlled tenure`} value={choices[plot.id]||'UNREVIEWED'} onChange={e=>setChoices(current=>({...current,[plot.id]:e.target.value}))}><option value="UNREVIEWED">Review required</option>{reviewedOptions.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></label>)}</div>:null}</article>;})}
    <p>{decisions.length} affected plot{decisions.length===1?'':'s'} ready to confirm.</p>{changesReviewed?<label><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/> I acknowledge that existing reviewed classifications will change.</label>:null}<button type="button" className="btn btn--primary" disabled={!decisions.length||saving||changesReviewed&&!ack} onClick={apply}>{saving?'Confirming…':`Confirm ${decisions.length} classifications`}</button>
  </section>;
}
