-- GP-5F.1: bounded Cost Code onboarding evidence and hierarchy review lifecycle.
CREATE TABLE cost_code_import_batches(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),client_id UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,source_filename TEXT NOT NULL,reviewed_rows_digest TEXT NOT NULL CHECK(reviewed_rows_digest ~ '^[0-9a-f]{64}$'),actor_user_id UUID REFERENCES buildlite_users(id) ON DELETE RESTRICT,actor_membership_id UUID REFERENCES client_user_memberships(id) ON DELETE RESTRICT,actor_provider_user_id TEXT,actor_display_name TEXT,actor_role_key TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE cost_code_import_row_evidence(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),client_id UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,batch_id UUID NOT NULL REFERENCES cost_code_import_batches(id) ON DELETE RESTRICT,cost_code_id UUID NOT NULL REFERENCES cost_codes(id) ON DELETE RESTRICT,source_row_number INTEGER NOT NULL CHECK(source_row_number>0),source_code TEXT NOT NULL,source_description TEXT NOT NULL,selected_hierarchy_evidence JSONB NOT NULL DEFAULT '{}'::jsonb,selected_target_mapping JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(batch_id,source_row_number));
ALTER TABLE cost_codes ADD COLUMN hierarchy_review_disposition TEXT,ADD COLUMN hierarchy_reviewed_at TIMESTAMPTZ,ADD COLUMN hierarchy_reviewed_by_user_id UUID REFERENCES buildlite_users(id) ON DELETE RESTRICT,ADD COLUMN hierarchy_reviewed_by_membership_id UUID REFERENCES client_user_memberships(id) ON DELETE RESTRICT,ADD COLUMN hierarchy_reviewed_by_provider_user_id TEXT,ADD COLUMN hierarchy_reviewed_by_display_name TEXT,ADD COLUMN hierarchy_reviewed_by_role_key TEXT,ADD CONSTRAINT chk_cost_code_hierarchy_review_disposition CHECK(hierarchy_review_disposition IS NULL OR hierarchy_review_disposition='not_applicable');
CREATE TABLE cost_code_hierarchy_review_audit(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),client_id UUID NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,cost_code_id UUID NOT NULL REFERENCES cost_codes(id) ON DELETE RESTRICT,operation TEXT NOT NULL CHECK(operation IN('allocate','clear','mark_not_applicable')),before_document JSONB NOT NULL,after_document JSONB NOT NULL,resulting_cost_code_version INTEGER NOT NULL CHECK(resulting_cost_code_version>0),actor_user_id UUID REFERENCES buildlite_users(id) ON DELETE RESTRICT,actor_membership_id UUID REFERENCES client_user_memberships(id) ON DELETE RESTRICT,actor_provider_user_id TEXT,actor_display_name TEXT,actor_role_key TEXT,actor_permission_key TEXT NOT NULL,occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE FUNCTION protect_cost_code_onboarding_evidence() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'Cost Code onboarding evidence is append-only';END $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_cost_code_import_batches_immutable BEFORE UPDATE OR DELETE ON cost_code_import_batches FOR EACH ROW EXECUTE FUNCTION protect_cost_code_onboarding_evidence();
CREATE TRIGGER trg_cost_code_import_rows_immutable BEFORE UPDATE OR DELETE ON cost_code_import_row_evidence FOR EACH ROW EXECUTE FUNCTION protect_cost_code_onboarding_evidence();
CREATE TRIGGER trg_cost_code_hierarchy_review_audit_immutable BEFORE UPDATE OR DELETE ON cost_code_hierarchy_review_audit FOR EACH ROW EXECUTE FUNCTION protect_cost_code_onboarding_evidence();
CREATE INDEX idx_cost_code_import_evidence_cost_code ON cost_code_import_row_evidence(client_id,cost_code_id,created_at DESC);
CREATE INDEX idx_cost_code_review_audit_cost_code ON cost_code_hierarchy_review_audit(client_id,cost_code_id,occurred_at DESC);
